### ISSUE TITLE
在unbuntu上运行linux.Ubuntu._amd64.tar.xz解压后的程序时，提示GtkDialog mapped without a transient parent

### ISSUE THREAD

**Issue by duyupeng** [NaiboWang/EasySpider#10]
在unbuntu18上运行解压后EasySpider_0.1.0_linux.Ubuntu._amd64.tar.xz，在使用本地运行爬虫后，终端提示GtkDialog mapped without a transient parent，没有后续弹出窗口，进行程序爬取和存储数据的运行。

**Comment by NaiboWang** [comment]
Ubuntu版本暂时只在20和22版本测试过，18版本没有测试，不过可以暂时通过以下方式解决。
1. 在任务执行阶段生成一个Execution ID，并记下： 
![image](https://user-images.githubusercontent.com/30287768/220240957-03b248a3-3bc8-420a-ade2-3ed6cd6e5b94.png)

2. 在EasySpider目录下打开terminal，并输入以下命令：
```
./EasySpider/resources/app/chrome_linux64/easyspider_executestage EID
```
将`EID`替换成刚刚生成的Execution ID，如：
```
./EasySpider/resources/app/chrome_linux64/easyspider_executestage 427
```

点击回车运行即可。
![image](https://user-images.githubusercontent.com/30287768/220241201-b9bee16f-3c62-4499-831b-201a8c03c7af.png)


有时间会测试18.04版本的使用，或者你也可以自己编译运行。

**Comment by duyupeng** [comment]
好的,非常感谢您的帮助.我按照以上方法测试后,发现需要GLIBC_2.28,但是unbuntu18的版本是GLIBC_2.27.所以应该是版本的问题.我这边还不太会编译.

**Comment by NaiboWang** [comment]
如果实在不会编译，就更换高版本的Ubuntu，或者用Windows

**Comment by duyupeng** [comment]
好的，谢谢帮助！
