### ISSUE TITLE
循环下一页无法找到element

### ISSUE THREAD

**Issue by LizsDing** [NaiboWang/EasySpider#102]
你好！我在爬https://www.freelancer.com/jobs/logo-design 这一页上的链接信息的时候，无法循环翻页，报错信息如下：
"Cannot find element://*[@id="pagination-390"]/li[6]/a[1], please try to set the wait time before executing this operation"
在点击下一页操作之前的循环已经设置了5秒等待时间。
我认为可能的原因（不一定对，还请大神指教）：freelancer 网站上的翻页按钮一直是第6个按钮没错，但是pagination-**390**这个数字390似乎是动态的，每次重新打开页面后数字都不一样，请问这种情况应该如何设置？谢谢！

**Comment by LizsDing** [comment]
任务在纯净版内保存为 “Hire Freelancers & Find Freelance Jobs Online | Freelancer-part 1 - get url”

**Comment by NaiboWang** [comment]
请看issues置顶说明：
https://github.com/NaiboWang/EasySpider/issues/100
Issues是来提软件的bug和功能需求之类问题的，对于如何使用软件设计一个任务的类似的问题，比如如何设置xpath，如何针对某网站设计一个流程等不属于软件的Bug和功能上的问题，我这边没时间一一解答，请大家理解。对于此类问题，大家可以加Readme里写的QQ群问其他朋友。

**Comment by NaiboWang** [comment]
算了，这次就帮你一下，以后这种问题请QQ群问其他朋友，你可以这样写XPath：

```xpath
//li[@data-link='next_page']/a
```

这个表达式表示：查找一个`li`元素，其`data-link`属性的值为`next_page`，然后选择这个`li`元素的子元素`a`。

你也可以直接通过`a`元素上的`data-pagination-next-button`属性定位：

```xpath
//a[@data-pagination-next-button]
```

这个表达式表示：查找一个`a`元素，其`data-pagination-next-button`属性存在。

在使用XPath时，要注意的是选择合适的属性以使定位尽可能精确，避免选中不需要的元素。

**Comment by LizsDing** [comment]
啊。。不好意思，我没有注意到有这个qq群，我明天来加。以后类似的问题我在群里问。
感谢Naibo校友（ZJUer) ! 我尝试了改了Xpath之后可以翻页了！

**Comment by NaiboWang** [comment]
好，不客气~
