### ISSUE TITLE
输出数据相关建议

### ISSUE THREAD

**Issue by zjl9959** [NaiboWang/EasySpider#103]
感谢作者开源的这款软件，用起来非常方便，不过关于输出的数据文件有一些小小的建议，如下：
1. 建议将同一个模板对应任务输出的数据归类到以模板命名的文件夹内（或者是支持自定义输出数据所在的文件夹），以便分析数据。
2. 建议将时间日期作为输出数据文件名的后缀，而不是随机的数字，以便查找。

**Comment by NaiboWang** [comment]
非常好的两个建议，下个版本会采纳。
