### ISSUE TITLE
将来是否支持导入数据库功能？

### ISSUE THREAD

**Issue by Shiweijunhf** [NaiboWang/EasySpider#104]
首先感谢开发者提供的这个软件，的确很容易上手。
其次是我的建议：现在提取的数据只有csv一种保存方式，是否可以增加更多的保存方式呢？比如增加对数据库(access\mysql\oracle等)的支持。
很多信息是有时间连贯性的，比如某个商品的价格/销量之类，使用数据库更方便整理、查询。再者数据库上对信息的分析会更自动化。

**Comment by NaiboWang** [comment]
好的，下下个版本会考虑支持，谢谢建议！

**Comment by NaiboWang** [comment]
导入MySQL数据库功能的版本已发布，欢迎使用。

**Comment by jipengkun** [comment]
太好了你太棒了
