### ISSUE TITLE
无法执行滚动操作

### ISSUE THREAD

**Issue by Tonystark64** [NaiboWang/EasySpider#105]
在爬取https://lihkg.com过程中，左侧的帖子在设置滚动和不设置滚动，采集到的数据量相当。
但手工用鼠标往下滚动时，数据量会增大很多。
“滚动到底部”和“向下滚动一屏”都试过。这个网页不是翻页，而是鼠标往下滚，然后加载更多数据这种。

**Comment by Flywolfs** [comment]
同样遇到这个问题，无法使用“滚动到底部”进行新的内容获取，请问作者有没有相关滚动功能的documentation？

**Comment by NaiboWang** [comment]
> 在爬取[https://lihkg.com过程中，左侧的帖子在设置滚动和不设置滚动，采集到的数据量相当。](https://lihkg.com%E8%BF%87%E7%A8%8B%E4%B8%AD%EF%BC%8C%E5%B7%A6%E4%BE%A7%E7%9A%84%E5%B8%96%E5%AD%90%E5%9C%A8%E8%AE%BE%E7%BD%AE%E6%BB%9A%E5%8A%A8%E5%92%8C%E4%B8%8D%E8%AE%BE%E7%BD%AE%E6%BB%9A%E5%8A%A8%EF%BC%8C%E9%87%87%E9%9B%86%E5%88%B0%E7%9A%84%E6%95%B0%E6%8D%AE%E9%87%8F%E7%9B%B8%E5%BD%93%E3%80%82) 但手工用鼠标往下滚动时，数据量会增大很多。 “滚动到底部”和“向下滚动一屏”都试过。这个网页不是翻页，而是鼠标往下滚，然后加载更多数据这种。

向下滚动是按下键盘的End键执行的，你这个页面是有两个分开的滚动栏，想要滚动哪个，先设置点击一下对应栏里的元素使该栏获得焦点，然后在点击元素的选项中设置向下滚动即可：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/966e659d-4138-4c0a-a78f-ed50458c39e6)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/53785a61-6ea7-43ea-ab6b-0c02bb9ba2ee)
