### ISSUE TITLE
点击一个a标签的链接，有时候会提示获取失败，请稍后尝试

### ISSUE THREAD

**Issue by dongchangjiangg** [NaiboWang/EasySpider#107]
在一个a标签的按钮上绑定点击元素操作，设置为打开此链接，配置任务没有问题，在爬取数据的时候，此操作，报错提示获取失败，请稍后尝试

**Comment by NaiboWang** [comment]
问题过于模糊，但基于”有时候“会提示获取失败，请观察提示的时候元素是否已经加载出来，多设置页面和操作后等待时间等元素加载出来再点击。

**Comment by dongchangjiangg** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NaiboWang/EasySpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 晚上8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NaiboWang/EasySpider] 点击一个a标签的链接，有时候会提示获取失败，请稍后尝试 (Issue #107)





 
问题过于模糊，但基于”有时候“会提示获取失败，请观察提示的时候元素是否已经加载出来，多设置页面和操作后等待时间等元素加载出来再点击。
