### ISSUE TITLE
感谢b站的网页滚动视频指导!但按照指导操作后日志如下:

### ISSUE THREAD

**Issue by Tonystark64** [NaiboWang/EasySpider#109]
#105   
感谢大神这么快回复并且在b站录了指导视频，这边按视频指导进行相同操作后暂未看到对应的效果。  
不知是否软件版本或是其他问题, 使用的版本下载链接和日志在下方。    
辛苦大神了！   
[b站视频指导](https://www.bilibili.com/video/BV1G14y1o7Qa/?vd_source=06eacb9ac6aa7e1a020a34679611fed5)  
[使用版本version 0.3.2](https://github.com/NaiboWang/EasySpider/releases/tag/v0.3.2)  

Configurations:
+------------------+------+-----------------------+
|       Key        | Type | Value                 |
+------------------+------+-----------------------+
|        id        | list | [8]                   |
| saved_file_name  | str  |                       |
|    user_data     | bool | False                 |
|  config_folder   | str  |                       |
| config_file_name | str  | config.json           |
|    read_type     | str  | remote                |
|     headless     | bool | False                 |
|  server_address  | str  | http://localhost:8074 |
|     version      | str  | 0.3.2                 |
+------------------+------+-----------------------+

win32 ('64bit', 'WindowsPE')
Finding chromedriver in EasySpider D:\22_23Term2\IEMS5930\ART350\EasySpider_windows_x64/EasySpider
Chrome location: D:\22_23Term2\IEMS5930\ART350\EasySpider_windows_x64\EasySpider/resources/app/chrome_win64/chrome.exe
Chromedriver location: D:\22_23Term2\IEMS5930\ART350\EasySpider_windows_x64\EasySpider/resources/app/chrome_win64/chromedriver_win64.exe
<selenium.webdriver.chrome.options.Options object at 0x0000023AC4301D50>
easyspider_executestage.py:1126: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
easyspider_executestage.py:1126: DeprecationWarning: use options instead of chrome_options

DevTools listening on ws://127.0.0.1:63176/devtools/browser/ec348745-7a31-4c2a-9d43-3a8bd30c030e
Loading stealth.min.js
id:  8
Save Name for task id 8 is: task_8_504345246
任务id 8 的保存文件名为: task_8_504345246
remote
Task Name: bbs
任务名称: bbs
Thread with task id:  8  is created
[16600:20188:0705/131124.108:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[16600:20188:0705/131126.042:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

Done!
执行完成！

**Comment by NaiboWang** [comment]
给我发封邮件：naibowang@foxmail.com，我把任务文件发你，你直接去看怎么实现的。
