### ISSUE TITLE
似乎有些元素右键选择不了

### ISSUE THREAD

**Issue by EugeneAeolus** [NaiboWang/EasySpider#113]
http://hrm.zju.edu.cn/
人力资源服务与管理系统这块，公开公示的链接点了右键没有任何反应，选择特殊点选模式也无反应。
![image](https://github.com/NaiboWang/EasySpider/assets/92861259/892584a0-ec02-4f1c-9991-195832085dbe)
左键进入后操作提示框直接消失。
![image](https://github.com/NaiboWang/EasySpider/assets/92861259/f3852d2e-965c-41c8-8081-f0c883babf73)

**Comment by NaiboWang** [comment]
暂时关闭，如果想回复请重新打开此Issue。
