### ISSUE TITLE
关于iframe的采集问题

### ISSUE THREAD

**Issue by xpkyy** [NaiboWang/EasySpider#114]
作者您好，我是一个新手，目前用EasySpider可以爬取大部分的基础内容，能节约不少时间，必须先感谢您的无私奉献！
现在遇到一个网站的数据无法采集的问题，具体情况如下：
某个付费资源网，其网址为S，登录之后点击页面中的资源目录链接，会在页面中打开一个嵌套的iframe页面，
里面是已付费的资源，手动是可以复制的，但是EasySpider无法识别到其中的任何内容，弹出一个提示说：
发现资源在iframe中，获取内容需要用以下网址N重新设计任务。尝试过用网址N单独访问，没有任何内容，
必须是在网址S打开的页面中点击资源目录链接打开嵌套的iframe页面才能返回资源内容，请问针对这种情况，
我目前用的0.3.2版本是否有什么解决的方法？

**Comment by NaiboWang** [comment]
0.3.2无法解决，0.3.5马上发布，到时候请使用新版本采集。

**Comment by xpkyy** [comment]
非常感谢~！
