### ISSUE TITLE
SSL错误

### ISSUE THREAD

**Issue by Lingtum** [NaiboWang/EasySpider#117]
开发大大，这个SSL错误可以被解决吗

![03ed573d449c7359ebcb702506a00c7](https://github.com/NaiboWang/EasySpider/assets/127567333/03a9970a-c026-401f-b980-e19f02615461)

**Comment by NaiboWang** [comment]
那暂时不会处理了，因为不影响使用，为了做到所有网页通用，这个需要保留。

**Comment by Lingtum** [comment]
嗦嘎，好的好的，辛苦开发大大了

**Comment by NaiboWang** [comment]
这个问题已经通过一些手段修复，可以重新下载版本使用。
