### ISSUE TITLE
一直重复Cloudflare检测

### ISSUE THREAD

**Issue by 425765923** [NaiboWang/EasySpider#118]
前置信息:
EasySpider 3.5版本
是否为Cloudflare等极端反爬网站：是

问题：
调试脚本总是循环Cloudflare检测，执行脚本过程中即使手动勾选，也没有效果，只有第一次运行可能是可以通过的
网址：https://portal.ustraveldocs.com/scheduleappointment

现象
![c](https://github.com/NaiboWang/EasySpider/assets/27410042/1bb44c08-6175-493b-ae85-5e8f7e4d0042)

期望
最好可以自动绕开cloudflare检测，或者和自己浏览器打开一样，偶尔才触发检测

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。

**Comment by NaiboWang** [comment]
这个地方确实有些Bug，正在紧急修复中，修复完成会回复，默认就支持自带用户目录功能。

**Comment by NaiboWang** [comment]
已修复问题，并已经更新到Github，重新下载即可。
