### ISSUE TITLE
Cloudflare模式如何保存用户信息（token）

### ISSUE THREAD

**Issue by 425765923** [NaiboWang/EasySpider#119]
前置信息:
EasySpider 3.5版本
是否为Cloudflare等极端反爬网站：是

问题：
在Cloudflare模式下登陆了网址后（https://portal.ustraveldocs.com），下一次还需要访问网址还需要登陆，请问Cloudflare模式下是如何保存用户数据避免总是重复登陆

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。
