### ISSUE TITLE
这个是否会容易被反爬虫站点检测

### ISSUE THREAD

**Issue by YeeKangShao** [NaiboWang/EasySpider#120]
我是一名专利代理师。工作需求，需要导出很多企业的专利数据，现有的专利数据运营站点收费过高，不适用于个人，而且数据更新还不及时，导致不同的网站搜的结果可能还不同。
最好的办法是去国知局站点（https://www.cnipa.gov.cn/）爬取，但是我在写任务的时候，打开这个站点就一直是空白的，然后用软件自带的浏览器打开其他站点又是正常的。是否是这个站点具备反爬虫技术？

易采集能否解决这个问题呢

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。

**Comment by YeeKangShao** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
