### ISSUE TITLE
English version of your software and tutorials? Not able to launch application.

### ISSUE THREAD

**Issue by Koladweep** [NaiboWang/EasySpider#125]
Is there an English version of your tutorials?
I had problem getting started since the application didn't even launch in windows x64. I'm having trouble finding proper documentation in English. could you help me out? I didn't see any log of windows defender having blocked it. I explicitly allowed it to run by bypassing the windows smartscreen.

**Comment by NaiboWang** [comment]
Hi, here is the document for English: https://github.com/NaiboWang/EasySpider/wiki

Scroll down to the bottom to see English, also here are all documentation of English:

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/244716f9-53a8-4dbd-9d45-86c76cbc8f54)


Youtube Video Tutorial: https://youtube.com/playlist?list=PL0kEFEkWrT7mt9MUlEBV2DTo1QsaanUTp

Please make sure you download the software via Github Releases: https://github.com/NaiboWang/EasySpider/releases
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/13245419-1ce6-4fb2-a4b4-90e55aefeca8)

**Comment by Koladweep** [comment]
Thanks Mr. Wang. I was # excited when I came across your actively maintained repo. To start is easy, but to continue the effort requires dedication.
