### ISSUE TITLE
忽略自签发证书错误

### ISSUE THREAD

**Issue by lxcau** [NaiboWang/EasySpider#126]
在爬取自签发证书网页时，chrome会因为证书错误停止加载网页，影响程序继续运行
建议在slenium调用chrome时增加参数options.add_argument('--ignore-certificate-errors')，并在GUI界面的打开网页证书部分增加一个“忽略证书错误“选项

**Comment by NaiboWang** [comment]
已解决，请等待下个版本发布或下载最新源码自行编译。
