### ISSUE TITLE
等待元素加载完成

### ISSUE THREAD

**Issue by lxcau** [NaiboWang/EasySpider#127]
在网页加载非常慢的情况下，可能会导致程序找不到对应XPATH而报错，建议像automa一样设置一个”等待选择器“并设置超时，这样比在上一个流程直接设置执行完等待固定时间更加合理
<img width="185" alt="屏幕截图 2023-07-15 230650" src="https://github.com/NaiboWang/EasySpider/assets/18585803/9405451d-c182-4b9b-95ac-122d28e12007">

**Comment by NaiboWang** [comment]
已解决，请等待下个版本发布或下载最新源码自行编译。

**Comment by lxcau** [comment]
高效🫰
