### ISSUE TITLE
链接下载不下来

### ISSUE THREAD

**Issue by 12138LMK** [NaiboWang/EasySpider#128]
链接下载不下来，报链接地址 对应XPath  未找到的错
但获取文本和链接时显示成功了
![image](https://github.com/NaiboWang/EasySpider/assets/139939005/29e30658-858a-4d71-b820-5ff39a6c2b2a)
就是执行的时候，只能下载下来文本，我看视频并没有重新获取链接的xpath
不知道什么原因

**Comment by NaiboWang** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/e178f573-5f87-4d64-9905-947b35030b2c)
这是个Bug，已经修复，可以等待下个版本，对于当前版本，处理方式为展开高级操作，JS脚本输入1再执行任务。

**Comment by 12138LMK** [comment]
好的，感谢，已成功
