### ISSUE TITLE
爬取链接里的文字内容时，会限制爬取链接数量吗

### ISSUE THREAD

**Issue by 12138LMK** [NaiboWang/EasySpider#132]
![image](https://github.com/NaiboWang/EasySpider/assets/139939005/ddec60fc-0b0b-49f4-969f-28d575169f13)
最近试了下发现这里的链接数量最多只能给675条，多了的话，后面的链接就开始非常不稳定，访问不到网页。
所以想问下是软件问题还是爬取网页（https://www.cls.cn/depth?id=1000）的反爬限制

**Comment by NaiboWang** [comment]
肯定不是软件问题，软件不会设置675这种数字，是网站反爬的问题，请尝试使用代理，或等一段时间再去爬取。

**Comment by 12138LMK** [comment]
好的，了解
