### ISSUE TITLE
"network_change_notifier_win " 抓取中出现报错

### ISSUE THREAD

**Issue by wanggegedouble** [NaiboWang/EasySpider#133]
![image](https://github.com/NaiboWang/EasySpider/assets/86892036/40ca76ad-b6ce-4ed8-8e87-c798089ffcfc)

**Comment by NaiboWang** [comment]
这个看上去是你的网络问题，有没有尝试过重新执行？

**Comment by wanggegedouble** [comment]
执行过两次，第一次晚上我把程序开启，然后就没管了。第二次是白天我重新执行了一次，还是会这样。网络也没有中断过。

**Comment by NaiboWang** [comment]
是不是在vpn或者内网环境下执行的程序，这个问题网上所有的解决方案都是检查网络环境重试，我这里无法复现此问题，没有办法直接处理。

**Comment by wanggegedouble** [comment]
哦哦，可能是开了vpn。这个我没注意。我重新在执行一次。
