### ISSUE TITLE
How to use regular expressions?

### ISSUE THREAD

**Issue by bizkit00** [NaiboWang/EasySpider#134]

**Comment by NaiboWang** [comment]
You can use regular expressions when you set the data extract type as JavaScript:

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/c858de50-0891-4db1-a9fb-a26301572289)

E.g., 

```JavaScript
var myString = arguments[0].innerText;
var regex = /pattern/ig;
var result = myString.match(regex);
return result;
```
