### ISSUE TITLE
您好，报错：找不到要循环的单个元素。请问如何解决？

### ISSUE THREAD

**Issue by peisong0109** [NaiboWang/EasySpider#135]
检测到页面变化，继续循环。
Page changed detected, continue loop.
Single loop element not found:  //*[contains(@class, "layui-laypage-next")]/i[1]
找不到要循环的单个元素:  //*[contains(@class, "layui-laypage-next")]/i[1]
Loop element not found:  /html/body/div[3]/div[1]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr
找不到循环元素:  /html/body/div[3]/div[1]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr
Done!
执行完成！

**Comment by NaiboWang** [comment]
你这个xpath本身写法就是错的，至少应该是`//*[contains(@class, "layui-laypage-next")]/i[1]`

建议用自带的XPath Helper去调试XPath，默认生成的xpath一般只能保证设计时的页面有效，更换页面后结构可能会变化因此需要更改XPath到一个更通用的XPath。
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/0250129f-c713-49b1-8ebd-8ce1e4c59371)

如需要更多帮助，请加Readme里写的QQ群问群友。

**Comment by peisong0109** [comment]
谢谢您的建议。这个xpath是根据教程操作并自动生成的，在xpath helper中测试也是正常的。

**Comment by peisong0109** [comment]
非常感谢，问题已解决。原因是页面加载时间过长。

非常感谢您的帮助。
