### ISSUE TITLE
获取超链接失败

### ISSUE THREAD

**Issue by yolandalyl** [NaiboWang/EasySpider#141]
点击了所有同类元素共20个，想采集超链接，选择采集数据后，出来的列表数据不全，且链接处是javascript:void(0);

![image](https://github.com/NaiboWang/EasySpider/assets/140702985/1d9c5715-2d45-4c1c-a15b-c45c5b8900ce)

**Comment by NaiboWang** [comment]
链接处是`javascript:void(0);`说明网页做了处理不能直接提取超链接值，建议使用`循环点击每个链接`来提取数据。

**Comment by yolandalyl** [comment]
谢谢大佬！还有一个问题是：右键选择标题，总是不出现超链接还怎么办呀。也是循环点击链接提取吗

**Comment by NaiboWang** [comment]
试着右下角扩大选区，如果不出现说明网页不是超链接驱动的，需要循环点击来提取。

**Comment by yolandalyl** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/140702985/c47b86d7-f9b2-4595-815a-8cd436e63d2a)
zhe这里不太清楚该怎么设置

**Comment by NaiboWang** [comment]
这里是新增字段，需要对工具掌握熟练才能使用，如果实在搞不定，可以加Readme里提到的QQ群问群友去交流。

**Comment by yolandalyl** [comment]
好的 感谢）
