### ISSUE TITLE
识别不到下一页

### ISSUE THREAD

**Issue by yolandalyl** [NaiboWang/EasySpider#143]
重写了几个Xpath都识别不到下一页按钮：”/html/body/div[4]/div[1]/div[1]/div[1]/div[1]/nav[1]/ul[1]/li[last()]/a[1]“ ”//a[contains(., '下一页')]“。但用Xpath Help都能识别到，每一页都能，但采集时不能识别

**Comment by NaiboWang** [comment]
采集的时候长按p键暂停，然后打开执行阶段的xpath helper调试xpath看能不能定位到元素，如果可以，尝试把元素点击类型从selenium点击改为JavaScript点击后重试。

**Comment by yolandalyl** [comment]
感谢回复！重新执行了两次不知道为什么又成功了hh

**Comment by NaiboWang** [comment]
那大概就是因为你留的等待页面加载时间不够，导致执行的时候元素还没有加载出来。
