### ISSUE TITLE
0.3.5版本，debug发现“提取数据”节点，js代码没有执行。

### ISSUE THREAD

**Issue by ITKing80** [NaiboWang/EasySpider#150]
设置 提取数据 节点的采集内容类型为：（针对该元素的）javascript代码返回值（需以return开头）
该类型的key是"JS"，没有被执行。

跟踪代码发现：
有执行前置js
                    self.execute_code(
                        2, p["beforeJS"], p["beforeJSWaitTime"], element, iframe=p["iframe"])  # 执行前置js

有执行后置js
                    self.execute_code(
                        2, p["beforeJS"], p["beforeJSWaitTime"], element, iframe=p["iframe"])  # 执行前置js

**Comment by NaiboWang** [comment]
如果没有写JS确实不会执行，写了就会执行了，再去试试。

**Comment by NaiboWang** [comment]
提取内容类型是“基于本元素的JavaScript代码返回值”吗？

**Comment by ITKing80** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/18067182/e9da96b7-d24c-4079-830b-6c3bf0cde359)

**Comment by NaiboWang** [comment]
JS写错了，Field[]前后应该加单引号，Field里面应该是双引号：

`return document.evaluate("//tbody/tr[contains(., 'Field["受理号"]')]/td[7]", document).iterateNext().innerText`

调试的时候，理论上的执行路径：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/013e1778-6340-4de6-b5cf-3d7702a1aa87)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/5e5e1b5f-e899-4bce-b6fc-c02613bd657e)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/3a6c24ba-2cbb-45b7-9ca9-6e542c2d5b9c)

**Comment by ITKing80** [comment]
> ![image](https://user-images.githubusercontent.com/18067182/257839578-e9da96b7-d24c-4079-830b-6c3bf0cde359.png)

没有写错，是拷贝错了，之前写错的，后面改了，json文件里是把不要的节点的id设置成-1，所以看错了，拷贝错了。
按你的截图，我明天再研究一下，谢谢。
