### ISSUE TITLE
边滚动边进入链接采集数据

### ISSUE THREAD

**Issue by yolandalyl** [NaiboWang/EasySpider#151]
请问有办法实现边滚动边进入链接采集数据吗
现在使用的Xpath是可以识别滚动后加载出来的标题连链接的
但是不知道该怎么采集完部分数据后，向下滚动然后继续识别

**Comment by NaiboWang** [comment]
循环操作，打开网页操作和点击元素操作都有向下滚动操作，请尝试在相关位置设置滚动以适用于自己的场景。

**Comment by mjy23** [comment]
滚动后想再循环上一步采取数据的操作时，好像已经无法识别了，这是为什么呢？

**Comment by Gotodie** [comment]
> 滚动后想再循环上一步采取数据的操作时，好像已经无法识别了，这是为什么呢？

请问解决了吗？我也有这个问题
