### ISSUE TITLE
抓取多页表格数据时，有些页面获取的表格的数据是完整的，有的又不完整是什么原因呢？

### ISSUE THREAD

**Issue by Yongliao666** [NaiboWang/EasySpider#152]
[](url)

**Comment by NaiboWang** [comment]
问题太模糊，但大概率是同样的XPath在不同的页面会提取到不同的数据，有的页面会匹配到完整数据，有的不够完整。因此要修改XPath来适应，使得同一个XPath可以提取到不同页面的所有数据。

**Comment by Yongliao666** [comment]
谢谢您的回复，我在试一下。

发自我的 iPhone

在 2023年8月3日，下午2:10，Naibo Wang ***@***.***> 写道：

﻿

问题太模糊，但大概率是同样的XPath在不同的页面会提取到不同的数据，有的页面会匹配到完整数据，有的不够完整。因此要修改XPath来适应，使得同一个XPath可以提取到不同页面的所有数据。

**Comment by NaiboWang** [comment]
Excel单个表格最大长度为15000汉字，是否超过了此限制？如果超过，保存格式转换为csv或者txt。
