### ISSUE TITLE
Linux下的安装问题

### ISSUE THREAD

**Issue by 1466898646** [NaiboWang/EasySpider#154]
我在Linux下按照步骤进行了编译，在执行文件夹中遇到了这个问题
![捕获](https://github.com/NaiboWang/EasySpider/assets/93703772/afa51dcb-7120-40d8-987e-1123b99c9c03)

**Comment by NaiboWang** [comment]
关键问题是你没有安装pyinstaller，需要先`pip3 install -r requirements.txt`，其他问题可以忽略。

**Comment by Gzj369** [comment]
@1466898646 请问linux centos环境下，按什么步骤进行编译呢
