### ISSUE TITLE
打开globalsources网站，被拒绝访问，ERROR15

### ISSUE THREAD

**Issue by KDora22** [NaiboWang/EasySpider#155]
https://www.globalsources.com/
打开这个网站被拒绝访问如图
![QQ截图20230804164007](https://github.com/NaiboWang/EasySpider/assets/103802740/1d84c86b-7bbe-445d-8b17-45619aca2ade)

**Comment by NaiboWang** [comment]
可能与你网络环境有关系，和软件无关：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/e7ceb8c2-f3c2-4440-8b25-812dbe165aad)

**Comment by KDora22** [comment]
> 可能与你网络环境有关系，和软件无关： ![image](https://user-images.githubusercontent.com/30287768/258393413-e7ceb8c2-f3c2-4440-8b25-812dbe165aad.png)

但我正常使用浏览器能打开这个网站，只有使用Easay Spider打开这个网站时才会出现无法访问的情况，即使更换了网络也是一样的情况

**Comment by NaiboWang** [comment]
换台电脑试一试。？因为我无法复现你的问题，所以也不知道该怎么处理。
