### ISSUE TITLE
多内容查询循环输入

### ISSUE THREAD

**Issue by jiehuiDT** [NaiboWang/EasySpider#161]
大佬，请问下，需要大量循环输入查询，输入的内容需要自动从csv，或者数据库查询得到。
这个该怎么实现。教程第一个视频是手动输入查询的内容，有没有地方可以配置自动查询获取到的内容

**Comment by NaiboWang** [comment]
用0.5.0版本，保存任务的时候指定Excel文件：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/979d83b7-67be-4017-b895-0794ed96f04b)


Excel文件格式设置如下：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/22014d90-7e77-478d-9493-c958920214a3)
