### ISSUE TITLE
如何在打开网页后提取cookie数据到excel

### ISSUE THREAD

**Issue by heurainbow** [NaiboWang/EasySpider#165]
希望通过批量注册账号，获取批量登录cookie后导出，该如何实现

**Comment by NaiboWang** [comment]
程序目前还不支持导出cookie，只支持导入，将来有很多类似需求后会考虑开发。

**Comment by heurainbow** [comment]
已经尝试发现0.5支持的python eval模式可以通过self.browser.get_cookies() 可以提取到。可以将selenium替换成seleniumwire进一步获取header信息。
