### ISSUE TITLE
循环点击页面每个链接不回退

### ISSUE THREAD

**Issue by daily-learn** [NaiboWang/EasySpider#167]
1.爬取公网网址为:https://inform.tmforum.org/research-and-analysis/reports
2.网页内的检索关键词为:autonomous networks
3.目的:点击进入每个图片所代表的文章链接,然后复制文章的网页,一个简单的任务,为了测试翻页是否正常.
4.操作过程:
               首先正常设置检索输入操作,进入搜索结果页面,然后右键点击下一页按钮,选择循环点击该元素;
                然后右键选中第一张图,选择选中全部,选择循环点击每个元素.
                然后进入正文页面,选择操作框中的采集当前页面的网址.
                然后保存,执行.
5.任务执行结果:第一页每个元素可以正常点击,第二页可以点进去第一个元素,然后就卡在当前页面,不回退,一直卡在那里.
6.特别说明:
为了保证不是采集选择对象的问题,试过只做"点击元素"的操作,但是执行结果仍然是卡在当前页面.
为了保证不是采集的网页的问题,换了检索词,检索到不同的网页,同样的操作,结果仍然是卡在当前页面.
任务设计:
![image](https://github.com/NaiboWang/EasySpider/assets/80041121/795f898c-b928-42fe-943f-bcdca63259bb)
版本号:0.3.5
操作系统:类centos系统(Red Hat)系列
7.最后
如果您能在百忙之中抽空看看这个问题，不胜感激。

**Comment by daily-learn** [comment]
补充说明，目的是为了点进去文章，保存该网页的连接。（本来是想直接复制文章内容保存，但是看了bilibili教学是要先爬取网页连接，然后再分开爬取图片和文字，就打算先保存连接），为了保证操作的正确性，也学习了基础的教学视频。主要是操作非常简单，按理来说不应该出现问题的。因为任务需求也简单。相对复杂的翻页也按着教程走的。

**Comment by NaiboWang** [comment]
这个页面属于下面视频的场景：
https://www.bilibili.com/video/BV11W4y1D71t/

**Comment by daily-learn** [comment]
感谢您的回复,我今天反复观看学习您的视频并操作了数十次,完全按照您的操作流程走.但是

1.发现:
第一页可以正常循环访问每个文章链接,但是最外部的大的翻页循环(即我有14页,设置了return v_page<=14作为翻页条件)它只在最开始的时候进入了一次,访问完第一页元素之后就再也无法再次进入翻页循环,页面永远不会点击下一页。运行结果可能是卡在第一页了.
要么就是自己会去点不该点的东西，然后最后进入一个空白页面（在设置了翻页功能后,就会乱点到一些错误的元素导致页面错误跳转）。

2.补充说明：为什么我知道第一次可以进入循环呢,因为我修改了翻页逻辑(t_page< v_ page我修改为了t_page<=v_page),第一次进入循环后就成功翻页,当然这是一种测试方式,不是我想要的.


3.猜想:
3.1.是否和版本有关(我的是0.3.5),
3.2.是否和网页的非标准化有关(即页面存在除了翻页之外的其他反人类设计,在本程序的兼容范围之外).
3.3.是否和页面的滚动的加载有关,我尝试设置页面滚动保证页面在访问了第一页所有元素后,通过页面滚动到末尾来保证显示下一页图标,但是很遗憾这种设置不起作用.
3.4 通过我多次尝试，我发现，第一页的文章的连接和第二页的文章的连接有些不同。按理说，设置循环点击，不论当前是那一页，设置的循环点击会对每一页生效。但我实测，对第二页设置的循环点击，就只对第二页的元素生效。同样，由于之前是在第一页点选的元素，可能就导致只有第一页可以点击。
3.5 是我选取的元素错误。我选取的文章xpath是：
/html/body/div[2]/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div/a[1]/div[1]/div[1]/div[1]/img[1]（通过插件可以定位该元素）
我选取的下一页按钮xpath是：
//*[contains(@class, "mdi-chevron-right")]
通过插件可以定位到该元素。
![image](https://github.com/NaiboWang/EasySpider/assets/80041121/ece70efb-6fd7-42e1-9cf0-9f880449b0b7)
![image](https://github.com/NaiboWang/EasySpider/assets/80041121/be476e03-9d6d-4206-834c-493287df13f1)

4.一点困惑：实在想不通为什么同样的操作，会有这么大差异，因为您的操作讲解确实简洁明了容易懂。我也是懂c++和java的，按理不应该是操作层面的问题。

非常希望能获得您的回复，谢谢。

**Comment by NaiboWang** [comment]
由于每个网站的设计都不同，因此部分网站可能存在需要设计十分复杂技巧的问题。
针对你说的这种情况，我最近比较忙没时间帮忙测试此网站，因此最好的方式为你下载源码，自行配置环境后通过断点调试的方式探究问题所在。

`ExecuteStage`文件夹内的程序即为执行阶段程序，调试所用的配置文件在`.vscode`文件夹内，只需要将ID换成自己的任务ID即可。

如果调试后发现了问题所在，也欢迎继续留言以便将来更新此工具。

**Comment by daily-learn** [comment]
您说的很对,您在该视频结尾已经教了我们调试方法,感谢您的用心工作.今天我将切换到一个支持源码调试的适配系统,尝试调试工作.
