### ISSUE TITLE
win10按照编译说说明编译ElectronJs后要设计任务打不开chrome浏览器,显示缺少了EasySpider_zh.crx

### ISSUE THREAD

**Issue by daily-learn** [NaiboWang/EasySpider#168]
补充一个问题的解决方法:
问题,源码执行设计任务时报错找不到文件:
![image](https://github.com/NaiboWang/EasySpider/assets/80041121/9badacd7-e460-444c-99c6-5340a511417d)

*打算设计任务时,程序的chrome无法弹出,界面有一个一闪而过的东西(可以理解为chrome闪退吧),
然后命令行显示如上,看得懂的错误是说缺少了文件EasySpider_zh.crx,

然后我下载了最新的发行版本0.5.0,在EasySpider_0.5.0_windows_x64_Beta\EasySpider_windows_x64\EasySpider\resources\app里面找到了它还有EasySpider_en.crx,然后执行成功

**Comment by NaiboWang** [comment]
先完成浏览器扩展部分的编译，即可生成两个`.crx`扩展文件。
