### ISSUE TITLE
关于页面存在pdf下载链接,点击跳出pdf预览器,该如何采集

### ISSUE THREAD

**Issue by daily-learn** [NaiboWang/EasySpider#169]
在有些页面,它提供pdf下载,但是必须先显示一个内容的预览,然后在右上角有下载pdf和打印pdf选项.
1.目标
ieee网页:https://grouper.ieee.org/groups/802/1/files/public/
  采集对象:里面子文件中的pdf的文件或者pdf里的内容
   我想采集内容或者点击下载按钮

2.出现的问题:
就像不能操作程序去点击浏览器的关闭按钮(那个x按钮)一样,它无法识别到页面上的任何内容.
如下是类似的预览页面(来自知乎):
![image](https://github.com/NaiboWang/EasySpider/assets/80041121/55dd0971-164e-4191-a01f-c48e763aa4e6)
如果要去点浏览器自身的那种按钮(比如pdf预览页面的下载pdf),
![image](https://github.com/NaiboWang/EasySpider/assets/80041121/92d5c736-1a4e-42a9-99f0-ede6d011d68c)

3.我的疑问
请问有没有方法实现,如果有,我应该朝什么方向努力,麻烦您指点,感谢.

**Comment by NaiboWang** [comment]
正常流程设计点击PDF链接，执行阶段即可自动下载PDF，无需额外设置。

**Comment by daily-learn** [comment]
好的,实现了,谢谢您的回复

**Comment by SAKURA-LBY** [comment]
具体怎么弄啊？能分享下设计吗？
