### ISSUE TITLE
关于提取多个参数的问题

### ISSUE THREAD

**Issue by ZeroCandyCY** [NaiboWang/EasySpider#174]
你好，请问下，我需要提取3个参数，第一次提取2个，第二次提取1个。这个三个参数的值有关联，需要放在一行。
![微信图片_20230828155036](https://github.com/NaiboWang/EasySpider/assets/52985091/5ab93d77-9e16-4ca8-beeb-0386199f5ad6)
我这么提取，会每条数据提取两次，请问该怎么处理？

**Comment by NaiboWang** [comment]
目前版本只能做到提取两次，将来版本会支持你提到的需求，请关注Releases页面更新说明。
