### ISSUE TITLE
如何在设计流程中预先自动执行先前流程，方便我继续进行设计

### ISSUE THREAD

**Issue by ellieot** [NaiboWang/EasySpider#175]
比如我现在需要设计一个任务，我做了一半想看看稳定性，于是我退出设计，来到执行页，然后执行完毕，再来到设计页开发。
此时我发现设计页是从头开始的，我如何让它自动执行到后面的状态

**Comment by NaiboWang** [comment]
只能在重新设计任务时按照步骤一步一步的重新设计然后在浏览器跳转到你自己想要设计的步骤页的位置，因为网页操作是有先后顺序的，具体逻辑取决于网站的后台，不取决于EasySpider。

**Comment by ellieot** [comment]
我的意思是，我想让easySpider在开发的时候能帮我自动填充用户名和点击登录等等的操作，直接到达我需要继续开发的那个位置。
现在我只要出去调试再回来开发，就需要手动输入表单，然后再做很多前期的手动点击工作，才能到达我想继续开发的位置，我感觉比较繁琐，想知道有什么能自动化执行先前步骤的解决办法

**Comment by NaiboWang** [comment]
目前版本不支持，将来有支持的打算，请关注Releases页面更新。
