### ISSUE TITLE
请问一下, 如何采集子页面的数据?

### ISSUE THREAD

**Issue by zxydream** [NaiboWang/EasySpider#176]
请问一下,如果需要的数据在子页面如何采集?
比如淘宝商品的规格颜色等数据,需要点到商品详情里面去,采集完数据然后返回列表,点击下一个商品详情采集数据,这样循环. 主要的操作是如何返回上一页.

**Comment by NaiboWang** [comment]
操作提示框中循环点击每个链接后进入子页面采集。
B站视频58同城那节有讲解。
