### ISSUE TITLE
设计窗口闪退

### ISSUE THREAD

**Issue by zxydream** [NaiboWang/EasySpider#177]
一开始用的挺好的,设计过几次之后再次点击设计的时候发现设计页面一闪而过, 就消失了, 浏览器页面打开了,也可以正常操作.
然后到修改任务流程时候,设计页面显示出来了,但是浏览器页面有没有打开.

**Comment by NaiboWang** [comment]
问题无法复现，建议关掉程序重启，或者重启电脑试试。
也许是杀毒软件阻止了程序启动。

**Comment by zxydream** [comment]
重启之后就好了
