### ISSUE TITLE
MacOS files for latest release

### ISSUE THREAD

**Issue by 1of13** [NaiboWang/EasySpider#179]
Where are the MacOS files for the latest release?

**Comment by NaiboWang** [comment]
Please see descriptions of the Releases page:
This version has only released the Windows x64 and x32 Beta versions, welcome to try it out and report any bugs as Issues in a timely manner. 

**The versions for other operating systems will be released after Bilibili changes the display of the number of video plays to the display of the total length of video plays.** 

Therefore, for the other operating system versions, please use version 0.3.5 for now.
