### ISSUE TITLE
按ebay示例程序执行第一次成功，第二次失败

### ISSUE THREAD

**Issue by gangan0** [NaiboWang/EasySpider#181]
用的是Mac电脑，按照ebay示例程序执行第一次能成功。但是第二次执行相同的任务，启动完Chrome浏览器，Chrome会自动关闭，终端里会报错
<img width="809" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/40681965/0de2ee3d-3d0c-4c50-8e42-9933ea160aa0">

**Comment by NaiboWang** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/c49787e3-184d-488a-8f40-7d6c27f99d06)
Chrome版本被MacOS系统自动更新了，解决办法为：

请自行到以下网址下载对应自己当前chrome版本的macOS版本的chromedriver：https://googlechromelabs.github.io/chrome-for-testing，并将chromedriver文件放在上面提到的Contents/Resources/app文件夹内，更名并替换掉“chromedriver_mac64”文件即可使软件恢复正常使用。

**Comment by gangan0** [comment]
解决了

> ![image](https://user-images.githubusercontent.com/30287768/265587340-c49787e3-184d-488a-8f40-7d6c27f99d06.png) Chrome版本被MacOS系统自动更新了，解决办法为：
> 
> 请自行到以下网址下载对应自己当前chrome版本的macOS版本的chromedriver：
> 
> https://googlechromelabs.github.io/chrome-for-testing
> 
> 并将chromedriver文件放在上面提到的Contents/Resources/app文件夹内，更名并替换掉“chromedriver_mac64”文件即可使软件恢复正常使用。

解决了
