### ISSUE TITLE
win11打开闪退

### ISSUE THREAD

**Issue by lyx102** [NaiboWang/EasySpider#184]
![Snipaste_2023-09-10_10-44-14](https://github.com/NaiboWang/EasySpider/assets/118903019/1b1394c7-3267-4217-9e20-2f02e6b306f8)
 到这个页面后，就闪退了

**Comment by NaiboWang** [comment]
问题无法复现，请尝试打开config.json文件，更改debug字段为true后重新打开程序。然后将info.log的信息贴在这里。
同时，尝试重启电脑试试，或重新下载打开。
尝试下载其他版本并打开。
