### ISSUE TITLE
执行例程任务报错了

### ISSUE THREAD

**Issue by fanleung** [NaiboWang/EasySpider#186]
win10，
chrome version: 116.0.5845.188

id:  9
remote
Task Name: 中国地震台网——历史查询
任务名称: 中国地震台网——历史查询

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
[1;32mpip index versions commandline_config
pip install commandline --upgrade[0m
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1949, in <module>
  File "myChrome.py", line 26, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 69, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 92, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 272, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 364, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 243, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF60A544A62+57106]
        (No symbol) [0x00007FF60A4BCF52]
        (No symbol) [0x00007FF60A38E2CB]
        (No symbol) [0x00007FF60A3B4C5B]
        (No symbol) [0x00007FF60A3B30AA]
        (No symbol) [0x00007FF60A3EE3F7]
        (No symbol) [0x00007FF60A3EDF60]
        (No symbol) [0x00007FF60A3E6793]
        (No symbol) [0x00007FF60A3BCE81]
        (No symbol) [0x00007FF60A3BE064]
        GetHandleVerifier [0x00007FF60A7F4222+2873042]
        GetHandleVerifier [0x00007FF60A846590+3209792]
        GetHandleVerifier [0x00007FF60A83F3AF+3180639]
        GetHandleVerifier [0x00007FF60A5D5F25+652245]
        (No symbol) [0x00007FF60A4C8618]
        (No symbol) [0x00007FF60A4C47C4]
        (No symbol) [0x00007FF60A4C48BC]
        (No symbol) [0x00007FF60A4B4C33]
        BaseThreadInitThunk [0x00007FF851A17034+20]
        RtlUserThreadStart [0x00007FF851C82651+33]

[7400] Failed to execute script 'easyspider_executestage' due to unhandled exception!

**Comment by NaiboWang** [comment]
Chrome 更新后需要同步更新chromedriver，请参考下面的问题将chromedriver_win64文件替换为116版本：

https://github.com/NaiboWang/EasySpider/issues/181

**Comment by fanleung** [comment]
已替换 
目前浏览器版本 117.0.5938.63
chrome 117.0.5938.62
但还是报一样的错误，无法执行
![image](https://github.com/NaiboWang/EasySpider/assets/15844433/fc17c693-8bb6-4370-8601-53c28b19167e)
![image](https://github.com/NaiboWang/EasySpider/assets/15844433/234977c0-1250-4ff0-96e5-0d9455dcee35)

**Comment by NaiboWang** [comment]
图中你的浏览器似乎还是115版本？  建议重新下载试一下。

另外就是示例任务可能已经过时，可以尝试自己设计一个简单任务试一试，这属于最基本的环境问题。
