### ISSUE TITLE
google图片爬取高清大图

### ISSUE THREAD

**Issue by ggkingdom** [NaiboWang/EasySpider#187]
https://lens.google.com/search?ep=gisbubb&hl=zh-CN&re=df&p=AbrfA8rthABrqWeeL93b5WWNFuVvPlKE9aZegDBqRM4aKnajuJ54jEf89gKS3NuIUhk86_8EiHbQyx_OBrXPrjL-NUwz_CvgfCFBwy0tAeg9s0ZdczmhCo9eg3g2mI-wr5Qv5p9oXY7KRh4GH8ffmBE7bYKcllfZNloWRYrwMRlTLP4irDWyWpcQSBRaMZw6LlTKGvd8vGnb3bPOhuvFbi9tIt3fAEIeT4IDIHz91c-v_QXfyn8Xt5TkCioNL5UyjzI59u5oOaXxuOH09nguh3RZ48X4EgnrP2JJ2k4Q#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKREkxWVdSak1qRmhMV0ZpTWpFdE5EVTJOeTA0TkdRNExXSTFNMlV3WWpKbFpXUmxZUklmU1Rkc1NEUlphVGRvYUVsVWMwWldkMUYzZG5veE4waFhObFpIWDNGQ1p3PT0iLG51bGwsbnVsbCxbW251bGwsbnVsbCwiMy03Il0sWyI5NTRhYmYyZS04Mzc3LTQ2MDktODdlOS0wNDQ5OWNmZjJiZTIiXV1d

**Comment by NaiboWang** [comment]
请明确问题，如果是想要问在google上爬取图片如何设计，这属于设计问题，建议跟随文档和视频自己选择。
如果是有什么软件Bug出现，请详细描述Bug的内容，截图。

**Comment by ggkingdom** [comment]
感谢作者回复。
已经看过下载图片的视频教程了"可视化爬虫易采集EasySpider: 实战采集汽车网文章内容并下载文章内图片"，以上issue中提及的页面，获取不到搜索结果的超链接，因此无法批量下载搜索出来的链接中的高清图片。
求助：用easyspider是否能批量下载google用图片搜索出来的链接中的高清图片。如果可以，通过什么方法呢，提供下思路即可，感谢。

**Comment by NaiboWang** [comment]
审查元素看看图片是什么形式，如果是图片就直接提取图片地址，如果是以css背景图片的方式出现，就提取背景图片地址。

**Comment by ggkingdom** [comment]
搜出来的网页样式各异，且只想要搜索结果中缩略图对应的那张原图，理论分析没法简单用这种自动化手段实现了，遗憾。

**Comment by NaiboWang** [comment]
嗯 可能需要上人工智能手段了。

**Comment by soaiyou** [comment]
使用dezoomify插件。
