### ISSUE TITLE
程序没有自动创建“打开网页”

### ISSUE THREAD

**Issue by joker1024567** [NaiboWang/EasySpider#188]
如图所示，默认的打开网页没有创建
我的版本为：v0.5.0和win10
![image](https://github.com/NaiboWang/EasySpider/assets/91998801/e960e097-317c-42e5-bacd-e8016d9832ab)
有可能是相关问题的错误截图
![image](https://github.com/NaiboWang/EasySpider/assets/91998801/2366118a-8f37-46c2-a8d2-ef1db8786263)
chrome使用的版本有问题，不是最新的
![image](https://github.com/NaiboWang/EasySpider/assets/91998801/d1124c5c-478a-4a44-81f5-46752308c483)
本地安装的版本是最新的
![image](https://github.com/NaiboWang/EasySpider/assets/91998801/bd4f5f74-e8a4-4c67-8457-f25564e0bd62)

**Comment by NaiboWang** [comment]
与Chrome版本无关，报错原因是端口绑定失败，一般是因为同时打开了两个EasySpider程序导致的，建议全部关掉重新打开或重启电脑打开。

**Comment by joker1024567** [comment]
我查了下，发现这个报错是端口占用的问题，因为我本地开启了docker，关闭docker的开机启动，重启后就没有这个报错了。如果打开多个easyspider主程序也会报这个错误。chrome版本的问题是我想多了，作者本身就是在固定版本上开发的，所以版本不是最新的。
最后就是开始的没有创建打开网页的问题，我确实遇到了，但也只是有一定概率（可能是CPU满100%后有概率遇到，我的电脑环境有各种各样的问题），具体的原因就不一一排查了，谢谢作者菌的回复，鞠躬
