### ISSUE TITLE
问下作者如何采集主页面和子页面的数据输出到一行里面？

### ISSUE THREAD

**Issue by 2375399351** [NaiboWang/EasySpider#189]
采集主页面a和b数据后，点击b数据采集c数据后，输出会分为ab和abc两行，有没有办法只输出abc?

**Comment by 2375399351** [comment]
任务流程分别为打开链接-提取ab数据-点击b链接-提取c数据

**Comment by 2375399351** [comment]
试了下设置采集ab数据的时候选择不保存，发现也不行，最终输出的是b和bc……

**Comment by NaiboWang** [comment]
等下个版本吧，将支持暂时不输出某一行数据。

**Comment by 2375399351** [comment]
> 等下个版本吧，将支持暂时不输出某一行数据。

好吧，谢谢

**Comment by LuChuangKeJi** [comment]
请问下这个问题目前的0.5.0版本解决了吗？

**Comment by NaiboWang** [comment]
0.5.0是三个月之前发布的版本，早于你问问题的时间，因此0.5.0没有解决。
但这个功能已经被加入到最新的源代码里了，你可以直接下载源代码编译运行，通过取消勾选`此提取数据操作后生成新数据行`选项来将第一个提取数据操作屏蔽掉，只留下第二个来实现。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/ee71421c-df48-4657-9c7a-03fd1e47c027)

**Comment by NaiboWang** [comment]
> 请问下这个问题目前的0.5.0版本解决了吗？

最新版本V0.6.0可通过设置是否生成新行来解决此问题：

<img src="https://github.com/NaiboWang/EasySpider/assets/30287768/2e580fa5-24e7-4e36-a380-bb886edb4781" width=60%>
