### ISSUE TITLE
easyspider_executestage.py的getData方法

### ISSUE THREAD

**Issue by quert999** [NaiboWang/EasySpider#190]
loopElement参数为空时，会报错lxml.etree.XMLSyntaxError
这时候我把loopElementOuterHTML变量设置成< html />可以走的通，mac版现在用起来已经很方便了，大赞作者
这个markdown编辑器打出来正常的html标签就会不显示。。

**Comment by quert999** [comment]
设置成 '<html/>'

**Comment by NaiboWang** [comment]
谢谢，如果觉得有代码可以改进，推荐提交pull request来合并自己修改的代码到主分支，这样你也是贡献者。
