### ISSUE TITLE
如果我想让两个类型的元素并行两列输出怎么实现？（在同类型元素识别不了的情况下）

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#191]
如果我想让两个类型的元素并行两列输出怎么实现？（在同类型元素识别不了的情况下）
比如微博发文的作者和发布时间作为两个元素无法实现上述功能
如果分开提取，会生成两列但也不会一一对应，不在同一个循环提取的对应列会自动填充同一元素
![image](https://github.com/NaiboWang/EasySpider/assets/133566473/62c0f100-6de8-4146-b44c-4571e3be7c27)

_Originally posted by @steelor in https://github.com/NaiboWang/EasySpider/issues/25#issuecomment-1732525006_

**Comment by NaiboWang** [comment]
<img width="693" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/30287768/be69614c-c2d3-40b4-814d-728ae2626e3c">

右键先选择第一个再选择第二个元素即可生成两个不同的字段并列。

**Comment by steelor** [comment]
我也是参考b站教学视频做的，先识别第一类元素，再点击第二类元素，结果当我点击第二类的时候元素列表就变了，变成了同一行，并且会多出链接文本

**Comment by steelor** [comment]
> <img width="693" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/30287768/be69614c-c2d3-40b4-814d-728ae2626e3c">
> 
> 右键先选择第一个再选择第二个元素即可生成两个不同的字段并列。

我也是参考b站教学视频做的，先识别第一类元素，再点击第二类元素，结果当我点击第二类的时候元素列表就变了，变成了同一行，并且会多出链接文本

**Comment by NaiboWang** [comment]
对啊，你不是想让这两个元素**并行两列**输出吗？这就是你想要的效果吧？

**Comment by steelor** [comment]
就比如下面我选择了页面下的第一类元素
![image](https://github.com/NaiboWang/EasySpider/assets/133566473/3ce2999b-38a6-4eb9-ac22-5ddd943f23e7)
然后我需要点击第二类元素，就是发布时间，当我点击的时候就出现了下面这种情况
![image](https://github.com/NaiboWang/EasySpider/assets/133566473/024a4348-f79b-4b88-817d-5fc58f46f4e7)

**Comment by NaiboWang** [comment]
如果你是想把每一个新闻的作者和发布时间都选上，就先选择一个新闻大块，然后选中全部，再选中子元素，最后删掉不需要的列。

**Comment by steelor** [comment]
> 如果你是想把每一个新闻的作者和发布时间都选上，就先选择一个新闻大块，然后选中全部，再选中子元素，最后删掉不需要的列。

这样可以实现了，多谢大佬，就是要删除的元素有点多😂

**Comment by NaiboWang** [comment]
使用选中子元素（所有块共同元素）会少选择一些子元素，或者手写循环也行。
