### ISSUE TITLE
请问如果某些页面xpath不能进行定位（应该有反爬），有其他方法可以选择吗？

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#192]
请问如果某些页面xpath不能进行定位（应该有反爬），有其他方法可以选择吗？

_Originally posted by @steelor in https://github.com/NaiboWang/EasySpider/issues/25#issuecomment-1733220405_

**Comment by NaiboWang** [comment]
几种可能的方案：

1. 可通过CSS Selector用自定义操作进行提取。
2. 无论如何/html/body把全文提取下来应该可以，再后面自己过滤。
3. 通过JavaScript进行操作和提取。

请根据自己的实际情况选择。

**Comment by steelor** [comment]
好的，感谢
