### ISSUE TITLE
采集的过程中容易跳转到data;界面，执行程序就直接挂掉

### ISSUE THREAD

**Issue by ZhCincent** [NaiboWang/EasySpider#193]
采集流程执行的过程中，偶尔会出现跳转到data;界面 然后后台执行程序就直接挂掉，没办法继续采集、

以前出现偶然的情况是动了鼠标或者点击浏览器的界面，其中还遇过一次 什么都没动，直接跳转了data界面

**Comment by NaiboWang** [comment]
此问题多数是因为history记录的问题，因为部分网页的后退逻辑问题导致后退的次数太多。
解决方案为可以设置条件判断，当出现data;页面时，使用自定义操作，执行JavaScript语句`history.go(1)`前进到指定页面。

**Comment by ZhCincent** [comment]
谢谢、

这种启动调用的方式，能否新增一种http的Api的接口模式，这边更方便调用以及其它地方使用更更方便。

**Comment by NaiboWang** [comment]
如果要增加这种方式，则需要EasySpider主程序一直处于运行状态，实现难度不大，我先记录下，将来有时间再去做。

**Comment by ZhCincent** [comment]
好的，谢谢

**Comment by Xiaozl11** [comment]
这个问题应该在条件判断中如何表示，页面是空白的，只有地址栏是data;, 不知道如何判断地址是不是data;

**Comment by Xiaozl11** [comment]
> > 这个问题应该在条件判断中如何表示，页面是空白的，只有地址栏是data;, 不知道如何判断地址是不是data;
> 
> 条件判断使用`eval`操作选项，代码设置为：
> 
> ```python
> self.browser.current_url.startswith("data:")
> ```

感谢回复，我已经解决此问题了。
我爬的网站有这样一个特殊的性质，当退回到data；页面时候，如果执行history.go(1)代码，则会进入到初始页面，并不会退回到上一次的页面。所以我做了以下处理：
![Snipaste_2023-11-30_16-07-00](https://github.com/NaiboWang/EasySpider/assets/141888011/8ca594f3-1399-4d69-9911-63e59124685c)

逻辑为：
点击新的连接不一定会进入，所以做一个判断是否成功进入新的连接，如果进入新的连接失败，则执行history.go(1)，也就是提前前进一次，再执行循环里的内容时候，刚好后退到主页面，这样就不怕后退到data页面了。
