### ISSUE TITLE
MacOs Monterey 12.3执行easyspider_executestage报错

### ISSUE THREAD

**Issue by binyellow** [NaiboWang/EasySpider#194]
[47452] Error loading Python lib '/var/folders/9_/lpfz_ckd1nzfgz0r0mgf_wqc0000gn/T/_MEIn8iiu4/Python': dlopen: dlopen(/var/folders/9_/lpfz_ckd1nzfgz0r0mgf_wqc0000gn/T/_MEIn8iiu4/Python, 0x000A): Symbol not found: _mkfifoat
  Referenced from: /private/var/folders/9_/lpfz_ckd1nzfgz0r0mgf_wqc0000gn/T/_MEIn8iiu4/Python
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by NaiboWang** [comment]
请问是用的哪个版本的程序，Mac是英特尔芯片还是Arm芯片？

**Comment by binyellow** [comment]
版本0.5.0 (0.5.0)
Arm M1芯片

**Comment by NaiboWang** [comment]
打包时使用的是Python 3.11的版本，因此操作系统版本要求最低为13。

可能的几种解决方案：

1. 自行下载源码配置环境运行程序。
2. 等待下个版本，将使用低版本的Python进行打包已解决操作系统兼容问题。
3. 升级MacOS为13及以上版本。

**Comment by binyellow** [comment]
我的python是13版本以上的
![image](https://github.com/NaiboWang/EasySpider/assets/29519985/1a7c3d54-aa8b-4ed5-b290-b4b4eca8db96)
我先试试1   其余2个方案比较耗时

**Comment by binyellow** [comment]
我的python是3.11版本以上也没用哈？就是MacOs版本要>=13
![image](https://github.com/NaiboWang/EasySpider/assets/29519985/e09f854b-e58c-4073-a09f-24598d394352)
我先试试1 其余2个方案比较耗时

**Comment by NaiboWang** [comment]
打包时的python版本和你自己Python的版本无关，是我这边打包的环境。

自行编译是最简单的方案，也最有效，可以试试。

**Comment by binyellow** [comment]
`发布一条龙脚本.md`编译文档是这块哈？

**Comment by NaiboWang** [comment]
不是，只需要跑ExecuteStage文件夹里的程序即可，按照文件夹里的Readme.md执行。

**Comment by binyellow** [comment]
我升级MacOS到13.6了  现在报这个错

darwin ('64bit', '')
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1794, in <module>
  File "selenium/webdriver/chromium/options.py", line 103, in add_extension
OSError: Path to the extension doesn't exist
[21054] Failed to execute script 'easyspider_executestage' due to unhandled exception!

**Comment by NaiboWang** [comment]
系统升级之后可以尝试直接执行当时压缩包里面的那个文件，不需要自己用代码编译，如果一定想要自己跑代码就把easySpider.app拷贝到ExecuteStage文件夹里再运行。

**Comment by binyellow** [comment]
这个就是直接执行压缩包中的文件，执行提示命令的时候报的，命令如下
`cd /Users/xxx/Downloads/EasySpider_MacOS_all_arch
./easyspider_executestage --id '[25]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/xxx/Library/Application Support/EasySpider/" --headless 0 --read_type remote --config_file_name config.json --saved_file_name `

**Comment by NaiboWang** [comment]
文件夹内确认有EasySpider.app的程序吗？
