### ISSUE TITLE
mac下 下载解压，用如下命令执行得到这个反馈：

### ISSUE THREAD

**Issue by guoqingkong** [NaiboWang/EasySpider#195]
**(base) kong-MBP14:EasySpider_MacOS_all_arch kong$ xattr -cr EasySpider.app**
xattr: No such file: EasySpider.app/Contents/Resources/app/chrome_mac64.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/116.0.5845.187/Helpers/GoogleUpdater.app/Contents/Helpers/GoogleSoftwareUpdate.bundle/ksadmin
xattr: No such file: EasySpider.app/Contents/Resources/app/chrome_mac64.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/116.0.5845.96/Helpers/GoogleUpdater.app/Contents/Helpers/GoogleSoftwareUpdate.bundle/ksadmin
xattr: No such file: EasySpider.app/Contents/Resources/app/node_modules/node-window-manager/build/node_gyp_bins/python3
xattr: No such file: EasySpider.app/Contents/Resources/app/node_modules/extract-file-icon/build/node_gyp_bins/python3

**Comment by NaiboWang** [comment]
请问是用的哪个版本的程序，Mac是英特尔芯片还是Arm芯片，操作系统版本是多少？

**Comment by averyhome** [comment]
尴尬 我怎么也遇到了这个问题 0.6.1，arm 芯片

**Comment by NaiboWang** [comment]
哪里下载的，安装包大小是多少，具体错误截图看一下？

**Comment by yingjialong** [comment]
我也遇到同样的问题了，最新的arm版本，请问如何解决

**Comment by NaiboWang** [comment]
看下截图
