### ISSUE TITLE
网页中xpath能够识别，但执行任务时不能识别

### ISSUE THREAD

**Issue by steelor** [NaiboWang/EasySpider#196]
我在网页中用xpath能够定位到下面这个元素，xpath是通用的，没有特殊性
![image](https://github.com/NaiboWang/EasySpider/assets/133566473/89c1f2fd-2c12-41fc-ae8f-d80c9aec1d4c)
但是在执行任务时会报错
![image](https://github.com/NaiboWang/EasySpider/assets/133566473/0f4f117b-783f-403b-86b0-99cbe3a3ebfe)
虽然后面它默认提取的元素也是定位到的，但是就不能在提取元素前执行JS代码了，请问这是什么原因？麻烦解答

**Comment by NaiboWang** [comment]
可以在执行阶段长按p键暂停，然后使用XPath Helper插件调试看是否在执行阶段的XPath可以检测到元素，如果不能，说明设计阶段和执行阶段的XPath不是同一个，以执行阶段为准。

如果可以检测到，那就是设置的等待时间不够导致元素还没有加载出来，这时候请设置更长的等待时间。

**Comment by steelor** [comment]
原来是设置的等待时间太短了，解决了，膜拜大佬。
还有一个问题，如果想对提取的内容进行正则表达式匹配或者css selector，也是执行JS语句吗？

**Comment by NaiboWang** [comment]
程序默认使用XPath，如果想使用CSS Selector，既可以用JS实现，也可以用自定义操作直接写Python语句调用Selenium接口来实现，正则表达式同理。

**Comment by steelor** [comment]
好的，谢谢！
