### ISSUE TITLE
请问如何解决同一个浏览器，打开两个页面

### ISSUE THREAD

**Issue by sdirkcy** [NaiboWang/EasySpider#197]
我需要在两个不同网点做数据搬运，请问如何解决同一个浏览器，打开两个页面

**Comment by NaiboWang** [comment]
可以自行设计流程甚至手动打开两个页面，然后使用自定义操作的Exec功能操作self.browser写Selenium语句，不断地切换窗口/标签页句柄来实现在两个页面之间的切换和操作：
https://blog.csdn.net/gz_testing/article/details/71251901
