### ISSUE TITLE
读取EXCEL文件

### ISSUE THREAD

**Issue by sdirkcy** [NaiboWang/EasySpider#198]
您好，我看https://www.easyspider.cn/ 你们官网有介绍可以读取EXCEL，请问是如何操作，是通过Python程序读取吗？

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/issues/161

**Comment by sdirkcy** [comment]
感谢回复，手工导入EXCEL可以解决，但如果我想自己做流程时，判断某一个目录下有没有相关的文件时，自动获取执行流程，就是说，如果我指定的目标一直没有文件，流程按照我间隔时间，下次再读取，直到有文件时，再执行

**Comment by NaiboWang** [comment]
上面的issue提到了可以在保存任务时指定excel文件，就不需要每次手动点击按钮了。
如果需要不停检测，建议使用命令行执行，自己写段程序，当检测到有文件时再去使用命令行执行程序。

**Comment by yulongMao** [comment]
但你那个是将标题列的所有数据都输入文本框了，我在issues提了
