### ISSUE TITLE
后续是否支持配置数据mysql存储

### ISSUE THREAD

**Issue by 2837linlinlin** [NaiboWang/EasySpider#20]
后续是否支持配置数据mysql存储

**Comment by NaiboWang** [comment]
csv导入mysql的操作已经有很多现成解决方案了，也就几行代码的问题，或者可以用mysql workbench去图形化的导入。
https://zhuanlan.zhihu.com/p/26964403
https://zhuanlan.zhihu.com/p/53923966
https://dev.mysql.com/downloads/workbench/

所以感觉重复开发的意义不大，尤其是我作为个人开发者还在读博，精力不太够。

所以建议将生成的csv文件通过以上方式自行导入到mysql，或者自己生成脚本，也欢迎提交pr更新此功能~
