### ISSUE TITLE
在已经创建好的流程后，想修改时，无法找到以下的操作台

### ISSUE THREAD

**Issue by sdirkcy** [NaiboWang/EasySpider#200]
在已经创建好的流程后，想修改时，无法找到以下的操作台，这个操作台，目前只有在新建时才看到，请问如何在修改时，可以重新调出这个操作台

<img width="1255" alt="微信图片_20230930214832" src="https://github.com/NaiboWang/EasySpider/assets/146321588/68460b51-2432-49e3-9b85-cdb7443dabcf">

**Comment by NaiboWang** [comment]
点击设计/修改任务，打开浏览器后选择列表中对应的任务，然后修改任务即可。
