### ISSUE TITLE
自定义提出数据

### ISSUE THREAD

**Issue by sdirkcy** [NaiboWang/EasySpider#201]
您好，昨晚在学习使用时，遇到以下问题
第一：请问如何在一个循环点击过程中，把点击的元素名称获取下来
第二：如何把第二个循环里面提现步骤时，把第一个循环的值，放在第二个循环提现数据步骤的数据集里面
中国秋快乐，谢谢！
![image](https://github.com/NaiboWang/EasySpider/assets/146321588/252174a6-a0c5-4106-896b-418e25b39a7e)

**Comment by NaiboWang** [comment]
第一个问题可以在点击元素前选中要点击的元素然后提取元素文本即可。
第二个问题没有看太懂，最好举个例子，或者多试试不同组合，然后看运行后的结果是否是你想要的。

双节快乐！

**Comment by sdirkcy** [comment]
在这个提取介面里面，增加问题一这一步提现的数据，放在第二个循环提现数据的内容里面，形成一组数据
![image](https://github.com/NaiboWang/EasySpider/assets/146321588/6b564239-6e4b-41de-9c77-6efab6da41e6)
我的流程是，每点击上面一行记录，下面就显示这个外呼的结果，然后，把订单号以及这个外呼结果，形成一组结果
![image](https://github.com/NaiboWang/EasySpider/assets/146321588/54c6cd59-d699-4fee-bff0-ea19d67f239e)

**Comment by NaiboWang** [comment]
你现在执行的结果是怎样的？这个流程看不出太大问题。

**Comment by sdirkcy** [comment]
现在问题在于，第一个循环拿不到准确的值 ，乱套一样
![image](https://github.com/NaiboWang/EasySpider/assets/146321588/98019860-fe9a-41ba-b36b-f2d0ea6c60c3)

**Comment by NaiboWang** [comment]
这种情况属于具体的业务逻辑问题，我这边不会做过于详细的答疑，但可以确定的是软件本身运行没有问题，流程设计的具体问题如果实在解决不了可以尝试加QQ群问群友，群号在Readme和网站官网最下方都有。

**Comment by sdirkcy** [comment]
好的，谢谢！

**Comment by Songs12345** [comment]
请问解决了没有，我也是同样需求
