### ISSUE TITLE
成功打开另一个窗口，但提出数据失败

### ISSUE THREAD

**Issue by sdirkcy** [NaiboWang/EasySpider#202]
不好意思 ，双节都麻烦你啦 ，
问题1：成功打开另一个窗口，也成功跳回第一个窗口，但提取数据时，应该是从第二个窗口提取后，再跳回第一个页面，但最终后台输出日志时，显示在第一个窗口的页面找到不提现的XPATH
指导1：目前循环提现一些数据，我想把这些循环的数据（最后一张图），把提现的内容，串成一个字符串或指定格式
<img width="1061" alt="93625c096b593ea4e0c6f9510795cb9" src="https://github.com/NaiboWang/EasySpider/assets/146321588/b3aa77d5-9d98-42b1-ad86-42d2383bbcca">

<img width="1271" alt="ea7b375899c0b01fe7b3a7020727131" src="https://github.com/NaiboWang/EasySpider/assets/146321588/f74fc5d8-741f-45db-9d9b-9950adfff3f6">

<img width="848" alt="f318eb62c942535ab3ff5c3a37493ab" src="https://github.com/NaiboWang/EasySpider/assets/146321588/12a0a915-dd38-407f-8bdc-791b22f81a85">

<img width="871" alt="bda801fcddff879797a53bd1615f97c" src="https://github.com/NaiboWang/EasySpider/assets/146321588/e8e7a5e9-f7b4-48aa-a707-2d0fbad59bda">

![image](https://github.com/NaiboWang/EasySpider/assets/146321588/d17389e4-a49a-4b61-a17c-976781fc7cdc)

**Comment by NaiboWang** [comment]
问题1：成功打开另一个窗口，也成功跳回第一个窗口，但提取数据时，应该是从第二个窗口提取后，再跳回第一个页面，但最终后台输出日志时，显示在第一个窗口的页面找到不提现的XPATH

需要使用Selenium的switch_to API将焦点从原来的窗口跳转到新的窗口，具体请参考以下教程：

https://blog.csdn.net/weixin_33831196/article/details/88654889

指导1：目前循环提现一些数据，我想把这些循环的数据（最后一张图），把提现的内容，串成一个字符串或指定格式

使用Javascript实现，具体请看视频教程。
