### ISSUE TITLE
打不开Chrome

### ISSUE THREAD

**Issue by Sinoftj** [NaiboWang/EasySpider#203]
Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
darwin ('64bit', '')
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1794, in <module>
  File "selenium/webdriver/chromium/options.py", line 103, in add_extension
OSError: Path to the extension doesn't exist
[18802] Failed to execute script 'easyspider_executestage' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by NaiboWang** [comment]
请提供更多有效信息，如是否为自行调试时碰到的问题。
此问题为无法找到插件，一般来说是EasySpider.app和easyspider_executestage文件不在同一个目录导致的。

**Comment by wmy0320** [comment]
i have the same question

**Comment by 1242128273wangpeng** [comment]
如果本地python版本2.x，试试修改python的版本。我改完可以运行了 https://www.cnblogs.com/fmixue/p/15904623.html
