### ISSUE TITLE
无法正常找到元素

### ISSUE THREAD

**Issue by sdirkcy** [NaiboWang/EasySpider#205]
![image](https://github.com/NaiboWang/EasySpider/assets/146321588/b94367b4-c23e-4255-adec-2b5688265cce)
该软件是一个很老旧的软件，使用是easyui这种UI，使用F12调试找到这个元素后，通过右键获取XPATH也找不到，使用EasySpide生成的元素，也是找到不元素，同时进入该软件后，操作台的字体也不正常

![image](https://github.com/NaiboWang/EasySpider/assets/146321588/2cbc8240-e8a2-4c98-bb87-668ec12a33b2)

**Comment by NaiboWang** [comment]
通过右键获取XPATH也找不到的情况下，说明网页结构不能在Chrome内核下完整的运行，请审查元素查看是否页面由奇怪的节点包围，如<frame>标签，因为软件并不支持非常古老的页面写法，如IE时代的写法。

或者尝试直接使用相对XPath进行定位，如//input[1]

字体不正常无关紧要，不影响。
