### ISSUE TITLE
通过vs执行easyspider_executestage.py报错

### ISSUE THREAD

**Issue by alexyanghx** [NaiboWang/EasySpider#206]
自己编译master源码并生成执行文件是可以正常使用的。
想使用vs对代码进行debug,调试的时候报下图错误，
![8549757e3b088aa15522a7096e89f263](https://github.com/NaiboWang/EasySpider/assets/13973784/13f0881d-0596-4bee-b143-3b0cf8da8fb2)

如果把应用包的地址填写绝对路径是可以执行过去，但是readType使用的local 又卡在这里了
![b0e2ae23946cacb7e12550670ff69bec](https://github.com/NaiboWang/EasySpider/assets/13973784/70d7b2bd-af75-425c-bcbe-b99a1b79ba9c)

上边两个问题帮看下，需要怎么配置？

**Comment by NaiboWang** [comment]
问题1请将我已经打包好的`EasySpider.app`拷贝到`ExecuteStage`文件夹下即可解决。

问题2如果一定要使用本地模式，就在`ExecuteStage`文件夹下自行建立`execution_instances`文件夹，并将`/Users/你的用户名/Library/Application Support/EasySpider/execution_instances`文件夹下的json文件拷贝到你新创建的文件夹下运行。

或者可以选择使用remote模式，打开EasySpider.app主程序的情况下，调试时传递ID号即可。

**Comment by alexyanghx** [comment]
问题1
我本地加了 主程序包 依然找不到，还是报同样的错
![401c7d3fbdc67b9890567a80990df4f7](https://github.com/NaiboWang/EasySpider/assets/13973784/c6bc1b8f-36e0-4deb-a907-a1375f8619fc)

**Comment by NaiboWang** [comment]
确认ExecuteStage文件夹下EasySpider.app/Contents/Resources/app/XPathHelper.crx是存在的，如果不存在就去ElectronJS目录下拷贝一份到指定目录。

**Comment by alexyanghx** [comment]
![38706d52c666dcff3aab367c51c99904](https://github.com/NaiboWang/EasySpider/assets/13973784/ad25a5a3-0b15-4095-9c5c-f68fcf6d3c59)
打印了下路径，我这个需要放在 根目录下，放在根目录下就可以正常跑了！
