### ISSUE TITLE
执行报错 JSON.stringify is not a function     at buildError

### ISSUE THREAD

**Issue by yuwojiusi** [NaiboWang/EasySpider#211]
执行时提示这个错误，怎么解决呢？
![Uploading cd7309ca875cb4941414c58ac0aac1ce.png…]()

**Comment by yuwojiusi** [comment]
File "threading.py", line 973, in _bootstrap_inner
  File "easyspider_executestage.py", line 210, in run
  File "easyspider_executestage.py", line 468, in executeNode
  File "easyspider_executestage.py", line 471, in executeNode
  File "easyspider_executestage.py", line 860, in openPage
  File "selenium/webdriver/remote/webdriver.py", line 492, in execute_script
  File "selenium/webdriver/remote/webdriver.py", line 429, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 243, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.callFunctionOn threw exception: TypeError: JSON.stringify is not a function
    at buildError (<anonymous>:323:18)
  (Session info: chrome=114.0.5735.90)

**Comment by NaiboWang** [comment]
1. 确定自己的任务流程可以在设计阶段正常打开。
2. 如果可以正常打开，在设计阶段打开Chrome查看版本是否为114，如果不是，说明是版本问题，参考以下issue解决：https://github.com/NaiboWang/EasySpider/issues/181

**Comment by yuwojiusi** [comment]
可以正常打开，只要提取网页数据就报错

**Comment by NaiboWang** [comment]
重新创建一个任务试一试，看是否会有同样的错误。

**Comment by yuwojiusi** [comment]
已经试过了，这个有没有可能是有些网站覆盖了json.stringify()这个方法？

**Comment by NaiboWang** [comment]
换其他网站可以吗？比如默认的京东。

**Comment by yuwojiusi** [comment]
其他网站就是正常的，只有我想采集的目标网站出现此类问题

**Comment by NaiboWang** [comment]
什么网址？我可以帮你试一下。

**Comment by yuwojiusi** [comment]
http://www.eshukan.com/secondchannel.aspx?typeid=29

**Comment by yuwojiusi** [comment]
感谢

**Comment by NaiboWang** [comment]
问题是selenium底层的包导致的，源码已经更新，目前需要你自行下载代码并编译运行。

我这里简单进行了一下修复，简单的任务可以执行，复杂任务看你的实测吧。

**Comment by yuwojiusi** [comment]
好的 谢啦

**Comment by guigutan** [comment]
> 问题是Selenium底层的包导致的，源码已经更新，目前需要你自行下载代码并编译运行。
> 
> 我这里简单进行了一下修复，简单的任务可以执行，复杂任务看你的实测吧。

老哥我C# Selenium的，也是 报他这个错误，Selenium.WebDriver是4.23.0   chrome也是114.0.5735.90，chromedriver对应版本。操作泛微OA登录后就不行，测试其他网站无问题。他上面提到的网址http://www.eshukan.com/secondchannel.aspx?typeid=29也是这个问题。求教

**Comment by guigutan** [comment]
我是搜索问题过来的，没有用你这个。
老哥我C# Selenium的，也是 报他这个错误，Selenium.WebDriver是4.23.0 chrome也是114.0.5735.90，chromedriver对应版本。操作泛微OA登录后就不行，测试其他网站无问题。他上面提到的网址[http://www.eshukan.com/secondchannel.aspx?typeid=29也是这个问题。求教](http://www.eshukan.com/secondchannel.aspx?typeid=29%E4%B9%9F%E6%98%AF%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E3%80%82%E6%B1%82%E6%95%99)
