### ISSUE TITLE
点击按钮下载文件之后的保存路径可以指定吗

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#212]
> > > > 想请问下那种点击按钮下载文件之后的保存路径可以指定吗
> > 
> > 
> > > 
> > 
> > 
> > > 用带用户信息的浏览器设计和执行，更改浏览器下载目录即可。
> > 
> > 
> > 作者你好，我发现这样子在调用任务时还是会恢复默认的下载路径，并不能下载到更改的路径内。并且在翻阅源码时发现在easyspider_executestage.py文件内有写默认下载路径在对应task中，但在实际使用中貌似并没有执行，貌似是bug。
> 
> 源码里并没有指定文件下载目录，只指定了图片下载目录，因此下载的文件会存在系统默认的下载路径中，如下载文件夹。 如果使用的是带用户信息模式，理论上修改的下载位置会被保存下来，不会有问题。

作者您好，我经过反复测试之后发现确实有点小问题，希望您解惑。
为了防止干扰我重新下载了EasySpider_0.5.0_windows_x64版本，以下是我的测试步骤：

1. 打开软件，使用带用户信息浏览器设计
2. 命名目录为test_data点击开始设计
3. 新建一个任务，打开网站后，修改浏览器内默认下载路径为“E:\Downloads\EasySpider_0.5.0_windows_x64”
4. 保存任务并退出所有相关程序
5. 以带用户信息浏览器设计模式选择修改刚刚的任务，确认此时下载路径仍为更改后的路径
6. 返回首页，在执行任务中选择“本地直接执行（带用户信息模式）”
7. 查看执行中的浏览器，发现下载地址变回了“E:\Downloads\”（此时检查此浏览器的历史记录发现有设计模式下的历史记录，说明是同一浏览器）
8. 退出所有进程，再次进入带用户信息浏览器设计模式查看，发现下载路径为“E:\Downloads\”
9. 后续我更改7中执行中的浏览器的下载路径同样失效

综上，程序在设计模式下修改的下载路径可以保存，但在调用任务时似乎会重置回默认路径，这个问题应该如何解决呢。

_Originally posted by @HHR-learner in https://github.com/NaiboWang/EasySpider/issues/25#issuecomment-1751929850_

**Comment by NaiboWang** [comment]
经测试确实存在此问题，源码中也指定的文件下载目录但是没有起作用，原因暂时不明朗，所以只能使用以下替代方案：

1. 在打开网页前设置一个内容为空的自定义操作，操作后等待时间设置为15秒左右，任务执行时，利用这15秒打开设置修改浏览器默认下载目录，然后无需关闭设置页面，等待程序执行下面的操作。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/a52aae7a-56ee-43c9-8bc0-9bfb355421d1)

2. 在下载文件后自行通过写代码或者手动复制粘贴的方式将文件拷贝到指定目录。

**Comment by HHR-learner** [comment]
好的，非常感谢您的解答！

**Comment by NaiboWang** [comment]
很好，谢谢！

**Comment by jernjie** [comment]
有一个新问题是我在点击一个链接下载excel文件时需要多次下载，每次的内容不一样，但点击下载后他文件是同一个，正常点击的话就是1.xlsx，1（1）.xlsx这样 但是调度执行就会覆盖写1.xlsx只有最后一个文件

**Comment by devilpie** [comment]
我也遇到了相似的问题，在网站上进行了下载，但是修改了json的浏览器下载路径后，还是保存到默认路径，很苦恼
