### ISSUE TITLE
关于保存格式

### ISSUE THREAD

**Issue by Danmo121** [NaiboWang/EasySpider#213]
提取流程是点击链接打开页面，提取页面的文字，使用xlsx保存时，有的页面的文字并未被采集完（字符数仅为几千），但保存为txt格式时，正常采集，这大概率是什么原因。

**Comment by NaiboWang** [comment]
Excel单个表格最大长度为15000汉字，如果不超过，建议手动把txt文件的文字拷贝到Excel单元格中看看是否可以显示全。

如果可以显示全，那说明采集过程中设置的等待时间太短等原因导致文字没有加载全，参考：https://github.com/NaiboWang/EasySpider/issues/152

**Comment by Danmo121** [comment]
感谢感谢！
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Naibo ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月9日 15:59
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [NaiboWang/EasySpider] 关于保存格式 (Issue #213)
        
      
    
  

Excel单个表格最大长度为15000汉字，如果不超过，建议手动把txt文件的文字拷贝到Excel单元格中看看是否可以显示全。
如果可以显示全，那说明采集过程中设置的等待时间太短等原因导致文字没有加载全，参考：#152
