### ISSUE TITLE
编译执行阶段程序ExecuteStage 时报错

### ISSUE THREAD

**Issue by yuwojiusi** [NaiboWang/EasySpider#214]
按照主程序，浏览器扩展，执行阶段程序顺序编译，也能正常设计任务，但是在编译执行阶段程序时报错，如下：
<img width="1279" alt="截屏2023-10-10 10 25 52" src="https://github.com/NaiboWang/EasySpider/assets/4416813/3a4906a5-3deb-4c8c-b22c-87f4dc0411b9">

环境：maos

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/issues/206
