### ISSUE TITLE
使用无头模式下载pdf失败

### ISSUE THREAD

**Issue by HHR-learner** [NaiboWang/EasySpider#215]
在正常模式可以正确点击下载，但是在无头模式无法下载到本地，无报错，截图显示所有模拟操作正确执行，网站也响应了，但是就是不能保存。
![1696903582 943134](https://github.com/NaiboWang/EasySpider/assets/74774809/b88a6dfe-f292-44be-9e7a-0aef19625ce9)

**Comment by NaiboWang** [comment]
请尝试参照以下issue的解决办法在打开网页前后添加自定义操作并填入相应代码：

https://github.com/NaiboWang/EasySpider/issues/212

然后尝试下载，我自己测试软件下载是没有问题的。

如果再不行请尝试用最新源码编译运行。

**Comment by HHR-learner** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/74774809/9655a872-a6dd-44fd-91b3-877d0893e046)
按照上述方法操作后依然下载失败，正在尝试编译源码运行

**Comment by HHR-learner** [comment]
在编译源码过程中遇到困难，

**Comment by HHR-learner** [comment]
在编译过程中遇到了困难，各种奇奇怪怪的报错，同时有一些疑惑，请问按照建议编译顺序（浏览器扩展-主程序-执行阶段程序）内的readme编译就可以吗，那“发布一条龙脚本”里的步骤需要执行吗，里面的一些步骤在readme中似乎没有。

**Comment by HHR-learner** [comment]
您好，相关邮件已发送至邮箱：naibowang@comp.nus.edu.sg，请你查收

**Comment by NaiboWang** [comment]
已回复邮件，我这边实测在无头模式下可以正常运行没有问题，你可以把这个json文件直接放入execution_instances文件夹下然后制定—id [218] 来运行。

没有什么大改动，最后一个操作为了稳妥等待时间改为了100秒。

运行时使用了现在最新的源码，如果老代码跑步起来请尝试使用新代码编译。

**Comment by HHR-learner** [comment]
经测试，仍然是普通时可以下载，无头时无法下载，下面开始尝试编译新代码

**Comment by NaiboWang** [comment]
给你邮箱发送了打包好的最新版。

将压缩包解压后，替换下面文件夹里的源文件，然后再次测试。

EasySpider_windows_x64\EasySpider\resources\app\chrome_win64

**Comment by HHR-learner** [comment]
非常感谢您的帮助！经测试，您发送的新编译的源码已经生效：

1. 在headless模式下，点击下载的pdf成功默认下载到对应的task文件夹内
2. 在正常模式下，点击下载的pdf成功下载到[212](https://github.com/NaiboWang/EasySpider/issues/212)对应的目录中
3. 值得一提的是，在headless模式下，[212](https://github.com/NaiboWang/EasySpider/issues/212)的修改方法将会失效，但与我的需求不相关

非常感谢您耐心的答疑！

**Comment by NaiboWang** [comment]
好的
