### ISSUE TITLE
无法执行任务_Mac M2 Ventura13.5.2

### ISSUE THREAD

**Issue by patrickstar231** [NaiboWang/EasySpider#217]
执行任务时报错
EasySpider_MacOS_all_arch % cd ********/Easyspider_Macos_a11_arch . /easyspider_executestage --id "[0]"
--useI_data 0 --server_address http://1ocalhost:8074 --config_folder "*******/Library/Application Support/Easyspider/" ]
--headless e --read_type remote --config_file_name config .json --saved_file-name
cd: too many arguments

单独执行时提示“No such files”
******EasySpider_MacOS_all_arch % cd *********/EasySpider_MacOS_all_arch./easyspider_executestage
cd: no such file or directory: **********/EasySpider_MacOS_all_arch./easyspider_executestage

***打码了哈

**Comment by NaiboWang** [comment]
你的EasySpider文件夹在哪个地方，就去cd到哪里，如

```
cd /Users/NaiboWang/Downloads/EasySpider_MacOS_all_arch
```

如果你已经把文件夹换了位置，就cd到对应为止，确保文件夹内有easyspider_executestage程序存在。

然后，执行：

```
. /easyspider_executestage --id "[0]"
--useI_data 0 --server_address http://1ocalhost:8074/ --config_folder "*******/Library/Application Support/Easyspider/" ]
--headless e --read_type remote --config_file_name config .json --saved_file-name
```

**Comment by patrickstar231** [comment]
是的 已经更换过对应的程序所在文件夹，还是没跑起来。麻烦你看看截图
<img width="577" alt="SCR-20231011-bhrm" src="https://github.com/NaiboWang/EasySpider/assets/138713545/ea768c02-4f5a-4eb0-a505-8b16d0ff539c">
<img width="1236" alt="SCR-20231011-bili" src="https://github.com/NaiboWang/EasySpider/assets/138713545/7a468089-2714-4d41-a892-bd83a1d7522a">

**Comment by NaiboWang** [comment]
换成bash去跑  zsh跑起来有问题。
另外就是--id 后面的单引号格式似乎有问题，不应该有倾斜角度。

**Comment by patrickstar231** [comment]
还是不行 即便我单独cd运行Unix也不行
<img width="565" alt="SCR-20231011-buue" src="https://github.com/NaiboWang/EasySpider/assets/138713545/68861e93-5c97-4c6c-9a4c-57f8775466b9">

**Comment by NaiboWang** [comment]
命令必须分成两步，第一步cd到EasySpider文件夹，第二步./easyspider_executestage --id [3]，不能合在一起。

所以，先cd /Users/..../Desktop/EasySpider_MacOS_all_arch

然后./easyspider_executestage --id [3]

**Comment by patrickstar231** [comment]
可以了 请原谅我这个小白 

感谢大神

**Comment by zhaoyiyidan** [comment]
您好，我无法安装，问题如下。我首先cd到EasySpider文件夹，第二步./easyspider_executestage --id [3]，但是出现了下列问题
<img width="738" alt="截屏2023-11-25 11 45 01" src="https://github.com/NaiboWang/EasySpider/assets/139891330/796ac031-7bf5-452a-841b-778ecbb2db4c">
 我阅读了macOS教程，但是这个问题教程中并没有出现。issues中我并未找到如何解决。                             感谢你的解答
