### ISSUE TITLE
请问设计的时候点击链接跳转能重定向url,任务执行的时候当前url不能重定向url，如何处理重定向问题呢

### ISSUE THREAD

**Issue by FanPan3359** [NaiboWang/EasySpider#218]
![企业微信截图_16969947121473](https://github.com/NaiboWang/EasySpider/assets/40200445/2dc05817-b6e0-407f-bcab-c86b3aeb67e8)
![企业微信截图_16969947043634](https://github.com/NaiboWang/EasySpider/assets/40200445/f3b1e9d8-6f8c-49b5-a11c-6fa0bef13bdb)

设计任务的时候当前浏览器窗口能点击链接跳转到新的url: http://192.168.2.55:1100/businesssystem/index ，点击链接中是没有index后缀, 能够重定向过去，执行任务的时候跳转 http://192.168.2.55:1100/businesssystem/ 无法重定向到新的index后缀地址，加上自定义操作js或selenium跳转也无法跳转过去http://192.168.2.55:1100/businesssystem/index ，默认当前浏览器窗口地址都是http://192.168.2.55:1100/businesssystem/  ，请问怎么处理重定向的问题呢？

**Comment by NaiboWang** [comment]
问题无法复现，因为你的网站是本地网站，所以我这边暂时没办法帮你调试。

如果能想办法找到一个公网可以访问的网站出现同样的问题，我可以帮忙看一下。

**Comment by FanPan3359** [comment]
> 问题无法复现，因为你的网站是本地网站，所以我这边暂时没办法帮你调试。
> 
> 如果能想办法找到一个公网可以访问的网站出现同样的问题，我可以帮忙看一下。

http://vue.ruoyi.vip  内网系统用的若以系统改的微前端，模拟登录后http://vue.ruoyi.vip/index 会url加载index后缀首页，执行任务的时候index无法加载

**Comment by NaiboWang** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/f2ab55c9-14b6-4b14-a91d-76d1d4f79db8)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/0523bc06-386e-498a-8994-c0a081e51a16)

我这边可以成功执行，不知道你说的哪个地方index无法加载。

**Comment by FanPan3359** [comment]
> ![image](https://user-images.githubusercontent.com/30287768/274152663-f2ab55c9-14b6-4b14-a91d-76d1d4f79db8.png) ![image](https://user-images.githubusercontent.com/30287768/274152687-0523bc06-386e-498a-8994-c0a081e51a16.png)
> 
> 我这边可以成功执行，不知道你说的哪个地方index无法加载。

![企业微信截图_16970043079811](https://github.com/NaiboWang/EasySpider/assets/40200445/023ab81a-2b74-4070-9f79-fc08a2982f20)

设计任务的时候，登录进去能够加载首页正常跳转，

![企业微信截图_16970040911955](https://github.com/NaiboWang/EasySpider/assets/40200445/69a883f5-f4b0-4dfc-9c29-88c5ac0bdeb8)
![企业微信截图_16970042414522](https://github.com/NaiboWang/EasySpider/assets/40200445/d20d9d19-36a9-4be0-a970-d869fa03e80e)

执行任务的时候  浏览器地址就不能加载最后index ,收到输入获取通过js跳转都只能到http://192.168.2.55:1100/businesssystem 这里 无法再加载index了

**Comment by NaiboWang** [comment]
无法复现，如上面的截图所示，你给我的那个网址，我在执行阶段可以跳转到index页面进入主页面。

**Comment by FanPan3359** [comment]
> 无法复现，如上面的截图所示，你给我的那个网址，我在执行阶段可以跳转到index页面进入主页面。

非常感谢支持，再次用另外一个系统测试，是正确的，这个内网系统页面是进去了，js资源未能加载导致的，可能是这个网站配置问题，不是地址跳转问题。

**Comment by NaiboWang** [comment]
好的。
