### ISSUE TITLE
能否增加定时自动执行功能

### ISSUE THREAD

**Issue by dsgvsn** [NaiboWang/EasySpider#22]

**Comment by NaiboWang** [comment]
程序本身支持通过命令行方式访问, 举例说明:

MacOS下通过以下命令直接直接任务: 

<img width="501" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/30287768/c8028168-d0b6-4dc8-85e8-70820c617b17">


```
./easyspider_executestage --id 17 --user_data 1 --server_address http://localhost:8074 --config_folder "/Users/naibowang/Library/Application Support/EasySpider/"
```

则我们可以直接将此命令放入`crontab`定时器中设置定时执行即可:

```
crontab -e
```

设置规则,如每12小时执行一次:

```
0 */12 * * *  /Users/.../easyspider_executestage --.....
```

记得easyspider本体程序不要关.

**Comment by dsgvsn** [comment]
好的了解了，我去找找windows上的替代品

**Comment by NaiboWang** [comment]
https://www.cnblogs.com/sui776265233/p/13602893.html
可以看看这个，如果还有问题欢迎继续讨论

**Comment by NaiboWang** [comment]
Windows x64下想要使用命令行执行程序，需要以下操作：
1. 调用任务时在下方获得任务执行号，记住这个`执行ID`：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/437adeb6-78b6-403e-aec9-f2c6b49af7da)

2. 打开命令行程序，进入EasySpider文件夹，并输入命令：

```
./EasySpider/resources/app/chrome_win64/easyspider_executestage.exe --id 4 --user_data 1 --server_address http://localhost:8074
```

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/39adc5c4-e1f7-413c-b733-bfd970c4f396)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/32fe5fc5-b797-41dc-939d-6562ed597c57)

其中，`--id`后面跟的是第一步得到的`执行ID`，`--user_data`为1则为带用户配置的浏览器，配置目录地址写在了上图`config.json`文件的`absolute_user_data_folder`字段中；为0则为纯净版浏览器。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/b309204c-0178-4952-a4ae-70f1bb97dd01)

**Comment by Zeniubius** [comment]
mac 有没有办法实现，不打开程序本体的情况下，执行任务呢，像 Windows 一样，我试了把 --read_type local 改成这种，貌似不行

**Comment by NaiboWang** [comment]
> mac 有没有办法实现，不打开程序本体的情况下，执行任务呢，像 Windows 一样，我试了把 --read_type local 改成这种，貌似不行

MacOS需要在easyspider_executestage同级文件夹建立一个tasks文件夹，然后把任务的.json文件拷贝进来，也就是你执行任务时候提示的Application Support/EasySpider/tasks文件夹里的.json文件，然后--read_type local即可。

**Comment by luoyuyimeng** [comment]
请问下，定时执行完后怎么自动关闭浏览器和执行窗口呢

**Comment by NaiboWang** [comment]
> 请问下，定时执行完后怎么自动关闭浏览器和执行窗口呢

https://github.com/NaiboWang/EasySpider/issues/220
