### ISSUE TITLE
使用powershell运行结束后怎么退出

### ISSUE THREAD

**Issue by zhyim0712** [NaiboWang/EasySpider#220]
![6fa1c0bd4c96268c004723d85c09b2aa](https://github.com/NaiboWang/EasySpider/assets/32584979/f997f962-f243-4b71-bf77-63f53f5a6e7c)
一直卡在这个页面

**Comment by NaiboWang** [comment]
命令行最后加入` --keyboard 0`即可，只是这种模式下无法使用键盘控制暂停和继续。
