### ISSUE TITLE
提示没有keyboard参数

### ISSUE THREAD

**Issue by zhyim0712** [NaiboWang/EasySpider#221]
<img width="976" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/32584979/0c3b7eaf-c2a3-4ac8-a57b-ad575074279d">
麻烦作者再瞅瞅

**Comment by NaiboWang** [comment]
你用的是哪个版本？把所有命令行的全部截图发我看一下，我自己试过0.5.0没有任何问题

**Comment by zhyim0712** [comment]
> 你用的是哪个版本？把所有命令行的全部截图发我看一下，我自己试过0.5.0没有任何问题

0.3.5有这个问题，0.5.0没有，感谢🙏
