### ISSUE TITLE
如果某网页比如循环下一页中 偶尔有时候会出现503等报错，当然多次刷新一般能打开 那么这种需要如何设计流程  或者判断 比如当出现特定信息时 重新刷新这个页面在爬取  或者找不到需要元素 有个重刷新机制 也就是问题不是需要时间来加载而是直接比如403 503等错误

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#222]
你好  这边咨询下 如果某网页比如循环下一页中 偶尔有时候会出现503等报错，当然多次刷新一般能打开 那么这种需要如何设计流程  或者判断 比如当出现特定信息时 重新刷新这个页面在爬取  或者找不到需要元素 有个重刷新机制 也就是问题不是需要时间来加载而是直接比如403 503等错误

_Originally posted by @ahuyuhy in https://github.com/NaiboWang/EasySpider/issues/100#issuecomment-1762457543_
            

添加无限循环（如循环单个元素//body循环9999次），然后循环里添加条件判断检测是页面是否存在指定文本或元素，如果存在就添加自定义操作用JavaScript或者Python刷新页面，否则在另一个条件分支里添加自定义操作Break掉循环即可。

**Comment by ahuyuhy** [comment]
收到 这边刚才也尝试了下 思路差不多 已经实现了功能  感谢师傅解答
