### ISSUE TITLE
大佬好，我要采的网页（xhs）向下滚动后会刷新出一批子链接，然后要逐个点击子链接再进去采数据。不太会操作🙁

### ISSUE THREAD

**Issue by baiyh19** [NaiboWang/EasySpider#226]
我要采集小红书上的一些信息，然后就是每次只会刷新出一部分，需要向下滚动才会继续刷新。每刷新出一批需要逐个点击进入子页面采集数据然后再下一个。试了试不太会，请教您，非常感谢~
![image](https://github.com/NaiboWang/EasySpider/assets/89718789/f48d59dc-abce-4494-9739-24f42ad51385)
![image](https://github.com/NaiboWang/EasySpider/assets/89718789/6d2473c8-8dd0-4f01-9135-8662fc0ab1d7)

**Comment by NaiboWang** [comment]
参考下面这两期视频：
https://www.bilibili.com/video/BV1G14y1o7Qa/
https://www.bilibili.com/video/BV14u4y1x7S5/

**Comment by mjy23** [comment]
> 参考下面这两期视频： https://www.bilibili.com/video/BV1G14y1o7Qa/ https://www.bilibili.com/video/BV14u4y1x7S5/

您好，小红书网站滚动后无法正常识别每一条笔记，会出现一条笔记重复抓取，或者滚动后只能识别到当前页面的某一条笔记，所以每个关键词大概只能抓20-30条数据，请问这个该怎么解决呢？
