### ISSUE TITLE
爬取数据时间处理 进行校验

### ISSUE THREAD

**Issue by 1749335128** [NaiboWang/EasySpider#227]
我在做一个新闻文章方面的爬虫，我有一个很普通的要求就是 我只要最近一个月的数据，或者当天的数据。 以下是我的操作流程： 
![image](https://github.com/NaiboWang/EasySpider/assets/86713070/b6edc6e8-57ff-4483-8b3e-b12895c6d17e)
![image](https://github.com/NaiboWang/EasySpider/assets/86713070/847b808a-bd73-411b-bbf3-ba78de9afb58)

可以看到提取数据 值 第三个记录值为时间，且可以正常获取到。
然后我再条件分支下添加了循环内js值判定，要求时间要一个月以内，当超过30天就执行自定义操作跳出循环。
![image](https://github.com/NaiboWang/EasySpider/assets/86713070/898ec17a-7dfc-4c0f-9dca-9b854b37d93a)
js代码：return (new Date().getTime() - new Date(arguments[2].innerText).getTime()) / (1000 * 60 * 60 * 24) > 30
我从控制台可以看到 所有的超过一个月时间的数据。
![image](https://github.com/NaiboWang/EasySpider/assets/86713070/bda39ef8-f35b-4ca9-b340-640c7c972c6b)
还有一个问题，目前我只看到了结束当前break的方法，我想直接结束此次爬虫的方法好像没有找到。

**Comment by 1749335128** [comment]
问题在于 我写的校验时间逻辑的js代码永远都返回 false，这是我看日志得到的结论。

**Comment by NaiboWang** [comment]
arguments[0]是固定写法，不能写成arguments[2]。

**Comment by NaiboWang** [comment]
所有语言的Break逻辑都是退出最近的循环，如果想要直接退出程序，使用自定义操作的exec语句，执行:

```Python
import sys
sys.exit(0)
```

即可。

**Comment by 1749335128** [comment]
> arguments[0]是固定写法，不能写成arguments[2]。
可以看到 我提取了数据三个字段  分别是标题，标题链接和时间，不能写arguments[2]，如何获取到我的在循环提取的时间呢

**Comment by 1749335128** [comment]
> 把2改成0

换成2仍然不行。可能没有明白我的意思，执行第一个操作提取数据（3个字段），第二个操作判断条件，我应该如何选到第三个字段上来啊，直接写arguments[0] 都不知道它找的什么东西哪个字段，我要拿提取数据的第三个字段 时间 ，执行js表达式。

**Comment by NaiboWang** [comment]
图中不是有个点击此处查看更多示例吗？看一下那个例子。
