### ISSUE TITLE
人际关系图谱

### ISSUE THREAD

**Issue by woshinidaye777** [NaiboWang/EasySpider#228]
贤弟好，我发现一个既有价值也有意思的事情：【爬平台用户关注列表】并生成【人际拓扑】，不知道easyspider现有的功能可以实现吗

比如，知乎、B站、Quara等等。

以某大V、Up主为种子用户，向上爬几层他们自己关注的用户，挖掘内容平台的关系网络和新话题，应该是个普适的功能

![人际拓扑2](https://github.com/NaiboWang/EasySpider/assets/148998692/e7ddefd6-6995-48d2-bddd-055f0c2c120e)

举例：

![人际拓扑1](https://github.com/NaiboWang/EasySpider/assets/148998692/8d967527-78cd-497b-96e2-ac9d37ef8da4)

**以知乎张佳玮为种子用户，爬他关注的139个用户列表，再依次爬取这些用户各自关注的列表**

目标：
三层下去，获取几十万用户ID及相互关注情况

<img width="999" alt="1" src="https://github.com/NaiboWang/EasySpider/assets/148998692/f40d3f63-9081-4e01-87cb-e04ffb582b34">

<img width="1060" alt="2" src="https://github.com/NaiboWang/EasySpider/assets/148998692/111cf744-18ed-4036-967d-e4a1483eb38e">

<img width="1090" alt="3" src="https://github.com/NaiboWang/EasySpider/assets/148998692/b9522fa3-e60f-422e-8138-dcda97b9bbdb">

<img width="1077" alt="4" src="https://github.com/NaiboWang/EasySpider/assets/148998692/40605c31-bc88-4ef8-bc9d-bdfb173dbfee">

如果可以，那可是帮了我大忙，不胜感激。

另外，不知星线图（比如词云图）和分词jieba之类的功能，在不在迭代计划里。

**Comment by NaiboWang** [comment]
可以实现你的需求，但如果知乎有反爬需要配合其他高级功能使用。

星线图（比如词云图）和分词jieba之类的功能，不在迭代计划里，软件还是要专攻，迭代计划只会让爬虫功能更好用和丰富，不会涉及到后续的数据分析。
