### ISSUE TITLE
大佬你好，我在使用软件中问题如下，希望能在百忙之中解答，万分感谢

### ISSUE THREAD

**Issue by mhdtoi** [NaiboWang/EasySpider#229]
问题1：https://www.xiaobinwang.cc/category-2.html     这个网址我在学习本软件中像筛选关于理性和感性的文章，然后最后判断中添加了在循环列表中判断文本“性”然后网站搜索出来包含性关键词的61页每页大概有10条   而过滤出来爬取到的不到60条，（如果不筛选可以全部爬下来）
问题2：如果我想筛选多个关键词该如何操作？
                                                                                                                                                                                       最后感谢你的努力付出

**Comment by NaiboWang** [comment]
1. 这个页面问题在于页面需要向下滚动才能显示出所有的文本，因此需要在翻页后设置页面滚动到底部：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/c88c5eed-eef5-462e-abc0-912493539b50)


2. 多重关键词可以用条件判断中的`针对当前循环项的JavaScript语句`选项，通过JS的`或`命令实现，参考：

https://www.bilibili.com/video/BV18C4y1V7J7/

示例：

```JavaScript
return arguments[0].innerText.indexOf("性") >=0 || arguments[0].innerText.indexOf("人") >=0 
```

**Comment by mhdtoi** [comment]
首先感谢耐心解答。确实会影响到，但是，如果刚启动开始爬第一整页有10条数据，它会只爬几个，后面一页会正常，这是因为什么？（已经设置滚动到底，而且爬取到的是网站搜索框里的包括“性”的全部搜索结果    ps：我想试试爬取到的数据条数和搜索到的条数是否吻合。不知道有没有偏差？）

**Comment by NaiboWang** [comment]
我的示例只是在标题中筛选，如果要从内容中筛选就比较麻烦，需要获取文章详情。没有获取到数据大多数情况下都是相应的元素因为等待时间或者viewport等问题导致文字没有被加载出来，因此需要具体情况具体分析。

**Comment by mhdtoi** [comment]
我好奇的是为什么一样的页面第二页就能全部采集到，而第一页就不可以？全部程序跑完就只少了第一页那几条。为此我还在设置中设置了刚开始打开网址后延迟10秒再采集，没有用。我的想法是如果漏采的话应该都会漏采，而不是只有第一页漏采，这样在我看来是很不合理的，所以我认为这是一个bug。（我用网站搜索出来的标题里的关键词全部显而易见，我觉得跟文章详情的话关系不大。

**Comment by NaiboWang** [comment]
把你的任务流程发到982311099@qq.com，我帮你看下，如果是bug就会去修复。

**Comment by NaiboWang** [comment]
tasks文件夹内的最新的json文件或者execution_instances里的最新的json文件，发到上面的邮箱。

**Comment by NaiboWang** [comment]
测试完成，解决办法为：在第一个操作，即打开网页操作选项中也设置页面滚动到底部。

需要深入理解逻辑，你的任务刚开始在第一个页面打开后没有设置页面滚动，后面的点击下一页后都设置了页面滚动，所以才存在你说的问题。

**Comment by mhdtoi** [comment]
我明白了，改正后无问题，感谢耐心解答。
