### ISSUE TITLE
判断条件的条件分支必须在最右边添加无条件分支否则会卡死

### ISSUE THREAD

**Issue by dsgvsn** [NaiboWang/EasySpider#23]

**Comment by NaiboWang** [comment]
这个应该问题不大？有什么是必须不要无条件分支的情况吗？

**Comment by dsgvsn** [comment]
只是刚开始用的时候，发现运行不起来，终端报错也很奇怪。后面对照视频猜测是这个原因才解决的。就是说希望这里人性化一点，给个提示。

**Comment by NaiboWang** [comment]
> 只是刚开始用的时候，发现运行不起来，终端报错也很奇怪。后面对照视频猜测是这个原因才解决的。就是说希望这里人性化一点，给个提示。

好的，谢谢建议，我会开一个issue专门记录大家的各种问题，然后找时间统一开发完。
另外就是刚开始运行不起来，终端报错什么的如果能截图给我会非常感谢，谢谢使用！

**Comment by dsgvsn** [comment]
Configurations:
+-----------------+------+-----------------------+
|       Key       | Type | Value                 |
+-----------------+------+-----------------------+
|        id       | int  | 10                    |
|  server_address | str  | http://localhost:8074 |
| saved_file_name | str  |                       |
|    read_type    | str  | remote                |
|    user_data    | bool | True                  |
+-----------------+------+-----------------------+

win32 ('64bit', 'WindowsPE')
Finding chromedriver in EasySpider D:\tools\EasySpider_windows_amd64/EasySpider
Chrome location: D:\tools\EasySpider_windows_amd64\EasySpider/resources/app/chrome_win64/chrome.exe
Chromedriver location: D:\tools\EasySpider_windows_amd64\EasySpider/resources/app/chrome_win64/chromedriver_win64.exe

Absolute_user_data_folder: D:\tools\EasySpider_windows_amd64\user_data

<selenium.webdriver.chrome.options.Options object at 0x0000024C48704D50>
easyspider_executestage.py:769: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
easyspider_executestage.py:769: DeprecationWarning: use options instead of chrome_options

DevTools listening on ws://127.0.0.1:9575/devtools/browser/4ccd19f0-2ffd-4ef3-9e7f-8c44f4c414a6

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
[1;32mpip index versions commandline_config
pip install commandline --upgrade[0m
Loading stealth.min.js
id:  10
remote
name:  123曝光
[21492:31384:0513/184137.720:ERROR:device_event_log_impl.cc(215)] [18:41:37.720] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[7876:20180:0513/184335.359:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by dsgvsn** [comment]
这次多了一个 Failed to read descriptor from node connection。
之前就是Passthrough is not supported, GL is disabled, ANGLE is这个报错，然后终端会一直不退出

**Comment by NaiboWang** [comment]
> 这次多了一个 Failed to read descriptor from node connection。 之前就是Passthrough is not supported, GL is disabled, ANGLE is这个报错，然后终端会一直不退出

这些是selenium报的问题，理论上不会影响程序执行，请问设计的流程有没有正常执行？没有的话卡在了哪里？
如果不能正常执行的话，可以把execution_instances文件夹里的10.json文件发在这里，我可以帮忙看下问题出在哪里

**Comment by dsgvsn** [comment]
这就是判断条件的条件分支没有在最右边添加无条件分支造成的卡死时的log

**Comment by NaiboWang** [comment]
好，注意到了，如果以后还有其他问题请继续提issues
