### ISSUE TITLE
爬取一个商品价格本类型网站时的疑问

### ISSUE THREAD

**Issue by 511568** [NaiboWang/EasySpider#230]
开发者好，我是个菜鸡，但是这个软件确实能为我工作带来很多便利，目前爬取一个价格本类型的网站遇到一点疑惑，麻烦给解答一下
![CF1314A5BD8BE93FDBD63F3BAC0C68D4](https://github.com/NaiboWang/EasySpider/assets/13399892/c371ba90-6569-4846-a759-43ffb2198d8a)
截图的是两种不同品牌产品的不同sku组合。当我想固定循环点击（极数）下的1/2/3/4P，然后再循环点击（额定电流）下的各按钮，这该怎么做判断呢？因为两个产品显示的页面布局是不同的，但显示的内容是相同的。我已经根据其中一种设计好了流程了，但换另一种后，因为布局有所不同，会错误的选择

**Comment by 511568** [comment]
站点地址是https://www.dq123.com/price/

**Comment by NaiboWang** [comment]
条件判断中通过JS判断指定布局（XPath）是否存在，具体细节这里不做答疑，如有需要请加群问。
