### ISSUE TITLE
页面弹窗遮挡住图形验证滑块

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#231]
爬 来赞达 菲律宾站 页面弹窗遮挡住图形验证滑块 https://www.lazada.sg/?spm=a2o42.searchlist.header.dhome.2bc13737fneiHG
![image](https://github.com/NaiboWang/EasySpider/assets/58603255/76bfce3f-43aa-4fa6-a6ab-f54fc82927db)

_Originally posted by @7-happy in https://github.com/NaiboWang/EasySpider/issues/100#issuecomment-1794677061_

**Comment by NaiboWang** [comment]
可点击右下角叉号×关闭提示框以进行登录等操作。

**Comment by honorRongYao** [comment]
![图片](https://github.com/NaiboWang/EasySpider/assets/46124853/4f991c20-e062-4f14-ba49-f484b7a193fc)
点了没反应

**Comment by NaiboWang** [comment]
鼠标左键点击。

**Comment by honorRongYao** [comment]
![企业微信截图_17041796044750](https://github.com/NaiboWang/EasySpider/assets/46124853/63ff6544-b5d7-4baf-9308-cf953130c63b)

点了还是没反应，大佬这种是不是要特殊的操作才行了

**Comment by honorRongYao** [comment]
![Uploading 202412152113.png…]()
点了还是没反应，大佬这种是不是要特殊的操作才行了

**Comment by honorRongYao** [comment]
![202412152113](https://github.com/NaiboWang/EasySpider/assets/46124853/cfc3804b-4498-4d88-83f9-6305a7b27aa8)
左键点了也无效，大佬是不是我操作有误还是要改什么东西了

**Comment by NaiboWang** [comment]
https://github.com/NaiboWang/EasySpider/wiki/%E6%93%8D%E4%BD%9C%E5%8F%B0%E6%8C%A1%E4%BD%8F%E7%99%BB%E5%BD%95%E9%A1%B5%E9%9D%A2%E7%9A%84%E5%A4%84%E7%90%86%E5%8A%9E%E6%B3%95
参考这个第一部分的6-8条。
