### ISSUE TITLE
macos arm64 拖动“点击元素”按钮 到 流程图中，没反应

### ISSUE THREAD

**Issue by adwpc** [NaiboWang/EasySpider#235]
版本0.5.0 (0.5.0)
macos 13.5.2 (22G91)
Apple M2 Pro (arm64)
拖动“点击元素”按钮 到 流程图中，没反应

**Comment by NaiboWang** [comment]
感谢反馈，这是一个Bug，将在下个版本中修复，目前的解决方案是可通过设计阶段在浏览器生成一个点击元素选项然后改选项内容，或者通过复制的方式复制已有的剪切元素选项。
