### ISSUE TITLE
在需要选择日期的网页出现的问题

### ISSUE THREAD

**Issue by AutisicLazzzyCat** [NaiboWang/EasySpider#237]
作者你好，非常感谢你开发出这样优秀方便的软件。我在使用EasySpider时发现它在选择日期时遇到一些问题。
![image](https://github.com/NaiboWang/EasySpider/assets/65114152/9a514412-a0e2-48e1-8c95-10272fc772c9)
如图，我想使用EasySpider定期爬取我在百度分析网站的一些统计数据。我希望每个月月初能自动抓取上个月的数据，所以我需要准确的选择或者输入日期。
![image](https://github.com/NaiboWang/EasySpider/assets/65114152/ca4dc8de-9be7-4f65-8354-8f9594cab943)
请注意图中红框，这里是我在点击蓝色日期栏选择后出现的日历选区，正常来说，我可以用鼠标点选日期的起始，也可以在红框输入日期的起始。我选择使用手动输入范围的方式，以便任务定期修改。

可是在我选择输入文字后，日历选区就会消失。
![未命名1700618091](https://github.com/NaiboWang/EasySpider/assets/65114152/d8933927-2f7f-4af9-8ff9-fb7e9b657a2a)

此时继续输入日期后，点击日历选择会发现日期成功输入了，但是却不被系统认可。
![image](https://github.com/NaiboWang/EasySpider/assets/65114152/6b44296b-5a0f-4f2d-a68b-4082473ddb55)

无法正确选择日期问题，还望解答

**Comment by NaiboWang** [comment]
很多网站的日期选择框是JavaScript脚本操控的，有相关的验证机制，不能用EasySpider自带的输入文字功能自动匹配，需要鼠标手动选择后进行接下来的操作，图中这种情况建议直接使用鼠标模拟选择，同时观察URL中是否有日期可以修改，如果没有还实在是操作不了，就每次执行任务前手动暂停或等待一段时间，手动鼠标选择后进行接下来的操作。

**Comment by AutisicLazzzyCat** [comment]
> 很多网站的日期选择框是JavaScript脚本操控的，有相关的验证机制，不能用EasySpider自带的输入文字功能自动匹配，需要鼠标手动选择后进行接下来的操作，图中这种情况建议直接使用鼠标模拟选择，同时观察URL中是否有日期可以修改，如果没有还实在是操作不了，就每次执行任务前手动暂停或等待一段时间，手动鼠标选择后进行接下来的操作。

请问有鼠标模拟选择相关的案例可以学习吗，还是说您的意思是在自动抓取过程中加手动选择日期的步骤？我不太清楚这种情况如何中断/暂停任务然后手动选择日期并继续

**Comment by NaiboWang** [comment]
鼠标模拟选择和点击按钮没区别，运行过程中可以随时长按p暂停执行，然后选择完成后再次长按p继续。

**Comment by kingship** [comment]
> > 很多网站的日期选择框是JavaScript脚本操控的，有相关的验证机制，不能用EasySpider自带的输入文字功能自动匹配，需要鼠标手动选择后进行接下来的操作，图中这种情况建议直接使用鼠标模拟选择，同时观察URL中是否有日期可以修改，如果没有还实在是操作不了，就每次执行任务前手动暂停或等待一段时间，手动鼠标选择后进行接下来的操作。
> 
> 请问有鼠标模拟选择相关的案例可以学习吗，还是说您的意思是在自动抓取过程中加手动选择日期的步骤？我不太清楚这种情况如何中断/暂停任务然后手动选择日期并继续

可以添加【自定义操作】执行python代码操作selenium来操作鼠标点击事件:`
# 获取拖拽的圆球
slideblock = self.browser.find_element(By.XPATH,'//SPAN[@class="nc_iconfont btn_slide"]')

#滑块移动轨迹
def get_track(distance):
    track=[]
    current=0
    mid=distance*3/4
    t=random.randint(2,3)/10
    v=0
    while current<distance:
          if current<mid:
             a=2
          else:
             a=-3
          v0=v
          v=v0+a*t
          move=v0*t+1/2*a*t*t
          current+=move
          track.append(round(move))
    return track
# 生成拖拽移动轨迹，加3是为了模拟滑过缺口位置后返回缺口的情况
track_list=get_track(300)
time.sleep(2)
ActionChains(self.browser).click_and_hold(slideblock).perform()
time.sleep(0.2)
# 根据轨迹拖拽圆球
for track in track_list:
    ActionChains(self.browser).move_by_offset(xoffset=track,yoffset=0).perform()
# 模拟人工滑动超过缺口位置返回至缺口的情况，数据来源于人工滑动轨迹，同时还加入了随机数，都是为了更贴近人工滑动轨迹
imitate=ActionChains(self.browser).move_by_offset(xoffset=-1, yoffset=0)
time.sleep(0.015)
imitate.perform()
time.sleep(random.randint(6,10)/10)
imitate.perform()
time.sleep(0.04)
imitate.perform()
time.sleep(0.012)
imitate.perform()
time.sleep(0.019)
imitate.perform()
time.sleep(0.033)
ActionChains(self.browser).move_by_offset(xoffset=1, yoffset=0).perform()
# 放开圆球
ActionChains(self.browser).pause(random.randint(6,14)/10).release(slideblock).perform()
time.sleep(2)`
