### ISSUE TITLE
请问xhs滚动翻页后再抓数据的时候会出现bug，比如重复抓一条笔记并且不能按顺序把每一条都抓下来，有无解决方法呀？

### ISSUE THREAD

**Issue by mjy23** [NaiboWang/EasySpider#238]
![微信图片_20231122112947](https://github.com/NaiboWang/EasySpider/assets/150579609/ad3012ec-2cc4-4864-af9f-d871cab8e17b)

**Comment by NaiboWang** [comment]
大概率是XPath没有设置好，这种需要具体情况具体分析，因为是业务需求所以这里不做详细解答，可以加群问群友。
