### ISSUE TITLE
编译ExecuteStage时报错

### ISSUE THREAD

**Issue by bigbang007jay** [NaiboWang/EasySpider#239]
![image](https://github.com/NaiboWang/EasySpider/assets/98505248/d3b101b1-f9b1-44a4-9dac-c404335798ef)
执行第三步，编译ExecuteStage时报错，如上面截图
按道理，已经满足上面描述这个条件：
运行程序前，确保已经完成了ElectronJS文件夹下主程序的编译，保证chrome文件夹和chromedriver环境已经就绪，同时EasySpider主程序已在运行中。
根据代码，这个execution_instances是空的，暂时不知道怎么获取和处理，麻烦UP主抽空看下并解答，谢谢！

**Comment by NaiboWang** [comment]
这是任务文件的问题，重新设计一个新的任务，不要用自带的老任务，然后传入新的任务ID。

**Comment by bigbang007jay** [comment]
收到，谢谢，我今天试试。晚点回复。

**Comment by NaiboWang** [comment]
execution_instances文件夹下的json文件，看看有没有name字段，这个代码如果你没有改过不应该出现这样的问题。
