### ISSUE TITLE
chrome总是秒退

### ISSUE THREAD

**Issue by wwwj27** [NaiboWang/EasySpider#24]

**Comment by NaiboWang** [comment]
长时间不回复，暂时Close Issue，如需要继续帮助请留言。

**Comment by gjp4tw** [comment]
@NaiboWang 我也遇到了這個問題，CHROME的版本是 114.0.5735.91

**Comment by NaiboWang** [comment]
> @NaiboWang 我也遇到了這個問題，CHROME的版本是 114.0.5735.91

手动打开Chrome会不会秒退？哪个版本的EasySpider，操作系统是什么，多少位？

**Comment by gjp4tw** [comment]
> > @NaiboWang 我也遇到了這個問題，CHROME的版本是 114.0.5735.91
> 
> 手动打开Chrome会不会秒退？哪个版本的EasySpider，操作系统是什么，多少位？

手動是可以打開的，EasySpider版本是0.3.2(Release裡面最新的)，系統是Windows10 64位元

**Comment by NaiboWang** [comment]
手动打开Chrome查看版本是114对吧？没有自动更新？
另外是软件直接秒退，还是说只是Chrome秒退？

**Comment by gjp4tw** [comment]
對，用resources裡面的chrome看版本是114，在版本那裡有出現An error occurred while checking for updates，這樣是有自動更新嗎？
閃退的是chrome，點擊純淨版或是帶有信息都會閃退

**Comment by NaiboWang** [comment]
试试下面几个解决方案，如果成功请回复：
1. 把软件目录换到C盘以外不带中文路径的文件夹，如直接放在D盘根目录下试试是否可以。
2. 重新下载0.3.2的Windows 64位版本试试。
3. 下载114版本的chromedriver并替换掉`EasySpider\resources\app\chrome_win64\chromedriver_win64.exe`然后重试：https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip

**Comment by gjp4tw** [comment]
以上方法都沒辦法，我自己在測試的時候出現這個錯誤 "An error occurred: Error: Timed out waiting for the WebDriver server at http://xxx.xxx.xxx.xxx:59385/"， 奇怪的是後面這個ip根本不是我的ip

**Comment by NaiboWang** [comment]
和IP应该无关，这个错误无法复现，我安装了虚拟机可以直接打开，你可以尝试在其他电脑打开或者虚拟机打开看行不行

**Comment by gjp4tw** [comment]
在其他電腦測試可以順利打開
