### ISSUE TITLE
编译执行时，网站打开为空白

### ISSUE THREAD

**Issue by think9326** [NaiboWang/EasySpider#241]
![20231128141846](https://github.com/NaiboWang/EasySpider/assets/106430150/1b47e680-4e8e-4c87-b7df-a156b27b92ba)
按照部署顺序，启动了spider，但是在执行Executestage里的python程序时，进不去网页

**Comment by NaiboWang** [comment]
打开网页操作传入的网址是什么，这问题一般和你自己的配置有关系。

**Comment by think9326** [comment]
传的是普通的网页，比如百度，知乎之类的

**Comment by NaiboWang** [comment]
如果是把任务文件直接放入我打包好的程序的tasks文件夹内，是否可以正常执行？
如果不可以，说明是任务文件的问题。

**Comment by think9326** [comment]
我把本地的task里的json文件放到官网已经打包好的easyspider里，运行发现能跑

**Comment by NaiboWang** [comment]
那就说明任务文件没问题，为什么编译不能运行我不清楚，问题无法复现，建议下载目前最新的源码，然后使用调试功能一步步来，尤其是OpenPage函数下面的操作，看看是否执行到了网页加载的命令。

**Comment by think9326** [comment]
好的，感谢大佬
