### ISSUE TITLE
你好,请问可不可以实现用两列数据(excel),一列是不同的网址,一列是要输入的不同网址对应的文本, 

### ISSUE THREAD

**Issue by rayfux3322** [NaiboWang/EasySpider#243]
比如第一列是5个不同的网址(但结构一样), 第二列是对应于5个网址要分别输入的5个不同的文本, 当打开第一个网址时,输入第一个文本,当打开每二个网址时输入第二个文本. 请问如何实现.

**Comment by NaiboWang** [comment]
可以，但需要使用自定义操作自己写一些Python代码，判断当前网址的索引，然后根据索引值对输入框传入不同的文本值。

这个需求比较特殊，直接用EasySpider会有一点麻烦，最好自己下载源码改代码实现定制需求。

**Comment by rayfux3322** [comment]
谢谢, 本人小白,不懂Python,不过我相信这种需求应该是普遍的, 等你这个大神有空了再更新一版新功能 .

**Comment by NaiboWang** [comment]
这功能并不普遍，普遍的是同一个网址输入不同的文本值，或者不同的网址输入同一个文本值，很少有不同的网址输入不同的文本值的需求，从代码实现来说复杂度会翻倍，因此不会更新此功能。
