### ISSUE TITLE
请问如何在“设计流程”执行任务以进行测试

### ISSUE THREAD

**Issue by hanuxxx** [NaiboWang/EasySpider#244]
看了教程后第一次使用本软件，初步完成了部分步骤，想测试一下。
保存后直接调用任务是能正常跑的。
但是我尝试去设计/修改任务，点击对应任务的修改任务，打开网页后就没有下一步反应了，后面的输入和点击操作都没有执行下去，我要怎么继续呢？
![image](https://github.com/NaiboWang/EasySpider/assets/23613751/3d0f3896-3550-42f8-8133-4aea3d9cbec9)

**Comment by NaiboWang** [comment]
本来就没有你说的测试功能，手动按照之前设计的步骤一步步来吧。

你说的这个功能下个版本会上线。
