### ISSUE TITLE
针对 iframe嵌套的网页不能采集

### ISSUE THREAD

**Issue by tewuapple** [NaiboWang/EasySpider#245]
网址：https://code.nhsa.gov.cn/search.html?sysflag=80
![企业微信截图_17014081099190](https://github.com/NaiboWang/EasySpider/assets/745401/732de80d-92b3-45fe-a724-db8599e08a97)
该网页有两个iframe，iframe嵌套一层，要采集的文本内容在第二层iframe里面，如图所示，右边框选中的那一部分，请问是不是哪里配置有误导致无法采集？

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。
