### ISSUE TITLE
多次按照视频教程均卡壳在【点击下一页元素】上面

### ISSUE THREAD

**Issue by LaoBaby815** [NaiboWang/EasySpider#248]
多次按照视频教程均卡壳在【点击下一页元素】上面，不能自动生成xpath，使用建议值在插件中都能够找到元素，但是执行任务的时候提示没有找到元素。包括完全填写了第一个视频中的xpath也是一样。求教！！！

**Comment by NaiboWang** [comment]
问题无法复现，把下面的文件放入你的tasks文件夹内，然后执行看看，我自己设计的任务流程。

[212.json](https://github.com/NaiboWang/EasySpider/files/13539889/212.json)

**Comment by NaiboWang** [comment]
可能是你的版本问题什么的，图1的选项是循环的参数；图2和图3是点击元素的参数配置，是不一样的，可以试试从头设计一个任务看看。

**Comment by LaoBaby815** [comment]
谢谢。上述问题已经解决。但是关于【任务计划】存在如下问题：在win10中按视频教程设置后，通过在powershell中（set-ExecutionPolicy RemoteSigned）后用powershell执行ps1文件（如图），没有任何问题，能够爬取数据。但是在win11中执行时，powershell界面一闪而过，并提示有问题（图二）。请问怎么处理？【通过（set-ExecutionPolicy Default）可以恢复原权限
![2023-12-05](https://github.com/NaiboWang/EasySpider/assets/152790917/40c9119e-be26-4664-8322-22d61eb8fa37)
】
![7A593E6C-233A-4e11-B9B1-CD7836FD0195](https://github.com/NaiboWang/EasySpider/assets/152790917/4b6d3322-cca8-497a-8246-a43f00c8ac38)

**Comment by NaiboWang** [comment]
这恐怕是你的Windows 11的Powershell版本太低等问题导致的，与软件本身无关，具体请多去网上查一下相关解决方案。
