### ISSUE TITLE
如何创建一个全局变量用来统计循环执行的次数？

### ISSUE THREAD

**Issue by Xiaozl11** [NaiboWang/EasySpider#249]
比如我创建的某个循环需要点击100个元素，但是我只想记录后20个元素的信息，也就是前80次循环我需要continue掉，我不知道如何创建一个全局变量来进行记录执行了几次。谢谢回答！

**Comment by NaiboWang** [comment]
使用自定义操作的exec操作定义变量，同时使用条件判断的eval选项和自定义操作的break操作或continue操作来实现你的需求，具体请参考文档中的exec和eval操作示例：https://github.com/NaiboWang/EasySpider/wiki/EXEC%E5%92%8CEVAL%E7%94%A8%E6%B3%95%E7%A4%BA%E4%BE%8B
