### ISSUE TITLE
网站页面爬不全

### ISSUE THREAD

**Issue by lichingyao** [NaiboWang/EasySpider#252]
网站：https://dianping.yiche.com/haiou/koubei/
流程：翻页操作，循环点击下一页
问题：只能翻到第6页，就结束了，没有报错，在第六页的时候有
--------Retrying----------

**Comment by NaiboWang** [comment]
这个网页设计的有点问题，解决方案为：将循环点击单个元素的最多执行循环次数由0改为固定次数如100以采集100页数据。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/de845bca-dd2b-4766-b158-3614d9ec9e90)

一周之后的0.6.0正式版将会彻底解决此问题。

**Comment by lichingyao** [comment]
好的感谢！我试了下100也不行也

**Comment by NaiboWang** [comment]
[210.json](https://github.com/NaiboWang/EasySpider/files/13683709/210.json)
导入并试试我设计的这个任务，多试几次。
