### ISSUE TITLE
对于rss地址，如xml文件地址该怎么处理？

### ISSUE THREAD

**Issue by kylinpoet** [NaiboWang/EasySpider#255]
比如这个地址：
https://www.chinanews.com.cn/rss/scroll-news.xml

**Comment by NaiboWang** [comment]
xml不支持可视化选择，但支持XPath提取，因此，使用方法为：

1. 按键盘F12打开开发者工具，然后点击选择按钮选中想要的元素：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/a27083d5-df38-4db8-97ab-001ee49c5f1b)

2. 定位到想要的元素后，右键选择复制XPath：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/e360002b-667a-4fdd-908b-77e8fd10311c)

3. 在EasySpider流程图界面左边拖动一个提取数据操作到流程图中：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/f68379a5-9ca9-473a-ab6e-dc43e1599749)

4. 添加一个字段：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/231dcf66-fe34-4b20-8923-67841d997db9)

5. 填入刚刚复制的XPath：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/a71318c8-0771-4712-9dc6-ff45d4734319)

即可提取对应字段信息。

循环提取数据的操作是类似的，不再赘述。
