### ISSUE TITLE
AGPL and commercial use restrictions

### ISSUE THREAD

**Issue by elliotwutingfeng** [NaiboWang/EasySpider#257]
Hello,

This project's readme states that it disallows commercial use, however, the GPL license family (which includes the AGPL that this project is licensed under) specifically [does not allow addition of restrictions](https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary) on use of the software. In fact, "any other added restriction can be removed by the user."

I would recommend the re-licensing of this project to a non-open source, [source-available](https://en.wikipedia.org/wiki/Source-available_software) license that disallows commercial use, or alternatively, consider removal of software use restrictions. Disclaimer: I am not a lawyer.

**Comment by NaiboWang** [comment]
Hi, do you know which license disallows commercial use? I cannot find one license that disallows commercial use but I want to set this restriction since this software has a patent and required to be charged for commercial use by my supervisor.

**Comment by elliotwutingfeng** [comment]
I'm sorry I don't have expertise on that, especially given that patents are involved, perhaps your university has IP legal advisors on this? All I know is that the AGPL is not suitable for this use case.

**Comment by NaiboWang** [comment]
Thank you very much and I will find a solution for this.
