### ISSUE TITLE
在数据写入模式中，添加第三种模式：自动重命名（如果文件已存在则自动重命名）

### ISSUE THREAD

**Issue by cat2123** [NaiboWang/EasySpider#258]
数据写入模式中，能不能加入第三种模式：自动重命名（如果文件已存在，则自动重命名）——下载的EXCEL/txt/CSV数据文件，既不追加写入，也不要覆盖写入

![1](https://github.com/NaiboWang/EasySpider/assets/58462832/f76439c2-89ca-49bd-b68e-03ae33e5caaf)

例如：
savedrecs
savedrecs (1)
savedrecs (2)
savedrecs (3)
savedrecs (4)

我在爬取WOS数据库时，程序本身没有爬取数据，但点击WOS数据库下载Excel文件时，EasySpider则不让chrome浏览器对重复excel文件进行自动重命名——我希望EasySpider不要干预chome对下载文件夹进行自动重命名。（如下两图）
![2](https://github.com/NaiboWang/EasySpider/assets/58462832/75e5804c-423e-4141-a99a-99cf34fb152c)
![3](https://github.com/NaiboWang/EasySpider/assets/58462832/0ed1895a-a51b-4ff9-911e-f1997d7f97bd)

**Comment by NaiboWang** [comment]
已了解需求，请关注后续版本更新。
