### ISSUE TITLE
自定义操作里加了一个数组，然后将提取的信息追加到数组中，需要怎么设置才能把这数组输出到excel中

### ISSUE THREAD

**Issue by alexyanghx** [NaiboWang/EasySpider#259]
预期一行4个字段 ，标题、作者、发布时间、内容导航(json结构)
我开始先提取了三个元素
![image](https://github.com/NaiboWang/EasySpider/assets/13973784/d33708f2-464c-4798-8d62-034cbf454ae7)
然后以python方式声明数组
![image](https://github.com/NaiboWang/EasySpider/assets/13973784/27a16e0f-245a-4f7f-b66f-b1208ab585a1)
循环导航信息，提取href和text然后以字典形式追加到前边声明的数组中
<img width="1100" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/13973784/b85ca355-c3be-4b9c-a7e3-876e2a7b9be4">
<img width="1038" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/13973784/e7a26336-4c3b-4d77-a469-7b8da2e05348">
最后想把数组保存到行中，不知道怎么操作？按我的想法搞会报错
![image](https://github.com/NaiboWang/EasySpider/assets/13973784/3858cbd9-d753-49b9-abba-4ac7d6004de6)
![image](https://github.com/NaiboWang/EasySpider/assets/13973784/ed04cb71-674e-4bf5-8227-5eb14c5d09a2)

请大佬指导

**Comment by NaiboWang** [comment]
`eval`操作不支持变量赋值：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/c55e0afe-0fdc-4a18-9d1d-d82283e8d157)

如果需要当做字段记录，直接在`eval`代码内写`json.dumps("self.content_catalog")`并在下方勾选`将执行后的输出/返回值作为字段记录：`即可：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/ddc17d8b-cbea-42fa-b8b2-57db2702e44d)
