### ISSUE TITLE
如何编译出符合自己本地环境的.sh文件（我的系统是manjaro）

### ISSUE THREAD

**Issue by knigth95** [NaiboWang/EasySpider#26]

**Comment by NaiboWang** [comment]
.sh只是脚本，如果指的是可在linux环境下运行的完整版，虽然我没用过manjaro，但按照Ubuntu的编译方式来说，主要是需要以下操作：
1. 保证Manjaro版本有可以运行的chrome版本，不然一切其余操作都做不到。
2. 最好有图形化界面GUI如Ubuntu的GNOME。
3. 能找到此系统版本能用的chromedriver：
https://chromedriver.chromium.org/downloads

同时满足后，请参照`ElectronJS`文件夹下的Readme文件的指示，将下载的chrome文件夹拷贝到`ElectronJS`文件夹内，然后按照教程去编译：

https://github.com/NaiboWang/EasySpider/tree/master/ElectronJS

同时最好测试一下nodejs输出的process.platform是不是“linux”，如果不是linux64位版本需要手动在`main.js`文件源码中以下添加另一个else if后添加自己的配置：

https://github.com/NaiboWang/EasySpider/blob/master/ElectronJS/main.js

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/14c200a3-9abd-4b28-8d7c-c886d733ba46)

配置好chromedriver，chrome的位置以及名字。
