### ISSUE TITLE
不定长，字段名不同的列表如何采集？能否用变量定义字段名？

### ISSUE THREAD

**Issue by Yuansheng-Liang** [NaiboWang/EasySpider#260]
假设有这样的一些列表，这些列表是同级的，但是字段名（有的字段不是每个列表都有）和数量不同：
列表1（3个字段）：
````
<div>
    <span>品牌：</span><span>111111111</span>
</div>
<div>
    <span>厂商：</span><span>2222222222</span>
</div>
<div>
    <span>价格：</span><span>3333333333</span>
</div>
````
列表2（4个字段）：
````
<div>
    <span>品牌：</span><span>111111111</span>
</div>
<div>
    <span>代工厂：</span><span>2222222222</span>
</div>
<div>
    <span>价格：</span><span>3333333333</span>
</div>
<div>
    <span>券后价：</span><span>444444444</span>
</div>
````
列表3（5个字段）：
````
<div>
    <span>品牌：</span><span>111111111</span>
</div>
<div>
    <span>代工厂：</span><span>2222222222</span>
</div>
<div>
    <span>价格：</span><span>3333333333</span>
</div>
<div>
    <span>特点：</span><span>1111，222，333</span>
</div>
<div>
    <span>活动：</span><span>百亿补贴，双旦优惠，优惠券</span>
</div>
````

---

希望：每个div中的类型（比如“品牌”，“价格”）作为字段名，其余作为字段的值，并且每个列表输出为一条数据。
请问如何采集数据？

**Comment by Yuansheng-Liang** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/54231251/556d94dd-5f4d-4332-97ea-a96d05c5a1ca)
大概是这样的效果，不知道可不可行

**Comment by NaiboWang** [comment]
我能想到的方法，在不定长的情况下，至少要确定好一共有几个字段，比如最多5个，就设置5个字段名称`品牌`，`代工厂`，`价格`，`特点`，`活动`。然后使用循环配合条件判断来做，具体步骤为：

1. 添加循环，循环类型为不固定元素列表，值为`//div`。
2. 在循环内部添加条件判断，添加5个条件分支，每个条件分支的条件均设置为`当前循环项包含文本`，不同条件分支的条件设置为包含的不同的文本类型，如第一个条件分支的条件为当前循环项包含`品牌`，以此类推。‘’
3. 在各个条件分支内部，各添加一个提取数据操作，提取数据操作的字段名称为对应字段的名称，如第一个条件分支内提取数据操作的字段名称即为`品牌`，XPATH勾选`使用相对循环内的XPATH`，XPath值为`//span[2]`来提取第二个span内的数据，以此类推。
4. 取消勾选所有提取数据操作的`此提取数据操作后生成新数据行`选项。
5. 在循环最后添加自定义操作，类型为`eval`，值为"页面已完成采集"，并设置`是否将执行后的输出/返回值作为字段记录`为`是`用来接受之前的字段值。

示例任务文件：[314.json](https://github.com/NaiboWang/EasySpider/files/13793232/314.json)

可以直接导入上面的任务参考怎么设计。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/b36e6066-13c7-4756-ad43-0d9c1c9f9985)
