### ISSUE TITLE
IllegalCharacterError

### ISSUE THREAD

**Issue by ND-LJQ** [NaiboWang/EasySpider#261]
采集数据存入excel中会出现IllegalCharacterError非法字符报错,是否能将其except
![image](https://github.com/NaiboWang/EasySpider/assets/77595446/8b425fe9-9f02-46fe-b1eb-1acbf5b7fbf4)

**Comment by NaiboWang** [comment]
已注意到此问题，将在下个版本修复，请先尝试使用CSV格式存储数据。
同时能否告知IllegalCharacter是什么，方便Debug。

**Comment by ND-LJQ** [comment]
????????????&quot;????????????????????&quot;????????????19????????????????????????????,?????,??,???????????,????????,??????????,????????,????????????????????????????????,,????????&quot;?????????????????   这是我碰到的数据格式,手动复制到excel能正常存储,是不是能用xlsxwriter库在写入excel时自动去除非法字符呢,或者遇到非法字符即跳过该记录(try except),而不是在0.5版本中直接报错弹出,和0.6版本中报错不停止,但不能正确存入数据

**Comment by NaiboWang** [comment]
最好的方式还是直接转成CSV存储，去除非法字符比较难做因为我并不清楚哪些内容才是非法字符；最多可以该成跳过带有非法字符的记录。

**Comment by ND-LJQ** [comment]
似乎出现了这样一种情况,我同时执行多个任务时,有时某个任务按P暂停,所有都会暂停

**Comment by NaiboWang** [comment]
是这样的，所以在保存任务选项中才允许修改暂停键，不同的任务使用不同的暂停键即可，或者通过命令行传参改变暂停键。

**Comment by ND-LJQ** [comment]
明白了,麻烦了☺️
