### ISSUE TITLE
有没有操作能够自动结束整个爬虫程序？或者能否在“自定义操作”中添加这个功能？

### ISSUE THREAD

**Issue by Yuansheng-Liang** [NaiboWang/EasySpider#262]
我目前的需求是这样的：

循环中如果遇到某个元素包含指定文本时直接退出程序。

---
目前好像没有发现能直接退出程序的方法，倒是“自定义操作”中有暂停的方法。

**Comment by NaiboWang** [comment]
添加自定义操作，类型为执行Python代码的`exec`选项，代码为：

```Python
self.browser.quit()
os._exit(0)
```

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/2348db6d-a4a2-4497-b6ef-e05dae45c08b)

**Comment by Yuansheng-Liang** [comment]
> 添加自定义操作，类型为执行Python代码的`exec`选项，代码为：
> 
> ```python
> self.browser.quit()
> os._exit(0)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/30287768/293460971-2348db6d-a4a2-4497-b6ef-e05dae45c08b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NTUzMzQsIm5iZiI6MTcwMzk1NTAzNCwicGF0aCI6Ii8zMDI4Nzc2OC8yOTM0NjA5NzEtMjM0OGRiNmQtYTRhMi00NDk3LWI2ZWYtZTA1ZGFlNDVjMDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE2NTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YWNlMjE4ZWFjODNlYjU4ODNmZGM5NTEwZmM1NDEyZjY4MDllNGQ1NWQyODc4OTNkZjI5NDlhYjI4ZmU4OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e3Gg_6Z8Pz1F-V-p29MxnmgecbMfzLNaUkhqsfvsPvw)

刚才试了一下，这样操作确实退出了，单数采集到的数据并没有得到保存

**Comment by NaiboWang** [comment]
再加一行self.saveData():

```python
self.saveData()
self.browser.quit()
os._exit(0)
```
