### ISSUE TITLE
不知道哪里设置错了。

### ISSUE THREAD

**Issue by dcba2008cn** [NaiboWang/EasySpider#263]
![1703949423615](https://github.com/NaiboWang/EasySpider/assets/154570368/5e4ad0ca-ee8a-45e1-99a3-72a8d0a2cc4a)
请看图片，我想采集yahoo、的新闻。设置 了打开网页-》循环（滚到底部，2次）-》【点击链接-》采集标题和正文】
实际只采集到4.5篇，好像滚动2次在程序运行的最后，滚动2次就退出程序了

**Comment by NaiboWang** [comment]
如果想要打开网页之后先滚动，就在打开网页操作中设置滚动，而不是循环操作设置滚动，即你给的图片的右侧设置滚动。
