### ISSUE TITLE
想爬取药品监督管理局药品审评中心受理品种目录，无法定位到年度元素

### ISSUE THREAD

**Issue by LSDnewcomer** [NaiboWang/EasySpider#264]
求助， 想要爬取药品监督管理局药品审评中心受理品种目录https://www.cde.org.cn/main/xxgk/listpage/9f9c74c73e0f8f56a8bfbc646055026d
中2023年度，药品类型：生物制品；申请类型：新药 的所有列表数据。
年度选项这一直无法定位到2023不知道是什么问题，能帮忙看下 xpath吗

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。
