### ISSUE TITLE
ocr型验证码

### ISSUE THREAD

**Issue by simonccccc** [NaiboWang/EasySpider#266]
我需要多次输入ocr型的验证码，请问应该怎么做？
<img width="505" alt="Screenshot 2024-01-05 at 11 02 47 AM" src="https://github.com/NaiboWang/EasySpider/assets/40349214/07981cb4-ef9e-44c7-8b0c-72ad0d31d925">

**Comment by NaiboWang** [comment]
浏览器选中验证码图片 -> 采集该图片的地址 -> 确认采集 -> 在流程图中更改`采集内容类型`为`OCR识别文字` -> 修改字段名为`参数1_图片` -> 在`输入文字`操作的`输入值`框里用`Field["参数1_图片"]`来表示字段值即可。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/4059dee2-71a1-4f3f-9091-2e5cba4364d2)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/c0e47cff-6f95-4cb3-9fbd-b5ac381f38b3)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/d241e10d-7990-4c19-94da-226d9945a170)

如果不想保存OCR识别结果，可以将`是否保存该字段`设置为`否`：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/ce0ae544-7ce5-4127-b13a-3b09953e3614)

更多细节请看这期视频：https://www.bilibili.com/video/BV1kF411R7VJ

**Comment by tw202415** [comment]
你好我想詢問一下，假設https://portal.sw.nat.gov.tw/APGQ/LoginFree?request_locale=zh_TW&breadCrumbs=JTdCJTIyYnJlYWRDcnVtYnMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIyJUU1JTg1JThEJUU4JUFEJTg5JUU2JTlGJUE1JUU4JUE5JUEyJUU2JTlDJThEJUU1JThCJTk5JTIyJTJDJTIydXJsJTIyJTNBJTIyJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMiVFOSU4MCVCMiVFNSU4RiVBMyVFOSU4MCU5QSVFOSU5NyU5QyVFNiVCNSU4MSVFNyVBOCU4QiUyMiUyQyUyMnVybCUyMiUzQSUyMmNoYW5nZU1lbnVVcmwyKCclRTklODAlQjIlRTUlOEYlQTMlRTklODAlOUElRTklOTclOUMlRTYlQjUlODElRTclQTglOEInJTJDJ0FQR1FfMicpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMihHQzMyMCklRTclQTklQkElRTklODElOEIlRTklODAlQjIlRTUlOEYlQTMlRTUlQkYlQUIlRTklODElOUUlRTglQjIlQTglRTclODklQTklRTclQTglODUlRTglQjIlQkIlRTclQjklQjMlRTclQjQlOEQlRTglQUQlODklRTYlOTglOEUlRTUlOEYlOEElRTclQTglODUlRTUlOTYlQUUlRTYlOUYlQTUlRTglQTklQTIlRTQlQjglOEIlRTglQkMlODklMjIlMkMlMjJ1cmwlMjIlM0ElMjJvcGVuTWVudSgnJTJGQVBHUSUyRkdDMzIwJyklMjIlN0QlMkMlN0IlN0QlMkMlN0IlN0QlNUQlMkMlMjJwYXRoVXJsJTIyJTNBJTIyJTIzTUVOVV9BUEdRJTJDJTIzTUVOVV9BUEdRXzIlMkMlMkZBUEdRJTJGR0MzMjAlMjIlN0Q=
這個網址內的驗證碼，他是會用time去亂數跳，我該怎麼擷取?
