### ISSUE TITLE
点击 纯净版浏览器设计 没有反应

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#267]
点击 纯净版浏览器设计 没有反应

_Originally posted by @wangwangxingao in https://github.com/NaiboWang/EasySpider/issues/100#issuecomment-1878855958_

请提供更多信息，比如从哪里下载的，什么系统，系统和软件版本号等。

**Comment by wangwangxingao** [comment]
> 点击 纯净版浏览器设计 没有反应
> 
> _Originally posted by @wangwangxingao in [#100 (comment)](https://github.com/NaiboWang/EasySpider/issues/100#issuecomment-1878855958)_
> 
> 请提供更多信息，比如从哪里下载的，什么系统，系统和软件版本号等。

在github上（这里）下载的，win11的系统，点击后可以看见有白色框闪一下，然后就消失了。其他几个也一样。

**Comment by NaiboWang** [comment]
Github Releases页面的x64版本，压缩包.7z大小300MB左右，解压后整个文件夹1GB左右对吗？

**Comment by NaiboWang** [comment]
进入`EasySpider\resources\app\chrome_win64`文件夹内，双击`chrome.exe`看chrome浏览器是否可以正常打开，如果可以，看版本号是多少，0.6.0应该使用120版本的chrome浏览器，同时双击打开文件夹下的`chromedriver_win64.exe`，看是否第一行显示的是Starting ChromeDriver 120.0.6...类似这样的信息。

**Comment by sanqiTX** [comment]
> 进入`EasySpider\resources\app\chrome_win64`文件夹内，双击`chrome.exe`看chrome浏览器是否可以正常打开，如果可以，看版本号是多少，0.6.0应该使用120版本的chrome浏览器，同时双击打开文件夹下的`chromedriver_win64.exe`，看是否第一行显示的是Starting ChromeDriver 120.0.6...类似这样的信息。

我Windows11也碰到这个问题了，一样的是在GitHub下载0.6版本的，双击chrome.exe后chrome浏览器打不开，chromedriver_win64.exe操作提示的是126版本的。然后重新换了0.5版本的，发现还是一样打不开chrome，这次自带的是115版本的，大佬有什么办法解决吗？
