### ISSUE TITLE
Xpath匹配结果在插件中和在设计器中不一样

### ISSUE THREAD

**Issue by thundersword** [NaiboWang/EasySpider#269]
![微信图片_20240107152610](https://github.com/NaiboWang/EasySpider/assets/23026566/d644053c-a299-4c61-83cb-0ef8cab9ee26)
如图，我现在要匹配这个列表进行采集，xpath为//div[starts-with(@class, 'index-module__goodItemWrapper___')]。
出现的问题是设计器提示是匹配到两个元素，而在xpath插件中是匹配到20个，也正是我想要的结果。
尝试了其他xpath写法，还是一样，“查看其它可能的xpath写法”中内容是空的。
再次请教，这种情况如何处理？

**Comment by NaiboWang** [comment]
设计器用的默认XPath绝对不是`//div[starts-with(@Class, 'index-module__goodItemWrapper___')]`，你可以点击采集数据等操作之后，把自动生成的XPath改为`//div[starts-with(@Class, 'index-module__goodItemWrapper___')]`，然后重新点击比如`提取数据`节点，就会重新标记为你定义的XPath对应的节点了。

**Comment by thundersword** [comment]
是的，我没有用设计器默认的XPath，因为用设计器的时候不论我怎么选择，都无法自动识别到同类元素，没有办法，我自己写了几个XPath

**Comment by thundersword** [comment]
又看了一遍，是我操作的问题，不能自动识别的时候，可以手动去选择同类。
