### ISSUE TITLE
想说可以docker部署嘛（另外想问问如何部署web版）

### ISSUE THREAD

**Issue by knigth95** [NaiboWang/EasySpider#27]
服务器ubuntu 
架构arm

**Comment by NaiboWang** [comment]
可以设置docker，但我没有制作docker镜像，因为软件开始的定义是Easy，面向用户群不是会用docker的专业人士=_=

如果要在arm架构的ubuntu系统运行程序，至少需要满足以下条件：

1. 保证arm版本的Ubuntu有可以运行的chrome版本。
2. 最好有图形化界面GUI如Ubuntu的GNOME。
3. 能找到此系统版本能用的chromedriver：
https://launchpad.net/ubuntu/focal/arm64/chromium-chromedriver

参照此issue的回答去编译：
https://github.com/NaiboWang/EasySpider/issues/26

当然，另一种方案是，可以在个人电脑，如Windows x64系统上把任务设计好，然后把`tasks`文件夹内生成的`.json`配置文件拷贝到arm芯片的ubuntu内的`tasks`文件夹，内让其负责执行任务，此时只需要编译个执行阶段的程序就行了，编译方式很简单，参考：

https://github.com/NaiboWang/EasySpider/tree/master/ExecuteStage

执行的时候使用命令行执行，如MacOS下的命令行：

```
./easyspider_executestage --id 17 --user_data 1 --read_type local --config_folder "/Users/naibowang/Library/Application Support/EasySpider/"
```

`id`为tasks文件夹下的json文件的名称。

**Comment by NaiboWang** [comment]
此外 Web版本什么意思还请解释下

**Comment by MushR00m** [comment]
> 此外 Web版本什么意思还请解释下

我想应该是能否部署在Docker后通过Web浏览器打开来使用，我也想问这个问题哈哈，大佬有没有考虑过适配下

**Comment by NaiboWang** [comment]
最开始开发的目的是“Easy”是想让许多没有代码基础的人可以打开即用的，没想到会有许多会用Linux，甚至会用Docker的人来用，以后可以做一个docker镜像，很简单，因为程序本身就是自己建立了一个Web浏览器。
你下载好Linux版本的程序打开以后，其他机器就可以通过http://IP地址:8074来访问服务器，通过修改`config.json`里的服务器配置可以修改端口号和云服务器地址。
至于直接远程调用和docker镜像，将列入下一阶段开发计划，估计在一个月内会上线。

**Comment by raining1123** [comment]
期待2024年能把这个坑填上哈哈哈哈
一直想找一款huginn的国产替代品
