### ISSUE TITLE
Mac m系列设计完美但执行时报错

### ISSUE THREAD

**Issue by zhl19970919** [NaiboWang/EasySpider#270]
Traceback (most recent call last):
  File "easyspider_executestage.py", line 50, in <module>
ModuleNotFoundError: No module named 'ddddocr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "easyspider_executestage.py", line 54, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-15: ordinal not in range(128)
[4912] Failed to execute script 'easyspider_executestage' due to unhandled exception!

**Comment by zhl19970919** [comment]
<img width="1214" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/33246547/afa8ecd8-7810-4ff4-8471-6e39453e392d">

**Comment by NaiboWang** [comment]
请提供电脑型号，操作系统版本，M几芯片等信息，我晚上会用另外一台电脑再试一下。

**Comment by NaiboWang** [comment]
另外可以试一下0.5.0版本能不能用

**Comment by zhl19970919** [comment]
> 请提供电脑型号，操作系统版本，M几芯片等信息，我晚上会用另外一台电脑再试一下。

型号：Macbook Pro14寸 21 年
芯片：m1pro 
操作系统：14.2.1 (23C71)

**Comment by NaiboWang** [comment]
你先试试0.5.0能不能用，晚上我看看0.6.0

**Comment by NaiboWang** [comment]
> > 请提供电脑型号，操作系统版本，M几芯片等信息，我晚上会用另外一台电脑再试一下。
> 
> 型号：Macbook Pro14寸 21 年 芯片：m1pro 操作系统：14.2.1 (23C71)

找了个你的同款，运行没有问题，问题无法复现，是否下载的位置不对？是在哪里下载的软件，软件下载压缩包为700+MB，建议从Github或123网盘重新下载一份试试。
