### ISSUE TITLE
请问下设置的循环点击下一页，为什么到第二页采集完就结束了，流程图如下

### ISSUE THREAD

**Issue by luoyuyimeng** [NaiboWang/EasySpider#272]
按照这个csdn链接操作的：https://blog.csdn.net/ihero/article/details/130805504
![微信截图_20240109165419](https://github.com/NaiboWang/EasySpider/assets/86345149/14c99fec-1d84-4f7b-9963-721deaa7dac7)

![微信截图_20240109165006](https://github.com/NaiboWang/EasySpider/assets/86345149/168a73fe-5e69-4cba-9488-e95a6c09343e)

**Comment by NaiboWang** [comment]
这文章不是我写的，而且你采集的内容似乎有iframe，需要仔细看文档和视频教程怎么处理这种情况，把软件自带的案例文件都研究一下，实在不行加QQ群问，这种具体需求我不会做详细讲解。

**Comment by luoyuyimeng** [comment]
谢谢您的回答，不是iframe，图片截错了哈，刚才群里问了，等解答中
![111](https://github.com/NaiboWang/EasySpider/assets/86345149/ea807243-6916-43ec-85bd-ae098e835dc5)

**Comment by luoyuyimeng** [comment]
> 这文章不是我写的，而且你采集的内容似乎有iframe，需要仔细看文档和视频教程怎么处理这种情况，把软件自带的案例文件都研究一下，实在不行加QQ群问，这种具体需求我不会做详细讲解。

是不是xpath需要加标签定位呢

**Comment by NaiboWang** [comment]
我不清楚你说的加标签定位是什么意思，不过建议多看看视频和文档，有些问题自然会解决。

**Comment by luoyuyimeng** [comment]
> 我不清楚你说的加标签定位是什么意思，不过建议多看看视频和文档，有些问题自然会解决。

谢谢解答，已经解决了

**Comment by NaiboWang** [comment]
能分享一下是怎么解决的吗？有利于其他朋友调试。

**Comment by luoyuyimeng** [comment]
看视频解决的

**Comment by NaiboWang** [comment]
OK
