### ISSUE TITLE
为什么执行任务后data文件夹里没有任何东西

### ISSUE THREAD

**Issue by LSDnewcomer** [NaiboWang/EasySpider#277]
执行的测试任务，但data文件夹里是空的。不知道是什么问题
（之前电脑下载过几版easyspider都用360清理干净了）

**Comment by LSDnewcomer** [comment]
<img width="575" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/155427093/959daa63-0250-4eb9-a4ee-bb16a8912a59">
<img width="500" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/155427093/c107d924-00bf-4cd0-b606-cfb69bd6e0ab">

**Comment by NaiboWang** [comment]
自己设计一个简单任务执行一下，同时把执行过程中的截图贴一下。
另外，这种绿色软件不需要用360清理。

**Comment by NaiboWang** [comment]
只从你发的截图看不出来任何问题，建议多等待一段时间，或者鼠标点击一下命令行界面后按一下回车看看有没有后续反应。
