### ISSUE TITLE
请教有多层xpath嵌套的图片地址应该怎么选中循环采集？

### ISSUE THREAD

**Issue by Hawkrain244263** [NaiboWang/EasySpider#278]
https://mcbcollection.com/natan-altman

**Comment by NaiboWang** [comment]
和文本采集时批量选中方法相同，如果没有选中完全就继续手动选择，根据情况修改XPath值，然后将节点类型改为`图片地址`，具体如何设计不做详细答疑，请学习XPath相关教程。
