### ISSUE TITLE
点击执行任务按钮时出现报错

### ISSUE THREAD

**Issue by FarAway2726** [NaiboWang/EasySpider#279]
刚装好软件，尝试执行任务时弹出窗口提示如下报错，找不到可执行文件，安装版本是[EasySpider_0.6.0_windows_x64.7z]。 谢谢！
![error](https://github.com/NaiboWang/EasySpider/assets/69225342/e3206230-8c5f-4150-b7fd-c2b8ed7d9f0c)

**Comment by FarAway2726** [comment]
补充： 安装版本是[EasySpider_0.6.0_windows_x64.7z]

**Comment by NaiboWang** [comment]
尝试以下两个方案：

1、尝试使用命令行执行看是否可以执行。
2、检查目录下`EasySpider\resources\app\chrome_win64`文件夹内是否存在`easyspider_executestage.exe`文件。

**Comment by FarAway2726** [comment]
重新装了一个version5的现在可以运行了，谢谢！
