### ISSUE TITLE
点击带用户运行后谷歌浏览，并不是bate版谷歌浏览器

### ISSUE THREAD

**Issue by GIEYang** [NaiboWang/EasySpider#285]
版本： 0.5.0
问题：
 点击带用户运行后谷歌浏览，并不是bate版谷歌浏览器，如下图

导致：不能加载出网站信息
执行脚本如下：
![image](https://github.com/NaiboWang/EasySpider/assets/68678655/61f89c88-aace-4fcd-b6d2-04567a385e78)

已在保存的时候选择是否为极端反爬，如下图
![image](https://github.com/NaiboWang/EasySpider/assets/68678655/0d038e05-20a6-4ed3-b447-87a4aa5d2735)

![image](https://github.com/NaiboWang/EasySpider/assets/68678655/40aff96b-4807-4b45-9f57-ee7f156d03a5)

**Comment by NaiboWang** [comment]
如果是要过Cloudflare，由于Cloudflare反爬技术的更新，目前版本已不支持，一直和Cloudflare斗智斗勇很耗费时间和精力，因此建议使用其他RPA软件对Cloudflare相关网站进行处理。
Beta浏览器已失去作用，因此再纠结这个问题意义不大。
