### ISSUE TITLE
如何爬取滑块验证码的网站

### ISSUE THREAD

**Issue by yulongMao** [NaiboWang/EasySpider#287]

**Comment by NaiboWang** [comment]
不同网站的验证码格式不同，因此需要的处理技术不同，没有统一的解决方案，可以自己尝试寻找有没有适合你的网站的滑块验证码的处理插件，类似这种：https://github.com/NoahCardoza/CaptchaHarvester

实在不行就只能通过插件的方式通过Python代码自己写一段适合自己网站的验证码处理模块。

或者自定义操作设置程序暂停/长按p键暂停，然后手动处理验证码。
