### ISSUE TITLE
如何取消点击鼠标左键就会选择元素

### ISSUE THREAD

**Issue by Kongmu2019** [NaiboWang/EasySpider#289]
设计任务的时候，第一次会出现登录界面，然后输入用户名密码后就不会出现登录界面了，可是用鼠标点击输入框却自动添加了任务，请问下该怎么操作？怎么取消左键也能选择元素的功能呢？或者说怎么删除锚点后面的任务节点？希望给出解答，谢谢

**Comment by NaiboWang** [comment]
右键选择操作，双击删除操作即可删除对应流程。
