### ISSUE TITLE
元素识别不了，原因在于元素在iframe标签内，如何处理

### ISSUE THREAD

**Issue by ZbyGsf** [NaiboWang/EasySpider#29]
![微信图片_20230514110733](https://github.com/NaiboWang/EasySpider/assets/76163449/a27262f2-65c1-4ae7-80aa-317f01193dec)
上图绿框中的元素能识别，红框中的元素识别不了，无法选中。想问问博主是什么情况

**Comment by NaiboWang** [comment]
先按键盘F12打开审查元素，然后点击以下按钮选择你页面中的红框中的区域，把对应的源码发我，我看下他是怎么写的网页：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/435cc424-9b93-4149-9e49-55fdde196c4a)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/8dcdd768-b12f-43ec-a44d-f793a1c683bd)

**Comment by ZbyGsf** [comment]
以上是下拉按钮、勾选框、文本三个部分的对应源码，还麻烦过目。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NaiboWang/EasySpider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月14日(星期天) 中午12:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NaiboWang/EasySpider] 元素识别不了，因为是纯小白，所以想请教一下大家能不能解决，怎么解决 (Issue #29)





 
先按键盘F12打开审查元素，然后点击以下按钮选择你页面中的红框中的区域，把对应的源码发我，我看下他是怎么写的网页：

**Comment by NaiboWang** [comment]
没看到源码……是不是忘发了

**Comment by ZbyGsf** [comment]
![福建](https://github.com/NaiboWang/EasySpider/assets/76163449/4dfe850d-df41-4e60-9474-db7c159aeafe)
![勾选框](https://github.com/NaiboWang/EasySpider/assets/76163449/651ecfd5-09be-4898-bf03-cc675d9a1651)
![箭头](https://github.com/NaiboWang/EasySpider/assets/76163449/2596d341-3314-4094-9650-e41bca9de5bc)
以上三张截图，不知道刚刚什么情况没发出来，，，，，

**Comment by NaiboWang** [comment]
最后一张图往上翻 看有没有一个iframe标签 截图给我

**Comment by ZbyGsf** [comment]
![微信截图_20230514132059](https://github.com/NaiboWang/EasySpider/assets/76163449/8f291857-8440-44fb-b254-732e57417f39)
有一个iframe的标签，箭头指着的地方

**Comment by NaiboWang** [comment]
右键复制src链接地址，直接粘贴到地址栏访问 看看是什么样子

**Comment by ZbyGsf** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/76163449/afe56da7-72f2-42e3-be15-610d59061133)
copy link address ,然后在新标签中打开，就变成了登录界面。登陆后回到了主界面

**Comment by NaiboWang** [comment]
link address是不是183.252.50.208:442/vms/historypic？不是的话发一下实际的链接，然后如果登录后回到主界面再次在浏览器中输入link address会出现什么？

**Comment by ZbyGsf** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/76163449/9c206c2b-56e5-4b37-9c65-88230d19650b)
link address的地址是183.252.50.208:442/vms/historypic，会出现上图页面，刚刚的操作似乎有点失误。

**Comment by NaiboWang** [comment]
直接在创建任务的时候将地址设置为：https://183.252.50.208:442/vms/historypic
然后试试？
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/d41f7709-bf08-47e9-ac85-42fa7da397c8)

**Comment by ZbyGsf** [comment]
创建任务的时候将地址设置为：https://183.252.50.208:442/vms/historypic 。会提示没有访问权限“The HTTP request is not acceptable for the requested resource”

**Comment by NaiboWang** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/a3f12861-bbd5-4308-b70d-59261fbad10d)

你这个网址是什么，直接拷贝到创建任务的URL地址栏中去创建试试，是不是以http开头不是https？

因为我无法访问你的网站，也没法给你直接调试……

另外你爬的不是什么政府军工之类的网站吧，我只是提供工具，不对工具使用后果负责的=_=

**Comment by NaiboWang** [comment]
以下是解决方案，iframe问题会在下个版本专门处理：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/5aff9e37-5bd5-44e9-a33c-41a50ea87fc3)
