### ISSUE TITLE
爬取下载链接的问题？

### ISSUE THREAD

**Issue by kuhubmk** [NaiboWang/EasySpider#290]
https://www.gamer520.com/
这是一个游戏资源网，它资源也是爬来的。所以他是懂爬虫的，目前遇到几个问题不知道怎么操作了。
1，它会时不时跳出一句话“不要爬我了”来中断网站。
2，然后随机进入嫌弃页会跳出一个窗口来屏蔽网页。
3，下载链接有明文提示的密码，这个可以用提取再输入解决。
4，下载链接2次跳转，右上角点击下载，从中间再跳出一个立即下载，然后点击中间立即下载再跳到一个新页面，再输入前面提取的到密码输入，点击确认才得到网盘下载链接。
这一套组合拳我有点蒙了，有没有大神遇到过这种问题！

**Comment by NaiboWang** [comment]
具体需求问题请仔细看教程根据不同场景来设置不同配置，这里不做具体答疑。
