### ISSUE TITLE
OSError: Path to the extension doesn't exist 报错

### ISSUE THREAD

**Issue by chenghaowuchris** [NaiboWang/EasySpider#292]
darwin ('64bit', '')
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2222, in <module>
  File "selenium/webdriver/chromium/options.py", line 101, in add_extension
OSError: Path to the extension doesn't exist
[4207] Failed to execute script 'easyspider_executestage' due to unhandled exception!

请问如何解决这个报错呢？ 感谢

**Comment by NaiboWang** [comment]
macos系统下下载软件后运行报的错误，还是下载代码自己编译时报的错误？

**Comment by chenghaowuchris** [comment]
> macos系统下下载软件后运行报的错误，还是下载代码自己编译时报的错误？

是MacOS 13.61 下载软件后生成脚本 在easyspider_excutestage_full 运行时的报错

**Comment by NaiboWang** [comment]
easyspider_excutestage_full应该和EasySpider.app处于同一个文件夹，是否移动了位置？可以放下文件夹和程序执行截图。

**Comment by NaiboWang** [comment]
你没有按照说明执行，第一步要先cd到此文件夹，第二步再./easyspider_executestage_full来执行命令。

**Comment by chenghaowuchris** [comment]
<img width="1789" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/152651846/9701117a-8f69-43f3-95ea-b3fe48b1787c">
你好， 还是一样的报错

**Comment by NaiboWang** [comment]
./easyspider_executestage是否能正常执行？

**Comment by chenghaowuchris** [comment]
是i ntel 2.6 GHz 6-Core Intel Core i7,主程序可以正常打开， ./easyspider_executestage执行后会报错
<img width="237" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/152651846/054aa04b-2bfd-42c9-9c20-6b85f2dd7c3d">
<img width="1753" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/152651846/f3751861-9ad1-4b14-bb76-1175dec9de96">

**Comment by NaiboWang** [comment]
EasySpider.app/Contents/Resources/app/XPathHelper.crx文件是否存在？是在什么渠道下载的？
可以通过右键EasySpider.app -> 显示包内容查看。

**Comment by chenghaowuchris** [comment]
<img width="1649" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/152651846/f747649b-26fd-4ac6-94d5-5dc7f48e06f5">
是存在的， 通过https://www.easyspider.cn/index_english.html 下载的

**Comment by NaiboWang** [comment]
你先cd /Users/.../EasySpider_MacOS敲回车，然后使用pwd命令敲回车确认已经在这个文件夹内部了，再./easyspider_executestage，全称截图下来看看。

**Comment by chenghaowuchris** [comment]
<img width="1792" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/152651846/8112d418-6b34-40bb-a34f-9d449e085445">
貌似解决了，但是亚马逊好像有个验证弹窗导致爬不到数据，but it is another story

**Comment by NaiboWang** [comment]
OK，问题就是之前仍然没有切换到目录，cd敲回车之后就行了。
