### ISSUE TITLE
如何获取输入的内容？

### ISSUE THREAD

**Issue by safferw** [NaiboWang/EasySpider#293]
如何获取输入的内容？例如：需要在某东搜索手机类别，爬取后，需要在结果中标明类别是手机。如何设置

**Comment by NaiboWang** [comment]
浏览器选中搜索框，点击提取该文本框的内容为提取数据操作增加一个字段即可。

**Comment by Pinkolinka11** [comment]
515525/525515

Dne ne 4. 2. 2024 1:16 uživatel Naibo Wang ***@***.***>
napsal:

**Comment by Pinkolinka11** [comment]
515525

Dne ne 4. 2. 2024 2:34 uživatel Kamila Sablaturova ***@***.***>
napsal:

**Comment by Pinkolinka11** [comment]
515525

Dne ne 4. 2. 2024 2:42 uživatel Kamila Sablaturova ***@***.***>
napsal:

**Comment by Pinkolinka11** [comment]
515525

Dne ne 4. 2. 2024 2:42 uživatel Kamila Sablaturova ***@***.***>
napsal:

**Comment by Pinkolinka11** [comment]
515525

Dne ne 4. 2. 2024 2:43 uživatel Kamila Sablaturova ***@***.***>
napsal:

**Comment by Pinkolinka11** [comment]
515525

Dne ne 4. 2. 2024 2:43 uživatel Kamila Sablaturova ***@***.***>
napsal:

**Comment by Pinkolinka11** [comment]
515525

Dne ne 4. 2. 2024 2:43 uživatel Kamila Sablaturova ***@***.***>
napsal:
