### ISSUE TITLE
树形结构的数据如何采集？

### ISSUE THREAD

**Issue by yulongMao** [NaiboWang/EasySpider#294]
要求在采集的excel表格中显示出层级关系
如图有此网页：
![image](https://github.com/NaiboWang/EasySpider/assets/157663998/8d8bd8aa-e737-4c9e-8dee-f8d40b683da4)
采集该网页数据需在excel表格中生成以下数据
![image](https://github.com/NaiboWang/EasySpider/assets/157663998/16d2d7ac-8bee-4991-b563-641a67d787f7)

如何用软件操作？

**Comment by yulongMao** [comment]
就这种数据怎么爬？要求用excel表格展示层级关系
![image](https://github.com/NaiboWang/EasySpider/assets/157663998/14b61294-7831-4920-85cf-e2afc7ed18fe)

**Comment by NaiboWang** [comment]
最多有几个子列表，就去循环嵌套几个循环，然后使用下面自定义变量的形式，动态修改每个子循环的XPath：

https://github.com/NaiboWang/EasySpider/wiki/%E6%97%A0%E4%B8%8B%E4%B8%80%E9%A1%B5%E6%8C%89%E9%92%AE%E5%8F%AA%E6%9C%89%E5%85%B7%E4%BD%93%E9%A1%B5%E9%9D%A2%E6%8C%89%E9%92%AE%E6%97%B6%E7%9A%84%E7%BF%BB%E9%A1%B5%E6%96%B9%E6%B3%95%EF%BC%88EXEC%E5%92%8CEVAL%E6%95%99%E7%A8%8B%EF%BC%89

如自定义两个变量`self.a`和`self.b`，分别负责爷爷元素和父元素的循环，爷爷元素循环的XPath设置为`/div[eval("self.a")]`，父元素元素的XPath设置为`/div[eval("self.a")]/div/div[eval("self.b")]`，子元素设置为`/div[eval("self.a")]/div/div[eval("self.b")]/div`。

每个循环内都先设置`点击元素`操作把层级展开，然后设置`提取数据`操作，其中的字段名称设置为相同名称即可把信息输出到同一行：即第一个循环内的第一个操作为`提取数据`，添加字段名称为`文件夹描述`，然后下面是第二个循环，第二个循环内的第一个操作也是`提取数据`，操作的字段名称为`文件夹描述`，依此类推。

`父级编号`字段要在提取数据操作中自己增加字段，采集类型为`（针对该元素的）JavaScript代码返回值（需以return 开头）`并设置为`return "1"`（假设是第1层嵌套）的方式来将对应字段值设置为`1`。

需要用到的知识点就上面这些，熟练掌握即可实现你要的效果。

**Comment by NaiboWang** [comment]
另外，看你的截图似乎是在做公司业务，如果牵扯到商用（用于盈利，用于公司业务等），请按照流程联系我进行商用授权，软件有专利证书收到法律保护。

**Comment by yulongMao** [comment]
目前还是测试阶段，如果正式用于公司业务我会找您联系的，然后你刚才说的那种方法让我再摸索下，先别关闭issuse

**Comment by lj898lj** [comment]
B站能否出一期视频，解决一下树形结构的数据采集问题？
