### ISSUE TITLE
关于向上翻页的问题

### ISSUE THREAD

**Issue by wanwan213** [NaiboWang/EasySpider#295]
现在的循环点击里面的翻页或滚动都是向下翻页或滚动，向上翻页如何设置？例如日期的选择，页面显示的是当前最新的日期，但需要爬取以前日期的数据，需要日期选择页面向上翻页。数据网址：https://zhcxgzfw.gdcd.gov.cn/nile-cmgdtd-h5-fe/#/Egression/全省。

谢谢！

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。
