### ISSUE TITLE
任务可以无浏览器界面执行吗

### ISSUE THREAD

**Issue by apexg** [NaiboWang/EasySpider#30]
比如我在window上设计好任务，然后在ubuntu上无界面执行这个任务

**Comment by NaiboWang** [comment]
可以迁移任务信息，任务支持命令行执行，Windows设计完成后先获取任务ID，然后把execution_instances文件夹内的`.json`文件夹复制到Ubuntu，然后就可以命令行执行。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/e59d2d5c-360c-4db3-9302-0f19eb4ab46d)

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/fe37d967-9e06-43b3-9c88-e0f23f7e229d)


用户的配置信息文件夹直接迁移是无效的，需要在新机器上重新创建用户配置信息，并进行登录等操作。

对于无浏览器界面执行，请关注0.3.0版本的发布信息。

其实我很好奇为什么这么多人想要在各种复杂场景下运行软件，感觉违背了“Easy”这个初衷哈哈。

**Comment by apexg** [comment]
> 本的发布信息。

谢谢您的及时回复，感觉你的设计太棒了。解决了我的一个很大问题。但是你要知道，easy深层次是简化代码开发量，就是从web获取各种xpath，你的设计做到了。但是在生产上运行，如果带界面，那么爬取1000万条记录需要耗费多少时间？1亿条呢？

**Comment by apexg** [comment]
另外一个问题，可以用web端来进行easy的任务设计吗？就是不用桌面端exe程序进行注入？如果能实现，就太顺滑了。

**Comment by NaiboWang** [comment]
> > 本的发布信息。
> 
> 谢谢您的及时回复，感觉你的设计太棒了。解决了我的一个很大问题。但是你要知道，easy深层次是简化代码开发量，就是从web获取各种xpath，你的设计做到了。但是在生产上运行，如果带界面，那么爬取1000万条记录需要耗费多少时间？1亿条呢？

其实我觉得按照这个软件的设计逻辑，有没有浏览器只是能不能看到的问题，跟爬取速度没太大关系，因为是模拟一个真实的浏览器在运行。
想要加速爬取，是通过并行多开的方式同时开很多个程序在跑，单个程序的爬取速度和有没有浏览器界面没关系……

**Comment by NaiboWang** [comment]
> 另外一个问题，可以用web端来进行easy的任务设计吗？就是不用桌面端exe程序进行注入？如果能实现，就太顺滑了。

暂时不能，因为需要对本地文件进行读写，并操作webdriver进行设计，必须要本地程序注入。

**Comment by NaiboWang** [comment]
新版本已支持无浏览器执行，视频地址后半部分有：https://www.bilibili.com/video/BV1dV4y1z764/

**Comment by fushiqingyun** [comment]
> > 本的发布信息。
> 
> 谢谢您的及时回复，感觉你的设计太棒了。解决了我的一个很大问题。但是你要知道，easy深层次是简化代码开发量，就是从web获取各种xpath，你的设计做到了。但是在生产上运行，如果带界面，那么爬取1000万条记录需要耗费多少时间？1亿条呢？
类似自动化的爬取不太适合大批量的抓取，量大的话还是走纯协议比较好，逆向加密参数和滑块等手段可以做到高并发访问

**Comment by jianweiG9** [comment]
收到，感谢！


---- 回复的原邮件 ----
| 发件人 | Naibo ***@***.***> |
| 发送日期 | 2024年12月9日 16:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [NaiboWang/EasySpider] 任务可以无浏览器界面执行吗 (Issue #30) |

https://www.bilibili.com/video/BV1ch4y1E7cn/
