### ISSUE TITLE
批量爬取excel列表中的网址

### ISSUE THREAD

**Issue by zhangsy9708** [NaiboWang/EasySpider#304]
针对“多个网页执行此任务，可在“打开网页”操作内填入多行网址”。能否批量从excel中导入网页进行操作

**Comment by popstar2023** [comment]
可以，执行的时候选取从Excel读取就可以了，执行的时候会循环执行Excel导入的网页地址

**Comment by NIU-desing** [comment]
从Excel导入的多个网页地址，如何将数据分开输出呢？现在是所有数据输出在一个csv文件里，没办法进行区分呢
