### ISSUE TITLE
如何爬取页面上没有的数据

### ISSUE THREAD

**Issue by MisteryLiuCode** [NaiboWang/EasySpider#306]
作者您好，我在爬取boss直聘的时候，想要详情页面的公司地址的经纬度，但是页面上并没有这个数据，f12之后可以在源码里看到这个数据，请问要如何获取呢

**Comment by NaiboWang** [comment]
如果是网站源码中可以看到的数据但是页面上看不到，可以尝试F12审查元素后定位到元素，然后右键点击要爬取的元素，点击`Copy` -> `Copy XPath`或`Copy Full XPath`，然后在EasySpider中手动添加`提取数据`操作，点击`新增字段`按钮，将XPath填入XPath框中，以爬取隐藏元素。
