### ISSUE TITLE
mac windows切换

### ISSUE THREAD

**Issue by rookieroo** [NaiboWang/EasySpider#308]
希望能有个同步功能，有多个设备，操作系统不一样。或者新增如【复制】当前任务，【导出】当前任务类似的功能，手动去同步

**Comment by NaiboWang** [comment]
软件本身不进行商业运作，不需要注册，没有任何用户信息存储在我这里，因此也没有云服务器同步的业务。
复制操作本身就支持，请阅读Win和Mac版本的`软件使用说明.txt`来查看如何复制或导出任务。
