### ISSUE TITLE
循环点击链接，点击模拟为右键

### ISSUE THREAD

**Issue by MisteryLiuCode** [NaiboWang/EasySpider#311]
我想循环点击链接，但是点击的时候总是右键，无法进入页面，网址：https://www.autohome.com.cn/car/
<img width="1048" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/77911473/7aa7fdee-0fcc-4499-8075-230540d1ff46">

**Comment by noobM3** [comment]
+1

**Comment by NaiboWang** [comment]
没有搞清楚你的意思，是在MacOS系统下设计任务时出现的问题吗？操作台在哪里？

**Comment by MisteryLiuCode** [comment]
是的，macos。我设计是循环点击每个链接，但却在右键点击每个链接
<img width="1954" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/77911473/af966fc9-f3e8-463d-aa32-c6a9ec629685">

**Comment by NaiboWang** [comment]
这是个bug，将在下个版本修复，目前的解决方案：

1. 把在新标签页中打开的选项调整为“否”。
2. 如果再次执行还不能正确点击元素，则把点击类型该成JavaScript点击。

**Comment by markxiwang** [comment]
@NaiboWang 您好，我下载了mac的0.6.0版本，还是有这个问题。 然后我按照您说的 1.把在新标签页中打开的选项调整为“否”。
2.如果再次执行还不能正确点击元素，则把点击类型该成JavaScript点击。 运行还是右键效果，点击不进去详情页面。。

**Comment by NaiboWang** [comment]
Bug已修复，请下载最新版本使用。
