### ISSUE TITLE
循环嵌套时，内层循环可否继承外层循环的Xpath相对路径？

### ISSUE THREAD

**Issue by Cyclohexatriene** [NaiboWang/EasySpider#312]
大佬您好，我想爬B站的视频评论数据，B站的评论是有楼中楼功能的，每个root-reply都对应多个sub-reply，且sub-reply需要翻页获取。
我目前的思路是：外层循环遍历所有的sub-reply-container，对于每个遍历到的sub-reply-container，再用内层循环爬取当页数据并翻页。如果内层循环可以继承外层循环的Xpath的话，就可以用子路径来匹配所有当页的sub-reply，并定位到该container对应的翻页按钮，但目前没在循环功能的界面找到和“提取数据”功能一样的“使用相对循环内的XPATH”选项，不知道是否有其他方式可以实现类似的功能？求大佬指教

**Comment by NaiboWang** [comment]
目前版本还不支持，但可以用下面案例的方法使用eval函数解决：https://github.com/NaiboWang/EasySpider/issues/294

将来版本会考虑支持。
