### ISSUE TITLE
任务设置的采集网址是http，但是运行时打开的却是https

### ISSUE THREAD

**Issue by WangYoYo123** [NaiboWang/EasySpider#313]
![QQ截图20240228093330](https://github.com/NaiboWang/EasySpider/assets/128301604/7785303a-8589-4cac-b0da-e39cf000feec)
好像是谷歌浏览器的安全设置原因，任务运行的浏览器版本和电脑系统浏览器版本不一样，而且设置了允许不安全内容，再次允许任务后，设置又会变成默认的。是否可以更改采集浏览器

**Comment by NaiboWang** [comment]
请提供网址，不然无法调试。
不允许安全内容这块你可以尝试使用带用户信息模式看是否可以记忆设置的状态。

**Comment by NaiboWang** [comment]
参考：
https://developer.aliyun.com/article/563761
https://blog.csdn.net/buyulian/article/details/134245141
