### ISSUE TITLE
全选按钮点击不了，下载的文件能看见却打不开

### ISSUE THREAD

**Issue by Yougetadad** [NaiboWang/EasySpider#314]
1、网页上有一个全选的按钮和一个导出的按钮，全选按钮点击后会变成全部取消。我操作easyspider点击全选按钮没有反应，操作导出按钮会有反应。同样的xpath我在本地用python的selenium写是能正常操作的，想请作者帮支个招，看看可以从什么方向排查。
2、导出的数据可以在esp打开的chrome上看到，但是手动操作却打不开，到对应的下载地址去看也找不到这个文件，也想请作者帮看一下。
谢谢。

**Comment by NaiboWang** [comment]
可以把点击类型改为JavaScript点击试一试，第二条没有理解，建议提供更多细节。
