### ISSUE TITLE
请问怎么获取 输入的网址或输入的参数 到 提取数据 输出到excel ？

### ISSUE THREAD

**Issue by jwcjf** [NaiboWang/EasySpider#316]
请问怎么获取 输入的网址或输入的参数 到 提取数据 输出到excel ？

**Comment by jwcjf** [comment]
提取数据 的流程中 应该如何写 ？

**Comment by NaiboWang** [comment]
提取数据的字段中有个选项是提取当前页面网址，可以直接提取网址。
输入的参数可通过提取输入框文字的方式提取到字段。

**Comment by jwcjf** [comment]
> 提取数据的字段中有个选项是提取当前页面网址，可以直接提取网址。 输入的参数可通过提取输入框文字的方式提取到字段。

输入的参数可通过提取输入框文字的方式提取到字段。 这块 方便截图看看吗，我找不到在哪？非常感激[NaiboWang](https://github.com/NaiboWang)。

**Comment by NaiboWang** [comment]
浏览器中选中文本框，然后选择提取文本框的文本即可。

**Comment by jwcjf** [comment]
> 浏览器中选中文本框，然后选择提取文本框的文本即可。

请问 提取数据 中的字段配置那里可以配置 直接读取 输入参数吗

**Comment by NaiboWang** [comment]
目前不能，输入的参数是为了输入文字操作准备的，将来也许会考虑增加此需求。

**Comment by NaiboWang** [comment]
整个逻辑改起来可能比较复杂，不建议修改，建议我之前的意思，先把文字输入到文本框，再去提取文本框的文字。

如果一定要改，设计阶段和执行阶段都要动，不是一两句话能说清楚改完的，以执行阶段为例，需要将/ExecuteStage/easyspider_executestage.py文件的LoopExecute函数中的loopValue的值传给getData函数，还要给一个字段来接受，同时配合设计阶段的网页来设置参数类型，比较麻烦。

**Comment by jwcjf** [comment]
> 整个逻辑改起来可能比较复杂，不建议修改，建议我之前的意思，先把文字输入到文本框，再去提取文本框的文字。
> 
> 如果一定要改，设计阶段和执行阶段都要动，不是一两句话能说清楚改完的，以执行阶段为例，需要将/ExecuteStage/easyspider_executestage.py文件的LoopExecute函数中的loopValue的值传给getData函数，还要给一个字段来接受，同时配合设计阶段的网页来设置参数类型，比较麻烦。

我主要是在 循环中 提取数据 流程要 配置字段 可以提取到输入的值，每一行都需要有这个值。
目前按照博主的解决方法不能在循环 提取数据中配置，提取的数据无法合并到 提取数据的字段中。
请问有办法用变量的方式来获取吗

**Comment by NaiboWang** [comment]
循环中的提取数据操作提取文本框的值是可以做到每一行都有你要的输入的值的，建议多探索下。

变量方式可能可以做到，但我最近没时间亲自试验，如果做不到短时间内也不会去调试，提供大概思路：

循环开始设置一个变量存储self.loopValue = loopValue，提取数据操作时提取类型选择为eval，用self.outputParameters["字段名"]=self.loopValue来提取。

参考：https://github.com/NaiboWang/EasySpider/wiki/%E6%97%A0%E4%B8%8B%E4%B8%80%E9%A1%B5%E6%8C%89%E9%92%AE%E5%8F%AA%E6%9C%89%E5%85%B7%E4%BD%93%E9%A1%B5%E9%9D%A2%E6%8C%89%E9%92%AE%E6%97%B6%E7%9A%84%E7%BF%BB%E9%A1%B5%E6%96%B9%E6%B3%95%EF%BC%88EXEC%E5%92%8CEVAL%E6%95%99%E7%A8%8B%EF%BC%89

**Comment by pokerface-afk** [comment]
请问大佬有解决这个问题的办法吗，我目前也遇到了这个需求
循环搜索多个关键词：衣服、裤子、鞋子
然后将输入的关键词作为一个字段对应搜索到的内容保存到excel中
