### ISSUE TITLE
0.6版本貌似有bug

### ISSUE THREAD

**Issue by Merry997** [NaiboWang/EasySpider#318]
大佬您好，我有3个问题需要请教您一下，麻烦您啦！

1. 我发现0.6版本的在采集知识星球时，即便我前一分钟登录过，下一分钟再采集任务时还需要再登录，但是前面用0.5版本的就没这个问题，我再回用0.5版本的依然没有问题，不管是0.5还是0.6的，我都是用带用户信息的方式设计的和执行任务的，0.5的没问题，这0.6版这是不是个bug呢？

2. 由于知识星球没有导航，而且搜索功能也不太好，有的内容明明有的， 但就是搜不出来，我每次看一些帖子，可是下次看的时候又得从前面开始翻找，很不方便，也会错过很多内容，于是我想把我付费的某知识星球里面的内容整理到表格里，包含标题跟对应的链接，这样我每次只需要点击后面的链接就可以直接看了，不用再跑到知识星球里面浪费时间翻找了，也方便自己知道哪些看过哪些没看过。可是我在采集的时候发现，每个帖子对应的链接不知道怎么采集下来，点击“复制链接” 那个链接就在剪切板上了，在审查元素里面没有直接的链接呈现，好像是加密了，我应该怎样抓取呢？（请见图1、2)

3. 谷歌浏览器上面的 插件可以用easyspider来点击吗？我点了没反应。
我想让他自动点击那个蓝色插件singlefile  来实现自动保存页面 (请见图3)

**Comment by Merry997** [comment]
图片明明贴上了  怎么不见了呢， 奇怪。我重新用图床传了，如下：
https://s3.bmp.ovh/imgs/2024/03/13/07f48bf8a6ed26f8.jpg   这是图片1
https://s3.bmp.ovh/imgs/2024/03/13/177efccc486b97df.jpg   这是图片2
https://s3.bmp.ovh/imgs/2024/03/13/44dc29a176cf272e.png  这是图片3

**Comment by NaiboWang** [comment]
1. 可能是Bug，但短时间内我没时间维护，这个问题已经记录下来，将来有时间会去调试。
2. 具体如何采集的需求问题，这里不做具体答疑，实在没时间，建议加群问群友或者去淘宝等平台请人代做。
3. 不支持和浏览器的扩展进行交互。
