### ISSUE TITLE
试图搭建环境改源码的时候发现问题，能否提供对应环境版本，例如python版本等

### ISSUE THREAD

**Issue by ltjfk** [NaiboWang/EasySpider#320]
npm ERR! code 1
npm ERR! path D:\Tools\EasySpider-master\ElectronJS\node_modules\extract-file-icon
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run rebuild
npm ERR! > extract-file-icon@0.3.2 rebuild
npm ERR! > node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Users\as\AppData\Local\Programs\Python\Python3
12\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.34601.69) found at:
npm ERR! gyp info find VS "D:\Tools\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\as_liutianji\AppData\Local\Programs\Python\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\extract-file-icon\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\as_liutianji\\AppData\\Local\\node-gyp\\Cache\\18.16.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\as\\AppData\\Local\\node-gyp\\Cache\\18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\as\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.16.0
\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\extract-file-icon',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\extract-file-icon\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "D:\Tools\EasySpider-master\ElectronJS\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "D:\Tools\EasySpider-master\ElectronJS\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "D:\Tools\EasySpider-master\ElectronJS\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (D:\Tools\EasySpider-master\ElectronJS\node_modules\node-gyp\lib\configure
.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.17763
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Tools\\EasySpider-master\\ElectronJS\\node_modules\\node-g
yp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Tools\EasySpider-master\ElectronJS\node_modules\extract-file-icon
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

**Comment by NaiboWang** [comment]
是否已经正确安装vs-build-tools?
Python版本3.9.*，nodejs版本20.10.*

**Comment by ltjfk** [comment]
按你说的装了17版本的vs-build-tools

**Comment by NaiboWang** [comment]
我没有碰到同样的问题，复现不出来同样的错误，因此不知道怎么处理，你可以用桌面版的Ubuntu来试一试。

**Comment by ltjfk** [comment]
您好，您发送的邮件已收到，会尽快给你回复。
