### ISSUE TITLE
看到新版本支持手机网页采集，可否支持APP，因为有些软件时支持APP的，比如Auto.js

### ISSUE THREAD

**Issue by bestNiu** [NaiboWang/EasySpider#321]
后续是否有支持APP采集的功能，比如类似这种
https://github.com/kkevsekk1/AutoX
的形式？

**Comment by bestNiu** [comment]
后续有相关的计划吗？

**Comment by NaiboWang** [comment]
手机APP采集所采用的技术栈和网页端不同且安卓系统更新速度很快，因此个人开发者很难独立完成开发和后期维护，短时间内无开发计划，但如果将来我毕业后自己组建团队，也许会有此计划。
