### ISSUE TITLE
执行任务后，不关闭打开的浏览器，然后通过post调用多次填充表单，能实现吗

### ISSUE THREAD

**Issue by gang2113920** [NaiboWang/EasySpider#322]
有这样一种场景：
其他某个系统中只要有新产生的数据时，则通过post向打开的任务浏览器中的表单中填写信息。

即：设计好的任务执行后，不关闭打开的任务对应的浏览器；当其他系统有新数据时，通过post调用任务填充表单，能实现吗？可以的话指导下方法，谢谢

**Comment by NaiboWang** [comment]
post调用任务最好使用程序调用接口来实现，支持浏览器填写表单，不过你的需求比较麻烦，需要实时监控浏览器内容然后写post，可以配合调用外部系统脚本的方式实现，具体细节请看各种教程，这里不作详细阐述。
