### ISSUE TITLE
采集文章，多张图片，会有多条记录？

### ISSUE THREAD

**Issue by bestNiu** [NaiboWang/EasySpider#324]
<img width="1599" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/49513129/4447d9ea-7b45-46af-bc0b-68ef33f48978">

<img width="1725" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/49513129/59d051c7-2b87-4b86-8dd3-4f5badc37e17">

<img width="613" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/49513129/5feb8c31-2cc9-4029-acb7-fe5edfc16631">

如上图所示，参考汽车采集的视频模仿，如果一个文章里面有多张图片，按照上图所示部署流程的时候，采集的数据有1-7条，其中文章图片也有7张，所以生成了8条记录，不知道这种怎么解决？ 并且没有记录图片插入的位置（所在的位置）

最终目标： 
1、生成一条记录（解决文章多张图片多个记录的问题）
2、并且每次生成的图片能记录其具体的位置，方便后续插入？

**Comment by bestNiu** [comment]
网址demo: https://www.cbndata.com/information/292299

**Comment by bestNiu** [comment]
这种标记 是否导出的结果 是json,markdown等等格式呢？ 从而实现图片（多媒体）位置的标记，从而实现快速导入其他系统？

**Comment by NaiboWang** [comment]
第一个目标可以通过取消勾选循环内提取数据操作的`此提取数据操作后生成新数据行`选项，然后把循环前面的提取数据操作放在循环后面实现。

第二个目标暂时不支持，如果发现有相关框架支持，欢迎推荐以做参考。

支持json导出，markdown不支持。
