### ISSUE TITLE
是否支持填写字母或数字的验证吗识别？如下图所示

### ISSUE THREAD

**Issue by yubbdiitcn** [NaiboWang/EasySpider#327]
![QQ图片20240318190927](https://github.com/NaiboWang/EasySpider/assets/163848892/6982039b-f6fd-4fdc-ba81-99f08a5a6eec)

**Comment by NaiboWang** [comment]
配合OCR功能和输入文字的变量功能可实现，先用OCR功能识别出图片，然后用Field["字段名"]将验证码输入文本框即可。
