### ISSUE TITLE
创建新任务跳转到网页时出现错误

### ISSUE THREAD

**Issue by zhengqingsun** [NaiboWang/EasySpider#328]
作者您好，请问在创建新任务里面输入网址然后点击开始设计后网站无法跳转或者出现403forbidden之类的错误是因为什么原因？
![屏幕截图 2024-03-19 105112](https://github.com/NaiboWang/EasySpider/assets/95663467/31cc33e7-52e4-42df-a8c4-b59415271d80)

**Comment by NaiboWang** [comment]
这网站在我这里浏览器直接访问就是这个样子，应该是网站本身的问题。
