### ISSUE TITLE
打开http网址时，默认添加了s，导致无法打开

### ISSUE THREAD

**Issue by huanyu1991** [NaiboWang/EasySpider#330]

**Comment by NaiboWang** [comment]
参考：
https://developer.aliyun.com/article/563761
https://blog.csdn.net/buyulian/article/details/134245141

**Comment by sinofaneliu** [comment]
1.chrome://flags/ 里没有 https upgrades这个选项
2.网站设置不安全内容为允许后，再启动任务选项又重置了
