### ISSUE TITLE
自定义操作如何设置鼠标左键双击？

### ISSUE THREAD

**Issue by Prime-H** [NaiboWang/EasySpider#331]
如题：自定义操作如何设置鼠标左键双击？

**Comment by NaiboWang** [comment]
用自定义操作，执行exec操作，用self.browser表示浏览器，然后参考下面的文章写双击操作代码：

https://blog.csdn.net/xiaodanpeng/article/details/50999026

**Comment by NaiboWang** [comment]
功能已添加，请下载最新版本使用。
