### ISSUE TITLE
执行计划报错

### ISSUE THREAD

**Issue by shenxinming123** [NaiboWang/EasySpider#335]
Mac 、本地直接执行（纯净模式）版本：0.6.0
执行./easyspider_executestage --ids '[6]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/shenxinming/Library/Application Support/EasySpider/" --headless 0 --read_type remote --config_file_name config.json --saved_file_name  
报错：
Task Name: 中国地震台网——历史查询
任务名称: 中国地震台网——历史查询
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2400, in <module>
  File "myChrome.py", line 26, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 45, in __init__
  File "selenium/webdriver/chromium/webdriver.py", line 61, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 209, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 293, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 348, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 229, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location EasySpider.app/Contents/Resources/app/chrome_mac64.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  这种情况怎么处理 请指教一下

**Comment by QQ853695231** [comment]
我也报这个错

**Comment by QQ853695231** [comment]
@NaiboWang

**Comment by NaiboWang** [comment]
是否有cd到EasySpider的文件目录？请贴出命令行所有的命令或整个命令行界面的截图。

**Comment by waney** [comment]
```
id:  3
remote
Task Name: 中国地震台网——历史查询 - 子元素
任务名称: 中国地震台网——历史查询 - 子元素
文件下载路径|File Download path: C:\Users\kflul\Downloads\EasySpider_0.6.2_Windows_x64\Data\Task_3\files

DevTools listening on ws://127.0.0.1:56169/devtools/browser/94f7588a-494b-4c39-a679-d6cf47e0295b

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
pip index versions commandline_config
pip install commandline --upgrade
任务ID 3 的保存文件名为: TTTTT
Save Name for task ID 3 is: TTTTT
此模式下，任务ID 3 将从头F开始执行，如果需要从上次退出的步骤开始执行，请在保存任务时设置是否从上次保存位置开始执行为“是”。
In this mode, task ID 3 will start from the beginning, if you want to start from the last step, please set the option 'start from the last step' to 'yes' when saving the task.
Loading stealth.min.js
MySQL config file path:  ./mysql_config.json
成功连接到数据库。
Successfully connected to the database.
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2477, in <module>
  File "easyspider_executestage.py", line 226, in __init__
  File "utils.py", line 612, in create_table
KeyError: 'type'
[25276] Failed to execute script 'easyspider_executestage' due to unhandled exception!
```
me too...

**Comment by NaiboWang** [comment]
> ```
> id:  3
> remote
> Task Name: 中国地震台网——历史查询 - 子元素
> 任务名称: 中国地震台网——历史查询 - 子元素
> 文件下载路径|File Download path: C:\Users\kflul\Downloads\EasySpider_0.6.2_Windows_x64\Data\Task_3\files
> 
> DevTools listening on ws://127.0.0.1:56169/devtools/browser/94f7588a-494b-4c39-a679-d6cf47e0295b
> 
> Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
> pip index versions commandline_config
> pip install commandline --upgrade
> 任务ID 3 的保存文件名为: TTTTT
> Save Name for task ID 3 is: TTTTT
> 此模式下，任务ID 3 将从头F开始执行，如果需要从上次退出的步骤开始执行，请在保存任务时设置是否从上次保存位置开始执行为“是”。
> In this mode, task ID 3 will start from the beginning, if you want to start from the last step, please set the option 'start from the last step' to 'yes' when saving the task.
> Loading stealth.min.js
> MySQL config file path:  ./mysql_config.json
> 成功连接到数据库。
> Successfully connected to the database.
> Traceback (most recent call last):
>   File "easyspider_executestage.py", line 2477, in <module>
>   File "easyspider_executestage.py", line 226, in __init__
>   File "utils.py", line 612, in create_table
> KeyError: 'type'
> [25276] Failed to execute script 'easyspider_executestage' due to unhandled exception!
> ```
> 
> me too...

If you can upload your task file (`id.json` in the `tasks` folder) here, maybe I can help you to take a look, now I cannot reproduce your problem.

**Comment by Pinkolinka11** [comment]
533

Dne čt 25. 4. 2024 16:06 uživatel Naibo Wang ***@***.***>
napsal:

**Comment by waney** [comment]
[112.json](https://github.com/NaiboWang/EasySpider/files/15124106/112.json)
Default file downloaded from github，for EasySpider_0.6.2_Windows_x64.

**Comment by NaiboWang** [comment]
> [112.json](https://github.com/NaiboWang/EasySpider/files/15124106/112.json) Default file downloaded from github，for EasySpider_0.6.2_Windows_x64.

This task is too old and not compatible to this version of EasySpider, please try to redesign a new task with current version of EasySpider, or try to use old version of EasySpider to run this task.
