### ISSUE TITLE
知网年鉴下载

### ISSUE THREAD

**Issue by zhangsy9708** [NaiboWang/EasySpider#338]
想问下楼主，知网年鉴自动执行的时候点了下载，但本地并没有下载，也没有下载记录怎么办？然后尝试，爬到对应网站之后，在停留界面的两三秒内，手动点击下载，依旧是本地没有文档，历史记录也没有下载记录，easyspider的data文件里面也没有tat

**Comment by NaiboWang** [comment]
我也不清楚你的情况，你可以尝试找另一个有下载功能的网站看一看是否有同样的情况发生，如果手动点击下载按钮都不能下载，大概率是网站本身的问题，自己的浏览器可以下载吗？

**Comment by zhangsy9708** [comment]
自己的浏览器可以下载的😭



发自我的iPad


------------------ 原始邮件 ------------------
发件人: Naibo Wang ***@***.***&gt;
发送时间: 2024年4月4日 01:57
收件人: NaiboWang/EasySpider ***@***.***&gt;
抄送: zhangsy9708 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [NaiboWang/EasySpider] 知网年鉴下载 (Issue #338)





 
我也不清楚你的情况，你可以尝试找另一个有下载功能的网站看一看是否有同样的情况发生，如果手动点击下载按钮都不能下载，大概率是网站本身的问题，自己的浏览器可以下载吗？

**Comment by NaiboWang** [comment]
这个问题短时间内我没时间去看，你可以尝试多看看教程和搜索有没有相关issue或者看源代码来解决，将来有时间我会去研究下。
