### ISSUE TITLE
提取第一层数据和第二层数据不能一一匹配

### ISSUE THREAD

**Issue by therocflyinginbluesky** [NaiboWang/EasySpider#34]
以下是案例：Easyspider采集公开招标信息记录
一、应用场景
在中国政府采购网中，采集公开招标信息，采集的信息包括公开招标主页数据和公告明细页数据。
URL：http://www.ccgp.gov.cn/cggg/dfgg/gkzb/
二、设置流程
 
![设计流程图](https://github.com/NaiboWang/EasySpider/assets/133950042/c86e8c6b-c886-4529-8611-e8d61e3a3098)

流程说明：
1.打开网页。
2.循环点击下一页：xpath：//*/a[@class="next"]，测试时只循环1次。
3.循环提取数据：xpath：/html/body/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li
4.提取总览数据：提取采购公告总览列表数据，提取项目名称、发布时间、地域、采购人、连接地址字段。
5.点击进入明细页：点击采购公告名称链接，进入公告明细页面。xpath：/html/body/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li/a[1]
6.提取明细也数据：提取明细页全部数据，字段名“采购公告”，xpath：/html/body/div[2]/div[1]/div[2]
7.点击下一页：点击下一页按钮。
三、问题
执行任务，能进入明细页和跳转下一页，能成功实现数据采集，但是采集的数据有问题，提取总览数据和提取明细页数据，有冗余，并且不能一一对应，提取第一部分数据有两行，提取第二部分数据也有两行，两部分数据交错对应。
请帮忙看下是什么问题，是不是设计流程出了问题？
四、附件
1.word记录；
2.设计流程json；
3.提取的数据；
4.日志。 
[Uploading 附件.zip…]()

**Comment by therocflyinginbluesky** [comment]
非常感谢你的解答，非常专业，我遇到的问题就是你解答中的这个情况，提取的数据样式也是与你提供的一致。通过你的解答，我明白了取数的逻辑，再次感谢。

**Comment by NaiboWang** [comment]
谢谢，因为程序全部都是我自己写的，自然对这个逻辑很清晰，感谢使用~

**Comment by Keith-Luo** [comment]
> 谢谢，因为程序全部都是我自己写的，自然对这个逻辑很清晰，感谢使用~

作者您好！请问这里有办法将删除多余行的逻辑封装在任务程序里面吗？我想尽可能不对excel进行后处理操作
