### ISSUE TITLE
在内容部分，使用全选，但是选不全。

### ISSUE THREAD

**Issue by bossnova426** [NaiboWang/EasySpider#340]
https://www.marketsmith.hk/webtool/#/stockQuotes
需要注册
点击左边行情，点击沪深，选择行业代码后，屏幕右边有行业下公司。个别公司非常多的里面，不能全部选择。
![EQ8%B{26PY%I~EAIVL2EN D](https://github.com/NaiboWang/EasySpider/assets/92976897/3e6edb37-c3de-49ca-a5d9-979d4f50511b)

如果使用手动添加，表格会乱。

**Comment by NaiboWang** [comment]
登录不了你说的网站，但大概率是他网页设计的时候这些元素就是没有在同一个级别。

**Comment by NaiboWang** [comment]
自动选中逻辑不会存在问题，如果有问题只能是网站设计就是不认为是同类型元素。
