### ISSUE TITLE
打开网站之后页面空白

### ISSUE THREAD

**Issue by sunpeng1979** [NaiboWang/EasySpider#342]
网站为:https://gaokao.chsi.com.cn/
网站协议：# Robots.txt file from http://gaokao.chsi.com.cn
# All robots will spider the domain

User-agent:*
Disallow:/zzbm/tjr/
非政府网站
运行EasySpider打开网站时显示的是空白的，使用F12，发现是。/favicon.ico:1    Failed to load resource: the server responded with a status of 400 (Bad Request)
差了些资料，将
chrome://flags/#block-insecure-private-network-requests修改为Disabled
运行EasySpider打开网站，可以显示页面，但是开始设计之后，试运行时，点击任何一个链接都没有反应，设计好之后，执行命令找不到XPATH。使用纯净版和用户版都用不了。求救。如果违反规定，请删除，谢谢

**Comment by NaiboWang** [comment]
学信网属于政府性质的网站，不予答疑，请自行调试，谢谢！
