### ISSUE TITLE
在多个FRAME框架的页面，顶端的标题上需要采集的菜单无法移动

### ISSUE THREAD

**Issue by chenglong08** [NaiboWang/EasySpider#344]
在多个FRAME框架的页面，顶端的标题上需要采集的操作菜单被遮挡，无法移动

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/wiki/%E6%93%8D%E4%BD%9C%E5%8F%B0%E6%8C%A1%E4%BD%8F%E7%99%BB%E5%BD%95%E9%A1%B5%E9%9D%A2%E7%9A%84%E5%A4%84%E7%90%86%E5%8A%9E%E6%B3%95
