### ISSUE TITLE
爬取www.smm.cn表格疑问

### ISSUE THREAD

**Issue by sudyhe** [NaiboWang/EasySpider#346]
网页界面：
![原始网页表格](https://github.com/NaiboWang/EasySpider/assets/13766872/f256bd4f-e356-428f-8bc8-f7cf5fd14c89)

爬取数据表格格式乱了，请求支援。
![爬取后串行](https://github.com/NaiboWang/EasySpider/assets/13766872/6d9b6893-da75-4782-a291-e099975abf1c)

**Comment by NaiboWang** [comment]
这种属于具体设计的需求问题，需要自己想办法解决，这里不做具体答疑，谢谢。

**Comment by sudyhe** [comment]
邮箱功能可以支持爬取下来的附件吗？

**Comment by Pinkolinka11** [comment]
Nikdy za vama ani neprijedu a nic proste. Nechci vás proste znat s jsem
zhnusena ze vseho a ze vsech. Uz neverim. Chci jen svou dceru kterou jste
zn7cili. Svrjma zkurvrnostma. Tahnete do hajzlu ubozaci. Nenávidím vás.
Nejsem na nic zvedava. Na vase lzi a divadelka. B

Dne st 17. 4. 2024 10:22 uživatel sudyhe ***@***.***> napsal:

**Comment by NaiboWang** [comment]
> 邮箱功能可以支持爬取下来的附件吗？

邮箱功能只是简单的让你实现发邮件通知任务结束等需求，不支持附件，如果需要类似功能请自行下载源码修改。
