### ISSUE TITLE
Is it possible to interact with other chrome extensions?

### ISSUE THREAD

**Issue by day-xy** [NaiboWang/EasySpider#349]
Hi there,

I'd like to know if it is possible to automate the interaction with other chrome extensions? For example, website login based on the the other extension?

Thanks,
Day

**Comment by NaiboWang** [comment]
Hi, EasySpider does not support automatically interacting with other chrome extensions, but if the extension can automatically work without human intervention, it is OK. For example, if an extension will automatically detect the captcha and solve it, you can just install it and it will automatically work (remember to use User Mode).
