### ISSUE TITLE
任务流程有多个提取数据操作时，软件的执行和输出逻辑

### ISSUE THREAD

**Issue by NaiboWang** [NaiboWang/EasySpider#35]
按照软件逻辑来说，数据交错应该每隔两行的数据是对应好的，因为软件本身的逻辑是每一个提取数据操作执行完成后都会输出一行，你的任务流有两个提取数据操作，因此每一轮采集都会输出两行，偶数行的数据是对应的。如第一个提取数据由字段A，B，C组成，第二个由D，E组成，那么第1轮采集时，软件会先填充ABC输出一行，再填充DE并保留之前ABC的值再输出一行。下一轮采集时，第一次ABC的值会变成第2次的新值，DE的值仍然是第一次的旧值；第二次ABC的值保留，DE的值变成第二次的新值，用表格表示即：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/1b20598b-eac3-46c8-ba34-758a4eb4c11c)

也就是说，流程中有几个提取数据的操作，每一轮执行就会生成几行。

因此，加粗部分的值应该是一一对应好的值，其余的值可以删掉，你用excel简单操作一下就可以了，可以看一下数据是不是我说的这样子。

另外另一个解决方案是使用即将发布的v0.3.0版本，新版本支持采集打开页面的标题，就不需要先提取总览数据再提取明细页数据了。

_Originally posted by @NaiboWang in https://github.com/NaiboWang/EasySpider/issues/34#issuecomment-1552659730_

**Comment by NaiboWang** [comment]
最新版本V0.6.0可通过设置是否生成新行来解决此问题：

<img src="https://github.com/NaiboWang/EasySpider/assets/30287768/2e580fa5-24e7-4e36-a380-bb886edb4781" width=60%>

**Comment by zhangdanmiao** [comment]
友情提醒，是在最后一次的提取数据中勾选【此提取数据操作后生成新数据行】
