### ISSUE TITLE
大佬，这个和影刀是不是差不多？ 

### ISSUE THREAD

**Issue by Yi-Lyu** [NaiboWang/EasySpider#353]
前阵子刚把影刀学会，刚去 bilibili 看了 EasySpider 的视频教程，感觉很像呐。

https://www.yingdao.com/

**Comment by NaiboWang** [comment]
自动化测试软件可能使用方式上都差不多，会用就行。

**Comment by Pinkolinka11** [comment]
Co?

Dne st 17. 4. 2024 4:41 uživatel Naibo Wang ***@***.***>
napsal:
