### ISSUE TITLE
网站的http与https的问题

### ISSUE THREAD

**Issue by sinofaneliu** [NaiboWang/EasySpider#354]
#330 按照里面的处理：
1.chrome://flags/ 里没有 https upgrades这个选项
2.网站设置不安全内容为允许后，再启动任务选项又重置了

要爬的网站主页可以通过https访问，但是要爬的链接只能通过http访问

**Comment by NaiboWang** [comment]
能否把网站链接发一下，我这边看看。

**Comment by NaiboWang** [comment]
临时解决方案：打开网页的时候设置一定的操作等待时间，手动调整https为http然后回车打开网页。
