### ISSUE TITLE
如果这一页只有一个doc，有办法让下载的doc以这一页采集到的标题命名？

### ISSUE THREAD

**Issue by dadalongvs** [NaiboWang/EasySpider#355]
由于我下载的网页的doc可能是因为他后台没有命名，所以每次下载下来名字都是一串数字和英文，如下图：
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/414fcbad-ee3d-4165-89e2-3ac33a003e9d)
我想将下载的文件就直接以采集的标题命名，该如何实现？是要添加什么步骤么？
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/9f171fc6-a998-456b-b816-4097df59178a)

**Comment by NaiboWang** [comment]
目前只能通过修改代码实现，请自行下载代码修改，没有好的办法。

**Comment by dadalongvs** [comment]
好的

**Comment by dadalongvs** [comment]
> 目前只能通过修改代码实现，请自行下载代码修改，没有好的办法。

这个没办法在自定义操作里通过一些代码实现么？

**Comment by NaiboWang** [comment]
不是很好处理，因为下载文件的监听函数在`utils.py`的`rename_downloaded_file`函数中，而且文件明明本身不受selenium控制，你的需求比较特殊，所以还是需要自己处理，配置环境也不是很难，可以试一试。

**Comment by dadalongvs** [comment]
> 不是很好处理，因为下载文件的监听函数在`utils.py`的`rename_downloaded_file`函数中，而且文件命名本身不受selenium控制，需要监听有没有新文件产生然后再去命名，你的需求比较特殊，所以还是需要自己处理，配置环境也不是很难，可以试一试。

可以请问一下，修改完utils.py然后使其编译生效的是哪一步？我在rename_downloaded_file函数下试了一个print("")，然后编译完npm run start_direct运行，再模拟点击下载一个文件，本地终端没有打印我print("")里的东西

**Comment by dadalongvs** [comment]
> 不是很好处理，因为下载文件的监听函数在`utils.py`的`rename_downloaded_file`函数中，而且文件命名本身不受selenium控制，需要监听有没有新文件产生然后再去命名，你的需求比较特殊，所以还是需要自己处理，配置环境也不是很难，可以试一试。

可以请问一下采集数据或标题的是那个函数么？

**Comment by NaiboWang** [comment]
`getData`是采集数据的函数。
