### ISSUE TITLE
判断条件的Javascript命令返回值功能执行错误

### ISSUE THREAD

**Issue by fyang93** [NaiboWang/EasySpider#357]
按照[官方教程](https://www.bilibili.com/video/BV1N94y1a7Lp)的操作，先循环采集数据，数据中包含字段“出价次数”，但是在判断条件中使用`Field["出价次数"]`出现以下错误：

```
执行JavaScript出错，请检查JavaScript语句是否正确：return Field["出价次数"] > 0
错误信息： JavascriptError: javascript error: Field is not defined(Session info: chrome=124.0.6367.61)
```

**Comment by Pinkolinka11** [comment]
To víš že jo Matěji. Jim to nevadí voní to takhle chtějí mít hezky při ruce.

Dne čt 25. 4. 2024 10:25 uživatel Fan YANG ***@***.***>
napsal:

**Comment by NaiboWang** [comment]
带`Field[""]`的指令只能在执行阶段进行测试，设计阶段不能直接测试，请在直接阶段测试此条件是否能被正确处理。

另外，你写的语句恰巧可以成立，但注意在其他情况下一般这么写是不对的，因为`Field[""]`如果不是数字而是字母或汉字，如`three`，那么你的语句会被转换为`return three>0`，此时不符合JS的语法格式（会把`three`识别成一个变量而不是字符串），应该在`Field[""]`前后加上引号，使得转义语句变成`return 'three' > 0`。
