### ISSUE TITLE
使用报错：most recent call last

### ISSUE THREAD

**Issue by Xiao-yi123** [NaiboWang/EasySpider#358]
![image](https://github.com/NaiboWang/EasySpider/assets/67501413/b86e095a-4435-4746-a1d5-ec749b48cab0)
如果报错Selenium, common. exceptions. WebDriverException: Message: unknown error: Chrone failed to start: exited abnormally,说明有之前运行的Chrome买例没有正常天团,请天团之前打开的所有Chrome买例后再运行程序即可。If you get an error Selenium, common. exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally, it means that there is a Chrome instance that was not closed properly before, please close all Chrome instances that were opened before running the program.id: 0remoteTraceback (most recent call last):File "easyspider_executestage.py", line 2348, in <module>File "json init.py", line 346, in loadsFile "json decoder.py", line 337, in decodeFile "json decoder.py", line 355, in raw decodeljson. decoder. JSONDecodeError: Expecting value: line 1 column 1 (char 0) [7656] Failed to execute script easyspider_executestage' due to unhandled exception!Cannot automatically check new version, please use the following command to check whether a new version avaliable and un grade by pip:■1:32mpip index versions commandline configpip instal1 commandline --upgradel0m

**Comment by NaiboWang** [comment]
是不是运行的已有的老任务？重新设计一个新的任务试一试，老版本任务有兼容性问题有可能运行不了。

**Comment by Xiao-yi123** [comment]
使用的0.6.2的最新的版本 设计任务时一点问题都没有 执行的时候就报错 重新设计的任务也执行不了

**Comment by NaiboWang** [comment]
把execution_instances文件夹里的2.json发到这里，我看一下。

**Comment by Xiao-yi123** [comment]
{"id":0,"name":"百度一下，你就知道","url":"https://www.baidu.com","links":"https://www.baidu.com","create_time":"2024-04-25 21:17:31","update_time":"2024-04-25 21:17:37","version":"0.6.2","saveThreshold":10,"quitWaitTime":60,"environment":0,"maximizeWindow":0,"maxViewLength":15,"recordLog":1,"outputFormat":"csv","saveName":"current_time","dataWriteMode":1,"inputExcel":"","startFromExit":0,"pauseKey":"p","containJudge":false,"browser":"chrome","removeDuplicate":0,"desc":"https://www.baidu.com","inputParameters":[{"id":0,"name":"urlList_0","nodeId":1,"nodeName":"打开网页","value":"https://www.baidu.com","desc":"要采集的网址列表，多行以\\n分开","type":"text","exampleValue":"https://www.baidu.com"}],"outputParameters":[],"graph":[{"index":0,"id":0,"parentId":0,"type":-1,"option":0,"title":"root","sequence":[1],"parameters":{"history":1,"tabIndex":0,"useLoop":false,"xpath":"","iframe":false,"wait":0,"waitType":0,"beforeJS":"","beforeJSWaitTime":0,"afterJS":"","afterJSWaitTime":0,"waitElement":"","waitElementTime":10,"waitElementIframeIndex":0},"isInLoop":false},{"id":1,"index":1,"parentId":0,"type":0,"option":1,"title":"打开网页","sequence":[],"isInLoop":false,"position":0,"parameters":{"useLoop":false,"xpath":"","wait":0,"waitType":0,"beforeJS":"","beforeJSWaitTime":0,"afterJS":"","afterJSWaitTime":0,"waitElement":"","waitElementTime":10,"waitElementIframeIndex":0,"url":"https://www.baidu.com","links":"https://www.baidu.com","maxWaitTime":10,"scrollType":0,"scrollCount":1,"scrollWaitTime":1,"cookies":""}}]}

**Comment by Xiao-yi123** [comment]
我在其他电脑上测试也是正常的 就我自己的电脑不能使用 难道是人品问题？

**Comment by NaiboWang** [comment]
你先试试把那两个文件夹删掉然后重新设计行不行，如果还不行可能是你的电脑安装了某些库改变了程序读取json文件的行为从而报错，如果这样，建议下载源码自行编译调试，看看问题到底出在哪里。

**Comment by Xiao-yi123** [comment]
大概是因为装了什么库的原因了

**Comment by Xiao-yi123** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/67501413/b459b700-37ef-41ce-8a3d-d5435d517569)

**Comment by NaiboWang** [comment]
这张图的原因是在说访问不到服务器，默认服务器地址是http://localhost:8074，但你似乎安装了什么代理程序，导致服务器访问不到。

可以使用命令行执行来规避这个问题，或者修改你的代理程序。

**Comment by Xiao-yi123** [comment]
怎么规避？但我访问 localhost:8074是正常访问的

**Comment by NaiboWang** [comment]
使用下方命令行执行，先点击获得任务ID，再点击命令行执行，打开powershell把命令粘贴进去运行。

你的代理问题我不清楚怎么回事，总之是影响到了程序执行。

**Comment by Xiao-yi123** [comment]
现在就是这么弄的 可惜没有成功 我先研究研究 看能不能解决

**Comment by NaiboWang** [comment]
记得把命令行的`--read_type`参数后面的值由`remote`改为`local`。

**Comment by Pinkolinka11** [comment]
533

Dne čt 25. 4. 2024 15:58 uživatel Naibo Wang ***@***.***>
napsal:

**Comment by Xiao-yi123** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/67501413/5985b4f3-8a4c-4128-8fe8-dc87f2069236)
默认就是local 找不出原因所在 代理也没有问题 这个软件对pip版本有要求吗？ 我已经把所有库都卸载了还不行

**Comment by Xiao-yi123** [comment]
大佬求助啊

**Comment by Pinkolinka11** [comment]
Just because.

Dne čt 25. 4. 2024 16:31 uživatel Xiao-yi123 ***@***.***>
napsal:

**Comment by NaiboWang** [comment]
软件是可以直接在一个全新安装没有任何软件和配置的系统上直接运行的，默认对任何环境都没有要求，但随着各种软件的安装，也许会影响到默认配置的环境。

按开始菜单按钮，输入proxy或者代理，看一下你的代理是怎么配置的？

**Comment by Pinkolinka11** [comment]
Well yes. I do think so. I will be Ha ha ha ha

Dne čt 25. 4. 2024 16:33 uživatel Naibo Wang ***@***.***>
napsal:

**Comment by NaiboWang** [comment]
关掉代理，重试一次。

**Comment by NaiboWang** [comment]
那我暂时也不知道怎么回事，因为我也没碰到过这种问题，这个是你电脑环境的事。

我只能给出两个替代方案：

1. 安装虚拟机运行程序。
2. 自己下载源码跑Python，然后一步一步调试看到底是哪里的问题。

**Comment by Xiao-yi123** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/67501413/57ba32ec-63a6-4de7-a8c4-b26ab02ad4cf)
这是我电脑安装的库 是否对其他某个的版本有要求？

**Comment by NaiboWang** [comment]
程序是打包好的，按理说和你电脑安装的环境是没有关系的，出现问题只能是和代理设置有关系。
你如果自行下载代码运行那这些包才会有影响。
你可以创建个新的用户，再试试用新用户执行程序。

**Comment by Xiao-yi123** [comment]
换个新用户目好像是可以正常使用的 那就是因为我当前的用户环境太乱了 其中某个东西影响到了它？如果是代理的问题的话有没有可能是VPN导致的？

**Comment by NaiboWang** [comment]
VPN就是代理的一种，你自己慢慢研究吧，我觉得大概率是这个原因。

**Comment by Xiao-yi123** [comment]
在其他电脑上我也用VPN 也能正常使用 先用其他用户玩吧 这个问题慢慢研究 代理问题本机的代理应该不会出什么问题的
