### ISSUE TITLE
类似简数这种可视化提取怎么实现的？

### ISSUE THREAD

**Issue by fendo8888** [NaiboWang/EasySpider#36]
类似下面这几种：

在页面上可以通过点击的方式获取提取规则
![image](https://user-images.githubusercontent.com/22114481/201588791-cf4ef6a7-e90e-4687-97f5-ecee1c5bcd39.png)

![image](https://user-images.githubusercontent.com/22114481/201589043-45e1ab71-5db5-407a-a0af-f05d2654e394.png)

**Comment by NaiboWang** [comment]
这个问题回答起来就比较复杂了，总的来说是通过Chrome扩展开发的方式进行js嵌入实现的，既然整个代码都开源，你可以fork一份自己研究一下。

**Comment by fendo8888** [comment]
> 这个问题回答起来就比较复杂了，总的来说是通过Chrome扩展开发的方式进行js嵌入实现的，既然整个代码都开源，你可以fork一份自己研究一下。
EasySpider的我知道是通过Chrome扩展，问题是他那个不需要装任何插件，直接打开页面，就能可时候提取，在网上找了一圈没找到相关的介绍。也就是可视化提取xpath(可视化提取规则)，我这边猜想是为每个dom元素绑定了事件，点击时，自定获取xpath，就是没找到好点的开源的类似这种。

**Comment by NaiboWang** [comment]
其实浏览器默认带的这个按钮就可以定位到元素然后右键获取XPath的，其实是不需要为每个元素绑定事件，只需要拿到页面源码的HTML DOM树就可以动态算出来。

至于简数怎么做的，闭源软件我也无法回答，但获取XPath并不困难，有很多方法可以实现，一个JS函数足矣。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/a47732d3-47c2-4416-9076-9bf4c27bcb26)
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/2a89334b-7f0e-4b0c-94d9-6b585f323cd1)

**Comment by fendo8888** [comment]
> 其实浏览器默认带的这个按钮就可以定位到元素然后右键获取XPath的，其实是不需要为每个元素绑定事件，只需要拿到页面源码的HTML DOM树就可以动态算出来。
> 
> 至于简数怎么做的，闭源软件我也无法回答，但获取XPath并不困难，有很多方法可以实现，一个JS函数足矣。
> 
> ![image](https://user-images.githubusercontent.com/30287768/239564811-a47732d3-47c2-4416-9076-9bf4c27bcb26.png) ![image](https://user-images.githubusercontent.com/30287768/239565173-2a89334b-7f0e-4b0c-94d9-6b585f323cd1.png)

实现方式肯定是通过JS的方式，看了网上的一些方式：

https://stackoverflow.com/questions/2661818/javascript-get-xpath-of-a-node

想找个现成开源的😀
