### ISSUE TITLE
建议加一个导出任务为独立py脚本的功能，可以在服务器灵活部署

### ISSUE THREAD

**Issue by xiaomayisjh** [NaiboWang/EasySpider#364]
建议加一个导出任务为独立py脚本的功能，可以在服务器灵活部署。最好可以还导出pip依赖

**Comment by NaiboWang** [comment]
这功能本来就有，不需要配置设计阶段可直接部署在Linux服务器，只需要配置好webdriver即可。
参考：https://github.com/NaiboWang/EasySpider/wiki/Docker%E8%BF%90%E8%A1%8C%E7%A4%BA%E4%BE%8B
