### ISSUE TITLE
自动修改文件名？？

### ISSUE THREAD

**Issue by Houcheng766** [NaiboWang/EasySpider#365]
在循环点击PDF文件的时候不知道为什么会修改文件名，能否不修改直接使用下载的文件名？
[
<img width="697" alt="截屏2024-04-30 13 55 32" src="https://github.com/NaiboWang/EasySpider/assets/129932087/39443157-19f7-4fa0-930c-8a80506d6afe">
<img width="697" alt="截屏2024-04-30 13 55 32" src="https://github.com/NaiboWang/EasySpider/assets/129932087/3d393d32-1e0b-4865-87ec-47bbe01ade5b">
<img width="1552" alt="截屏2024-04-30 13 54 22" src="https://github.com/NaiboWang/EasySpider/assets/129932087/62a0359a-e29e-4da4-9f5d-0dfff765dee8">
](url)

**Comment by NaiboWang** [comment]
是的，会自动修改文件名的原因是为了避免多次下载同名文件，因为重名被覆盖之前下载的文件，如果需要保留原文件名，使用0.6.0版本即可。
