### ISSUE TITLE
请问该怎么提取cookie？

### ISSUE THREAD

**Issue by IamMagicSu** [NaiboWang/EasySpider#366]
我想注册账号后提取cookie保存，但我不知道该怎么做……
教程和视频也没有说，我看issue去年有人提了相同的问题，也给了解决方案。
但是我没学过python，看不懂，需要有更具体一点的方法，拜托拜托……
![image](https://github.com/NaiboWang/EasySpider/assets/143731057/cd5af8a5-2d87-4ed7-bbac-1f1b19e71f54)

**Comment by NaiboWang** [comment]
打开网页操作有个按钮可以获取cookies，试一试。
