### ISSUE TITLE
在国产统信系统上不能使用？请问有什么办法吗？

### ISSUE THREAD

**Issue by leonaghL** [NaiboWang/EasySpider#368]
在国产统信系统上不能使用？请问有什么办法吗？国产统信系统使用的是liunx-arm64架构，下载easyspider执行显示二进制问题。能有办法吗？

**Comment by NaiboWang** [comment]
ARM64不直接支持，但是可以自行编译，因为selenium和chromium driver都有对应的适配，需要自行处理。
