### ISSUE TITLE
MAC系统提示错误

### ISSUE THREAD

**Issue by yahyako** [NaiboWang/EasySpider#37]
系统版本 macos Ventura 13.3.1 (a)
按照B站教程 结果最后提示：
Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "easyspider_executestage.py", line 674, in clean
  File "easyspider_executestage.py", line 660, in saveData
TypeError: can only concatenate str (not "NoneType") to str

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
不知道怎么回事

**Comment by NaiboWang** [comment]
完全按照B站教程来的吗，能不能让我看一下你的任务流程是什么样的？命令行命令什么的。

**Comment by yahyako** [comment]
<img width="1148" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/76864710/4a9518bc-669b-4e01-a86b-f215165c88a5">

**Comment by NaiboWang** [comment]
额，我说的是你这个图里的“修改任务流程”，然后调用任务的时候的命令行提示命令。

**Comment by yahyako** [comment]
为了测试所以需求很简单 不涉及到循环和判断 
然后
<img width="1173" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/76864710/3c162578-1ecf-489d-9fa9-3f970b998d90">

**Comment by yahyako** [comment]
<img width="999" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/76864710/dfdebf3c-a517-4d04-8f1d-a7c5b994a0b2">

**Comment by yahyako** [comment]
然后就这样

**Comment by NaiboWang** [comment]
麻烦把你的/Users/bunihala/Library/Application Support/EasySpider下的execution_instances文件夹里的4.json发到我的邮箱naibowang@u.nus.edu我去看一下

**Comment by yahyako** [comment]
抱歉 我没找到您说的这个路径

**Comment by NaiboWang** [comment]
你执行的方式不对，应该先cd到这个文件夹，然后在执行命令行提示的命令：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/98ded44f-044d-4dd4-8b83-d51641b3fe54)

然后暂时不要有中文路径。

可以等待月底之前发布的v0.3.0版本，命令行提示会更智能。

**Comment by yahyako** [comment]
好的 等您月底发布吧  感谢您的回复 祝万事顺利

**Comment by NaiboWang** [comment]
这个版本也能用啦，先cd /Volumes/B-SDD/.../EasySpider_MacOS_all_arch
然后再./easyspider_executestage 那一串命令就行了。

**Comment by yahyako** [comment]
可以了 按照您说的 CD 到具体目录就可以了 万分感谢老师

**Comment by NaiboWang** [comment]
不客气~
