### ISSUE TITLE
获取html页面head标签里面的内容

### ISSUE THREAD

**Issue by lzlitich** [NaiboWang/EasySpider#374]
目前只能获取到html里面<body>中的内容. 但是<head>里面的标签内容获取不到.  使用xpath 在页面内是可以获取到元素内容.点击试运行获取不到.

**Comment by touero** [comment]
检查是否存在iframe

**Comment by lzlitich** [comment]
<img width="862" alt="head" src="https://github.com/NaiboWang/EasySpider/assets/169120341/07470fdb-7a99-4adc-a59f-baa653415e11">
不存在iframe,就是直接获取html里面的<head></head>内容

**Comment by touero** [comment]
把网站和xpath发出来看一下

**Comment by lzlitich** [comment]
网址地址:https://www.1905.com/  
标题:/html/head/title
关键词://meta[@name='keywords']/@content
链接://meta[@property='og:url']/@content

**Comment by NaiboWang** [comment]
采集标签属性值时，不能使用@content这种写法来获取，而是要在下面选择采集内容类型为`元素的属性值`，并指定属性名称`

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/b3613

示例任务：

[338.json](https://github.com/NaiboWang/EasySpider/files/15246785/338.json)
b6d-80e1-47c7-9d01-b42c7e6941d9)

**Comment by lzlitich** [comment]
多谢!
