### ISSUE TITLE
0.6.2控制面板被挡住了，怎么都弄不出来

### ISSUE THREAD

**Issue by wangzongming** [NaiboWang/EasySpider#375]
操作这个网址就会复现 https://hwdms.mot.gov.cn/BMWebSite/person/base.do?id=d5efccda52bb44a3a54b3d92dd0dc4df&type=0&companyid=c9932a5b272d46b386d96698bec4121b

![image](https://github.com/NaiboWang/EasySpider/assets/27466569/22df6c75-5f0e-464c-9ff3-0dd43c939f5b)

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。
