### ISSUE TITLE
我输入的网址是http,任务采集的时候会自动使用https

### ISSUE THREAD

**Issue by jerryxjh** [NaiboWang/EasySpider#377]
我输入的网址是http,任务采集的时候会自动使用https,导致任务失败

**Comment by NaiboWang** [comment]
问题发生原因：120之后版本的浏览器自动设置的http强制跳转https策略。
解决方案：Windows平台下载x32版本的EasySpider使用，其他版本请自行更换浏览器和webdriver版本至119版本以下，或使用0.5.0版本的EasySpider。

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/594ea1e5-bf53-4c84-a936-c563392298ba)

**Comment by zhouwenjun0820** [comment]
试运行时http没有强制跳转https，但是真正执行时却强跳，这是为什么呢？
实际上，直接打开EasySpider内置的谷歌浏览器访问也没有强跳
链接比如：http://www.donghua-ml.com/index.php?m=content&c=index&a=lists&catid=10
谢谢

**Comment by NaiboWang** [comment]
我理解这个问题，这是webdriver根据浏览器版本自动控制的，我也没有办法处理，直接按照我上面的操作来就行了。

**Comment by Skura3** [comment]
还有一种办法就是在设计时，在打开网页那里设置一个等待时间，在弹出网页的时候进行手动校正
