### ISSUE TITLE
请问任务模型是否为所有人公用

### ISSUE THREAD

**Issue by includeIostreamUsingnamespace** [NaiboWang/EasySpider#380]
刚下载尝试使用，看到任务栏里面的任务不断的更新，有几点疑问
1. 这是否意味着我建立的任务模型别人也可以使用
2. 任意一个用户对任务执行修改（或删除等操作）后是否其他用户任务栏里面的模型也会随之发生变动
3. 如果上述疑问12成立，是否考虑后续每个用户有单独的空间，方便用户整理自己的模型

因为查看其他issues未找到明确解释
以上感谢您的时间

**Comment by NaiboWang** [comment]
config.json文件里设定了默认服务器地址为localhost，因此所有任务默认都是你本地的任务，跟其他任何用户无关，任务不共享。软件支持通过修改config.json中的服务器地址为远程服务器来使得多用户共享任务，但默认的服务器localhost只是本地服务器。任务文件存放在本地tasks文件夹内，删掉里面的文件就会删除任务。

**Comment by includeIostreamUsingnamespace** [comment]
明白，感谢！
