### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by kmafly** [NaiboWang/EasySpider#382]
打开网页， 对方网址直接报错，返回错误信息：429.
请问如何处理，是否可以增加参数，控制请求次数.

访问的地址如下：
https://www.realestate.com.au/buy/in-forest+lake,+qld+4078%3b/list-1

抓包，返回的信息为： 429 Too Many Requests

**Comment by Jerryzhao83** [comment]
这个信息是对方限制访问了吧。

Seach “429 Too Many Requests” ，as key words。

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by kmafly** [comment]
我查了资料，估计是对方网站做了反爬处理。          用seleium 的  webDriver  模拟浏览器访问，也是一样的问题。
确认对方做了反爬特征码处理。

还有其他办法爬取资料吗？

**Comment by NaiboWang** [comment]
换RPA类软件吧，比如影刀RPA，我这个软件的底层目前是Selenium，只能做到Selenium能做到的事情。

将来有计划更换底层到如playwrite之类的平台，也欢迎大家探索更好用的底层框架提供给EasySpider。
