### ISSUE TITLE
EasySpider不能跳转

### ISSUE THREAD

**Issue by jlcxxzj** [NaiboWang/EasySpider#40]
感谢大佬的项目，调试最新的3.0版本出现问题，无论是源代码运行还是软件，创建新任务时，EasySpider界面并没有进入编辑流程，源代码运行甚至会出现闪退，重启之后不闪退，仍无法进入编辑流程界面

**Comment by jlcxxzj** [comment]
很神奇，当我下2.0版本准备运行的时候，3.0的EasySpider居然能跳转到设计流程界面了

**Comment by NaiboWang** [comment]
OK，能用就可以，如果还有其他问题，请继续提issue。

**Comment by jlcxxzj** [comment]
一晚上没睡，终于在两分钟前debug成功，在Windows使用npm安装项目依赖一直部分报错，导致运行闪退和页面不显示，从换node.js版本到来回删模块，到下载的依赖python和visual studio，折腾了十几个个小时，后续在详细解读，感谢

**Comment by NaiboWang** [comment]
> 一晚上没睡，终于在两分钟前debug成功，在Windows使用npm安装项目依赖一直部分报错，导致运行闪退和页面不显示，从换node.js版本到来回删模块，到下载的依赖python和visual studio，折腾了十几个个小时，后续在详细解读，感谢

不容易，感谢有朋友研究我的代码，希望能一起进步~
