### ISSUE TITLE
0.6.2 采集执行完成后，命令行界面不会自己关闭。gui界面手动采集，还是ps命令行采集，最后的采集命令行都不会自动关闭。

### ISSUE THREAD

**Issue by Jerryzhao83** [NaiboWang/EasySpider#402]
问题如题。

我第一次接触EasySpider，也看了bilibili的教程。
在使用过程中就遇到了这样的问题。

我使用的操作系统是Win11。
采集过程能够顺利执行。

采集完成后，程序会提示我“现在可以安全的关闭此窗口了”。就是不自己关闭。
此时，采集网页窗口，已经自己关闭了。

这是bug还是设计就这样？
我弱弱的问一句。
多谢大佬。

**Comment by NaiboWang** [comment]
就是这样设计的，如果需要命令行自动退出，参考：#220

**Comment by Jerryzhao83** [comment]
多谢大佬抽空回答。昨晚，已经搜索了历史issue，感谢大佬再次确认，感谢赐教。
