### ISSUE TITLE
使用JSON格式保存数据，数据出现重复。

### ISSUE THREAD

**Issue by Jerryzhao83** [NaiboWang/EasySpider#406]
**系统环境：** win11
**EasySpider版本：** 0.6.2

**操作流程：**
打开页面1，提取数据1
打开页面2，提取数据2
打开页面3，提取数据3

**采集数据结果，保存为json格式，**
每次提取数据都选择了“提取数据前清空其他操作字段已记录的值” 和 “此提取数据操作后生成新数据行”。
但是json结果，会分为3个json节点，
第1个节点内，后两个元素为空，只有数据1。
第2个节点内，第3个元素为空，有数据1和数据2。
第3个节点内，3个数据都有。
以上三个数据都为单个元素，非数组。

**希望情况：**
1，每个提取节点单独保存为一个json节点。（感觉此种较好，因为每个提取数据环节可能提取的数据量不同）
2，只保留一个最后json结点，包含所有采集数据。（其实和上面的每个节点单独保存应该一样，因为每个提取数据过程，可能数据量不同）。

请大佬指正，这种需求思考是否正确。

**Comment by Jerryzhao83** [comment]
我重新设计了字段名称，
每次采集的时候
1、使用同样的字段名称。
2、使用同样的提取数据结构。
这样就可以解决了。

**Comment by NaiboWang** [comment]
好的。

**Comment by NaiboWang** [comment]
目前不支持这种做法，你可以拆成三个任务，每个任务一个表格来实现。

**Comment by Jerryzhao83** [comment]
收到。

我现在采用的就是拆成3个任务的方法。
