### ISSUE TITLE
爬取数据的时候会重复爬取内容

### ISSUE THREAD

**Issue by lidey-zr** [NaiboWang/EasySpider#412]
![QQ图片20240602172850](https://github.com/NaiboWang/EasySpider/assets/78307542/40b581b1-f06e-44e8-9352-c18f872b45a9)
![2](https://github.com/NaiboWang/EasySpider/assets/78307542/940f08e8-5501-4d5b-8363-c4d97709ca20)
很简单的一个循环爬取，但是会多次重复内容

**Comment by NaiboWang** [comment]
只靠这张图看不出问题，大概率你循环写的有问题，循环的XPath是什么？最好把任务文件发过来。

**Comment by lidey-zr** [comment]
标签的问题，已经解决！

**Comment by Marinaxia33** [comment]
亲，可以问问具体是哪里出问题了呀，我也是，好苦恼！！

**Comment by zh-sgv** [comment]
提取长文本的时候，取消勾选：

<img width="574" height="295" alt="Image" src="https://github.com/user-attachments/assets/3ca868d7-a739-4aff-a990-4e0fa91ea210" />
