### ISSUE TITLE
任务最终运行时最终定位的Xpath无法进行修改

### ISSUE THREAD

**Issue by l-dawei** [NaiboWang/EasySpider#414]
![image](https://github.com/NaiboWang/EasySpider/assets/56504017/c4c2fad4-24c1-48ce-89b2-beac03697a52)

图片中，我添加了`//*[contains(@class, "Content--contentInner--QVTcU0M")]/div`，结果变成了`/html/body/div[2]/div[3]/div[1]/div[1]/div[3]/div[3]/div[1]/div/a[1]/div[1]//*[contains(@class, "Content--contentInner--QVTcU0M")]/div`，原来的`/html/body/div[2]/div[3]/div[1]/div[1]/div[3]/div[3]/div[1]/div/a[1]/div[1]`删除不了

**Comment by NaiboWang** [comment]
`任务最终运行时最终定位的Xpath`就是让你看到最终程序以哪个XPath来定位元素，不可改动。
`任务最终运行时最终定位的Xpath`由`循环的XPath`和`当前操作的XPath`两部分拼接组成，也就是程序最终会以此XPath来定位元素。
你的例子中，`循环点击每个元素`中设置的XPath为`/html/body/div[2]/div[3]/div[1]/div[1]/div[3]/div[3]/div[1]/div/a[1]/div[1]`，`点击元素`操作设置的XPath为`//*[contains(@class, "Content--contentInner--QVTcU0M")]/div`，所以最终定位的XPath为`/html/body/div[2]/div[3]/div[1]/div[1]/div[3]/div[3]/div[1]/div/a[1]/div[1]//*[contains(@class, "Content--contentInner--QVTcU0M")]/div`。

如果不想要前面这一大串，就把`使用相对循环内的XPath定位到的元素`选项取消勾选。
