### ISSUE TITLE
【Bug】打开网页  工具 ，无法使用

### ISSUE THREAD

**Issue by l-dawei** [NaiboWang/EasySpider#418]
1. 点击开始设计按钮
2. 没有出现之前的"打开网页"标签
![image](https://github.com/NaiboWang/EasySpider/assets/56504017/0162843d-f0aa-40e5-b088-3a77f6d1d177)

3. 使用工具箱里面的 "打开网页" 标签，并设定URL
![image](https://github.com/NaiboWang/EasySpider/assets/56504017/886bd644-24e1-4c37-8bea-92f0648ad237)

4.  URL 为空，并且无法执行任务（没能打开预设的URL）
![image](https://github.com/NaiboWang/EasySpider/assets/56504017/c497ab4c-13dd-47fe-bc73-d1ba585ee776)

**Comment by NaiboWang** [comment]
MacOS就是默认没有打开网页按钮，输入网址开始设计之后才会添加此节点，建议多看看视频再来提issue，你之前问的很多问题也都有讲。
