### ISSUE TITLE
centos编译报错

### ISSUE THREAD

**Issue by dadalongvs** [NaiboWang/EasySpider#419]
修改权限后：
cd ./node_modules/electron/dist/
sudo chown root chrome-sandbox
chmod 4755 chrome-sandbox
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/9051668f-f13f-4255-b2cc-9e413bf9ccb5)

执行npm run start_direct命令还是会有报错：
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/dc8120dd-9e2d-48f6-ba18-1fccbbe23f96)

**Comment by dadalongvs** [comment]
之后在修改 package.json文件
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/d6bd21aa-753f-4239-9cf3-ca9b2b517d85)
之后，npm run start_direct可以运行了，但是无法进入设计任务
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/438b7622-0c5c-4832-ac5a-059b6b1c306b)
且报错
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/c9254769-b2db-4baa-91ea-f6adfa7692da)
我修改了chromedriver_linux64权限，没有用：
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/dc8df506-e739-4958-be3d-6fb435710534)

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/issues/236

**Comment by dadalongvs** [comment]
有按照他改权限，但是还是有报错



---- 回复的原邮件 ----
| 发件人 | Naibo ***@***.***> |
| 日期 | 2024年06月06日 18:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [NaiboWang/EasySpider] centos编译报错 (Issue #419) |

参考：#236

**Comment by NaiboWang** [comment]
CentOS我上面给你发的帖子是成功编译的，但我自己并没有在CentOS上编译过程序，所以也不清楚应该怎么处理。

实在不行，可以执行安装Docker调用Selenium的Docker容器，这样就不需要ChromeDriver这一套东西了。

**Comment by dadalongvs** [comment]
> CentOS我上面给你发的帖子是成功编译的，但我自己并没有在CentOS上编译过程序，所以也不清楚应该怎么处理。
> 
> 实在不行，可以执行安装Docker调用Selenium的Docker容器，这样就不需要ChromeDriver这一套东西了。

easyspider要怎么调用嘞？是要代码里修改添加容器Selenium的ip端口号？

**Comment by NaiboWang** [comment]
去看文档

**Comment by dadalongvs** [comment]
> 去看文档

请问你说的是这一篇文档吗？看了文档还是没懂要怎么调用docker里的selenium chrome。
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/981e5102-f354-4451-ace5-2e6e2106bc1c)
我看他都是在命令执行任务，并且命令里的python3 easyspider_executestage.py --ids [0] --docker_driver http://localhost:4444/wd/hub --user_data 0 --server_address http://localhost:8074 --config_folder "./" --headless 1 --read_type local --config_file_name config.json --saved_file_name中 --docker_driver在0.6.2tag里貌似没有了。

**Comment by dadalongvs** [comment]
> 去看文档

请问你说的是这一篇文档吗？看了文档还是没懂要怎么调用docker里的selenium chrome。
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/a9ec700d-a75a-4464-b166-649d93142682)
我看他都是在调用命令执行任务，没有说如何页面操作时怎么调用docker里的chrome

**Comment by NaiboWang** [comment]
请问这个问题是解决了吗？

**Comment by lelevs** [comment]
> 请问这个问题是解决了吗？

是我自己的问题，我修改完权限后还一直在尝试用root用户运行。。。。只是最后我也没办法在centos上用页面去设计和运行数据爬取，只能用python3 easyspider_executestage.py --ids 运行
