### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by Cjc517** [NaiboWang/EasySpider#420]
在哪里修改能让他自动采集这个组里的同类元素呢，比如这个榜单有50所学校，但是另一个榜单有60所学校，我在第一个榜单选中了50所学校的元素，继续循环点击到第二个榜单的话，他只会采集定义的50个学校，后面10所没有。能不能直接让他采集比如<tr>这个组，里面放的是榜单所有学校。

**Comment by NaiboWang** [comment]
具体需求问题不做答疑，请自行探索软件用法。
