### ISSUE TITLE
下载到一半因网络故障导致中断后，如何继续下载

### ISSUE THREAD

**Issue by LiyanJin** [NaiboWang/EasySpider#423]
正常下载中，网络故障，导致下载中断。可否继续前一个下载任务，而不用重头再下载？
<img width="1440" alt="截屏2024-06-07 22 14 24" src="https://github.com/NaiboWang/EasySpider/assets/18226861/02a1d756-31c7-409f-8338-da62c0184560">

**Comment by NaiboWang** [comment]
不能，Chrome浏览器本身不支持。
