### ISSUE TITLE
十几年码农看不懂怎么修改任务

### ISSUE THREAD

**Issue by try2020-code** [NaiboWang/EasySpider#424]
我知道通过 设计任务进去。。但请看我操作
第一步
![image](https://github.com/NaiboWang/EasySpider/assets/84961646/9ad29060-191e-4c6d-ab1c-4b8faa835778)
第二步
![image](https://github.com/NaiboWang/EasySpider/assets/84961646/991a1705-3342-427c-aed1-223f3403f207)
第三步
![image](https://github.com/NaiboWang/EasySpider/assets/84961646/3892b5ee-925b-4938-9c0a-481440bda7cc)

第四步
![image](https://github.com/NaiboWang/EasySpider/assets/84961646/08f6933f-0b94-4700-aad3-d7221d750465)

第五步
![image](https://github.com/NaiboWang/EasySpider/assets/84961646/ead81987-703c-4c8a-a71e-b62f661c2d5c)

问题在这
![image](https://github.com/NaiboWang/EasySpider/assets/84961646/9726d835-8273-4e8a-985a-bc35b5bcde7e)

告诉我怎么改。。。 试过了。大小没法调

**Comment by NaiboWang** [comment]
两种方式，要么不用手机模式然后按照你的操作方式操作，要么在第四步的图里按方向键右键展开表格右面的操作选项，点击修改任务即可。
第四步的图里面已经写了按方向键浏览表格。
