### ISSUE TITLE
Windows 10 PowerShell Error Message when Execute Task by cmdline with Data Mode

### ISSUE THREAD

**Issue by ReaINapster** [NaiboWang/EasySpider#426]
Hi,
I pasted the command from "Execute task by commandline (Data Mode)" to .ps1 file and ran with PowerShell and this error message came up:
![Capture](https://github.com/NaiboWang/EasySpider/assets/49534214/8dc06da9-8b86-4b86-9291-1dadc92ff713)

Best

**Comment by NaiboWang** [comment]
Do not put your software into a folder whose name contains space and try again.

**Comment by ReaINapster** [comment]
Oh my. That is a quick fix.
Thank you for your instant reply!
