### ISSUE TITLE
软件内置的谷歌浏览器打开http开头的网址会自动更改为https

### ISSUE THREAD

**Issue by Mosw5871** [NaiboWang/EasySpider#434]
尊敬的开发者您好！

我在爬取以http开头的网址的页面内容时，软件自带的谷歌浏览器会强制将网址转换成https开头。并且即使我按照网上教程禁止添加s，但是重新打开浏览器之后又会重置浏览器设置，我之前的设置完全失效了。请问有什么可以解决的方法？

感谢你的贡献！

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/issues/377
