### ISSUE TITLE
程序如何添加代理

### ISSUE THREAD

**Issue by JerryXu2023** [NaiboWang/EasySpider#436]
你好！
请问windows 版的，如何添加代理呢？在gui页面没有找到相关代理设置的地方。
是否可以在哪里设置？谢谢

**Comment by NaiboWang** [comment]
不需要通过程序本身设置代理，你自己原来怎么设置的代理就怎么设置，比如：https://zhuanlan.zhihu.com/p/683246349

**Comment by JerryXu2023** [comment]
理解了，原来直接在chrome里设置代理就可以。谢谢回复
