### ISSUE TITLE
请问计算型的图片验证码如何自动输入

### ISSUE THREAD

**Issue by code2mike** [NaiboWang/EasySpider#440]
针对如下类型的图片验证码如何自动输入
![image](https://github.com/NaiboWang/EasySpider/assets/7035849/1fc5d6e5-5e40-4d02-b032-6ceb05999d3a)

**Comment by NaiboWang** [comment]
由于验证码类型过于多样，没有通用的解决方案，只能通过加载对应验证码识别插件或者自己手动过，或者修改本软件源码手动添加识别验证码的模块。
