### ISSUE TITLE
循环采集多张图片，为什么只采集到最后一张

### ISSUE THREAD

**Issue by Sumptuous** [NaiboWang/EasySpider#445]
<img width="584" alt="采集" src="https://github.com/NaiboWang/EasySpider/assets/16350193/3810d4c0-5f25-47b5-b432-fadf2dfdacc9">

循环采集多张图片，只采集了最后一张，没有按数组的格式输出数据

**Comment by NaiboWang** [comment]
具体需求不做答疑，应该是你的XPath写的有问题。
