### ISSUE TITLE
现在过cf要怎么做啊

### ISSUE THREAD

**Issue by YOYO88888888** [NaiboWang/EasySpider#451]
如题，现在2024年7月1号，我刚刚看b站视频。那个是23年的视频了。现在还能用么。。。有什么方法过啊

**Comment by NaiboWang** [comment]
CloudFlare是一群由专业反爬人员组成的公司，他们的反爬手段每天都在更新，我这边没时间天天跟进这件事情，所以只能看看市面上还有没有其他能解决CF的框架，然后用他们去过。
