### ISSUE TITLE
命令里怎么修改输入参数

### ISSUE THREAD

**Issue by Sumptuous** [NaiboWang/EasySpider#471]
![image](https://github.com/NaiboWang/EasySpider/assets/16350193/3bfe4b29-e4d2-4d54-adbe-05a5876fddcf)

用java定时任务执行命令采集数据，怎么在命令里修改这个输入参数呀

**Comment by miachaellei** [comment]
https://github.com/NaiboWang/EasySpider/wiki/API-Invoke-Example
