### ISSUE TITLE
闪退是为啥啊啊啊啊

### ISSUE THREAD

**Issue by yueqi77** [NaiboWang/EasySpider#473]
按照up的教程调了中国地震网历史查询那个例子，但是执行的时候闪退，看了好几遍，每一步都没错啊呜呜呜

**Comment by LaoBaby815** [comment]
我也是啊。我看了一下好像是点击循环按钮出现问题了。请问你解决了吗？如若，如何处理的？

**Comment by yueqi77** [comment]
我是因为挂了代理，我吧代理关了就没有闪退了
