### ISSUE TITLE
爬取字段出现冗余行，无法消除

### ISSUE THREAD

**Issue by Tovelo95** [NaiboWang/EasySpider#485]
我在同一页面爬取一次后要操作一次再次爬取，造成这样的字段冗余。希望得到帮助^ ^
![QQ图片20240718150714](https://github.com/user-attachments/assets/0846d500-8731-4fea-8e27-67ef4c8f7795)
在excel里会出现两行没有爬取完整的无用数据

**Comment by NaiboWang** [comment]
提取数据操作有“此提取数据操作后生成新数据行”，取消勾选前面的提取数据操作的此选项试一试。

**Comment by Tovelo95** [comment]
谢谢，我已解决，很管用！
