### ISSUE TITLE
执行任务时报错：系统找不到指定文件

### ISSUE THREAD

**Issue by Abulid** [NaiboWang/EasySpider#49]
ERROR:device_event_log_impl.cc(222)] [09:20:54.920] USB: usb_service_win.cc:415 Could not read device interface GUIDs: 系统找不到指定的文件。 (0x2)
![image](https://github.com/NaiboWang/EasySpider/assets/98083927/4e0fc3ad-f244-4336-8cd9-7c5f495952a4)

**Comment by NaiboWang** [comment]
这个错误可以无视，如果任务无法执行，应该是你的任务流程设计的有问题，可以看B站教程视频或者等新版本，新版本会将报错信息直接打印在控制台。
