### ISSUE TITLE
请问如何读取excel一列数据作为输入？外加闪退问题

### ISSUE THREAD

**Issue by SZU-czw** [NaiboWang/EasySpider#491]
easyspider非常好用，做大做强，感谢大佬
但是遇到些小问题解决不了，想提如下需求
1 将excel的一列数据作为keyword进行查询，有没有数据大小或者字符串长度限制，如何读取Excel一列数据作为输入框的参数？

2 win10系统设置了操作后的延时，但是浏览器经常闪退，程序不稳定，是不是可以在软件中嵌入稳定的chrome版本呢？

3web页面输入框输入数据，弹出新页面，但页面还是超链接，再点击超练级，进入到很多下载页面，如何下载该页面附录文件，比如点击就能下载pdf文件或者压缩包？

**Comment by NaiboWang** [comment]
你好，针对你的问题，回答如下：

1. 在调用任务的时候有一个“从Excel读取”的按钮，点开可以看到如何从Excel文件读取参数的指示，同时，也可以按照说明直接在保存任务的时候有一个选项可以指定从Excel读取，直接输入Excel文件路径即可。
2. 目前还没有考虑在软件中嵌入稳定的chrome版本，而是随着chrome更新，但软件打包好的浏览器在win10系统下闪退不稳定可能和软件是否有嵌入稳定的chrome无关，也许是我不知道的其他内容。
3. 对于下载文件，直接设置点击操作就可以自动下载，植入如何点击超链接等操作，直接设计正常流程就可以。

**Comment by SZU-czw** [comment]
感谢大佬
