### ISSUE TITLE
会话持久化

### ISSUE THREAD

**Issue by LeiDoubi** [NaiboWang/EasySpider#492]
正常浏览器只要不退出，会话级别的token 都会有效。
而EasySpider 每次执行一个任务都好像是重新启动了一个session。 导致的结果是每次登陆的时候都需要重新登陆。这个有比较好的解决方案嘛

**Comment by NaiboWang** [comment]
请尝试`带用户信息模式`设计和执行任务。

**Comment by LeiDoubi** [comment]
感谢作者的及时回复。就是使用的 `带用户信息模式` 执行的任务。但是由于token 是session 级别的，所以上次执行任务的token 在下次执行任务的时候，就失效了

**Comment by NaiboWang** [comment]
那需要不关闭浏览器，否则我没有办法解决这个问题…
