### ISSUE TITLE
无法通过无头模式截取京东网页的完整图像

### ISSUE THREAD

**Issue by hellodqy** [NaiboWang/EasySpider#498]
> 使用版本：`v0.6.2`
网址：<https://www.jd.com>

在使用无头模式截取京东首页时，无法获取整个网页的截图，获得的截图大小均为`779 x 579`

设计流程图：
![image](https://github.com/user-attachments/assets/9782a7fc-a083-430c-824a-914d70bc1bbb)

命令行参数：
![image](https://github.com/user-attachments/assets/8f24ed5e-0fdf-401e-a819-05331f0f79bb)

截图：
![1722594136 496926](https://github.com/user-attachments/assets/80435d99-870d-4371-9131-6384df235d40)

**Comment by miachaellei** [comment]
![image](https://github.com/user-attachments/assets/1b8f38b8-64f5-45bc-9cda-4f5d5ad28da4)
任务保存的时候选择最大化窗口试一试。

**Comment by mustedu** [comment]
> ![image](https://private-user-images.githubusercontent.com/161262321/359723686-1b8f38b8-64f5-45bc-9cda-4f5d5ad28da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDcwNDYsIm5iZiI6MTcyNDIwNjc0NiwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzIzNjg2LTFiOGYzOGI4LTY0ZjUtNDViYy05Y2RhLTRmNWQ1YWQyOGRhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjE5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGZlMGM3ZTIxOGVlZmE2YTM3ZDUzMGM4MDQxNTFjMzQ4MWJiNzljOWY1NzM1NjYyMWM4N2MzMTZjMDMwNmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r8k0U8O4eTaoNxj--KAeVWlUM4dentRuY94jG0mtGpo) 任务保存的时候选择最大化窗口试一试。

这个操作界面在哪里呢

**Comment by mustedu** [comment]
@miachaellei您好

**Comment by miachaellei** [comment]
![image](https://github.com/user-attachments/assets/6e456ca4-a333-4978-9cd6-23b802e00f18)
保存任务时弹出的窗口中。
_注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_

**Comment by mustedu** [comment]
> ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_

测试了，我这里还是不行的。

**Comment by miachaellei** [comment]
> > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> 
> 测试了，我这里还是不行的。

有头模式下正常不？

**Comment by mustedu** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> > 
> > 
> > 测试了，我这里还是不行的。
> 
> 有头模式下正常不？



> > > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> > 
> > 
> > 测试了，我这里还是不行的。
> 
> 有头模式下正常不？

有头模式可以调整下窗口大小，但也只能可视画面，无法全屏（滚动）截到下面的

**Comment by miachaellei** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> > > 
> > > 
> > > 测试了，我这里还是不行的。
> > 
> > 
> > 有头模式下正常不？
> 
> > > > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> > > 
> > > 
> > > 测试了，我这里还是不行的。
> > 
> > 
> > 有头模式下正常不？
> 
> 有头模式可以调整下窗口大小，但也只能可视画面，无法全屏（滚动）截到下面的

嗯，这里需要自己写代码通过多段截图后再拼接了。
还有一个思路可以找个插件试试。

**Comment by mustedu** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> > > > 
> > > > 
> > > > 测试了，我这里还是不行的。
> > > 
> > > 
> > > 有头模式下正常不？
> > 
> > 
> > > > > ![image](https://private-user-images.githubusercontent.com/161262321/359724912-6e456ca4-a333-4978-9cd6-23b802e00f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDc1MjksIm5iZiI6MTcyNDIwNzIyOSwicGF0aCI6Ii8xNjEyNjIzMjEvMzU5NzI0OTEyLTZlNDU2Y2E0LWEzMzMtNDk3OC05Y2Q2LTIzYjgwMmUwMGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwMjI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGViMjIzZmZiYzkyNTJmNjU5ODc3NjI0ZTc5MDU2ZTVmMTkxNTdiMGFmNjgzY2RhZTM0N2VmZDhiNjA3MTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HKPi2D_2O_Sh2TdzsrzKmnTIsZL2MwiK9NRv43izo3s) 保存任务时弹出的窗口中。 _注：即便最大化窗口截图可能也无法实现整个网页的截图，可能需要写代码实现多段截图的拼接才行。_
> > > > 
> > > > 
> > > > 测试了，我这里还是不行的。
> > > 
> > > 
> > > 有头模式下正常不？
> > 
> > 
> > 有头模式可以调整下窗口大小，但也只能可视画面，无法全屏（滚动）截到下面的
> 
> 嗯，这里需要自己写代码通过多段截图后再拼接了。 还有一个思路可以找个插件试试。

https://www.bilibili.com/video/BV1ch4y1E7cn/?spm_id_from=333.788&vd_source=782df057ad87366ec3b1578359214a8d
这个教程上，也没有代码及插件。您那边方便分享下吗？谢谢

**Comment by NaiboWang** [comment]
示例任务：[348.json](https://github.com/user-attachments/files/16685600/348.json)

在截图操作前添加`自定义操作`，`执行模式`为`执行Python代码`，代码为：`self.browser.set_window_size(1800, 19600)`，即把窗口大小设置为1800x19600，可自定义调整。

执行时用命令行使用`无头模式`执行即可获得完整截图：

![1724210412 047355](https://github.com/user-attachments/assets/931e03bb-68d3-475b-acbf-7b827809d60a)

**Comment by mustedu** [comment]
> 示例任务：[348.json](https://github.com/user-attachments/files/16685600/348.json)
> 
> 在截图操作前添加`自定义操作`，`执行模式`为`执行Python代码`，代码为：`self.browser.set_window_size(1800, 19600)`，即把窗口大小设置为1800x19600，可自定义调整。
> 
> 执行时用命令行使用`无头模式`执行（`--headless 1`）即可获得完整截图：
> 
> ![1724210412 047355](https://private-user-images.githubusercontent.com/30287768/359735640-931e03bb-68d3-475b-acbf-7b827809d60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTUwNzYsIm5iZiI6MTcyNDIxNDc3NiwicGF0aCI6Ii8zMDI4Nzc2OC8zNTk3MzU2NDAtOTMxZTAzYmItNjhkMy00NzViLWFjYmYtN2I4Mjc4MDlkNjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA0MzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDRkNmRjNWNmMzE4ODFhYWRmNDFiMzNhNmZhNTYxMDBhNDBmZjVlZTVhODcyNzA0MzNmZGM2ZDAzOGY1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Isz89_8AmJV-syW7co94riRQYkx_8aOChIAI1Pgr2ek)

无头模式下，无法进行登录。

**Comment by NaiboWang** [comment]
尝试带用户信息模式

**Comment by mustedu** [comment]
> 尝试带用户信息模式

用--headless 0可以登录，但截图是不全的
用--headless 1不能登录。

**Comment by NaiboWang** [comment]
那可能暂时无解了， 如果看到其他类似工具有实现此功能，可以在这里给出，我会参考他的实现。

**Comment by mustedu** [comment]
> 那可能暂时无解了， 如果看到其他类似工具有实现此功能，可以在这里给出，我会参考他的实现。

好嘞，谢谢

**Comment by Steven-spec-gif** [comment]
不使用无头模式目前版本没办法截取整个网页，部分网页打开了无头模式定位元素可能会定位不到，可以执行自定义python代码逐次截屏然后拼接成一个完整的图片，代码如下。感谢up，如果能出一期自主添加options.add_argument的教程或者在命令行里面加入相应的参数位置就太棒了。
sys.path.append(r"C:\Users\15596\AppData\Local\Programs\Python\Python310\Lib\site-packages") # 假设此路径下有PIL库
from PIL import Image
import io
import time

driver = self.browser

# 获取页面尺寸（不包括滚动条）
total_width = driver.execute_script("return document.documentElement.scrollWidth")
total_height = driver.execute_script("return document.documentElement.scrollHeight")
viewport_width = driver.execute_script("return document.documentElement.clientWidth")
viewport_height = driver.execute_script("return document.documentElement.clientHeight")

# 创建一个空白图像
stitched_image = Image.new('RGB', (total_width, total_height))
previous = 0

while previous < total_height:
    # 如果不是第一次截图，则滚动窗口
    if previous != 0:
        scroll_position = min(previous, total_height - viewport_height)
        driver.execute_script(f"window.scrollTo(0, {scroll_position});")

        # 等待浏览器加载新内容并稳定下来
        time.sleep(1)  # 根据需要调整等待时间

        # 因为滚动可能导致页面重排，再次获取视窗高度
        viewport_height = driver.execute_script("return document.documentElement.clientHeight")

    # 截图
    screenshot = driver.get_screenshot_as_png()
    img = Image.open(io.BytesIO(screenshot))

    # 计算粘贴截图到空白图像的位置
    paste_position = (0, previous)

    # 更新位置，对于最后一屏不再增加
    previous += viewport_height

    # 如果剩余部分小于等于视窗高度，则表示已经到达底部
    remaining_height = total_height - (previous - viewport_height)
    if previous >= total_height or remaining_height <= viewport_height:
        # 对于最后一屏，调整粘贴位置以覆盖部分倒数第二屏
        paste_position = (0, total_height - viewport_height)
        stitched_image.paste(img, paste_position)
        break

    # 粘贴截图到空白图像
    stitched_image.paste(img, paste_position)

# 保存最终的长图
filename = f'{self.myVar}full_page.png'
stitched_image.save(filename)
print(f"Full page screenshot saved as '{filename}'")

# 增量操作应该放在文件保存之后
self.myVar += 1
