### ISSUE TITLE
为什么运行的时候C盘空间一直在减少

### ISSUE THREAD

**Issue by CoCu888** [NaiboWang/EasySpider#499]
为什么运行的时候C盘空间一直在减少，它运行过程中产生的临时文件存储在哪里

**Comment by NaiboWang** [comment]
C:\windows\systemtemp去看看这个文件夹，及时删除用过的临时文件。

**Comment by CoCu888** [comment]
> C:\windows\systemtemp去看看这个文件夹，及时删除用过的临时文件。

这个目录我看了，不是这个文件产生的数据
今天用了一天，C盘少了五个G，我每次都是等待窗口提示清理完之后才进行关闭，但是使用的时候C盘可用容量依旧减少

**Comment by NaiboWang** [comment]
看一下EasySpider目录下有没有`TempUserDataFolder`目录，有的话运行完成后删掉即可。

**Comment by CoCu888** [comment]
这个目录下没有文件，个人猜测是系统数据缓存，昨天用工具清缓存，C盘空间恢复了很多

**Comment by copylian** [comment]
C盘会变少很多，只能删除 %temp%下的文件
