### ISSUE TITLE
自定义操作，执行系统级命令，调用python, 返回的中文乱码

### ISSUE THREAD

**Issue by xyz371292552** [NaiboWang/EasySpider#510]
本人新手，想实现的功能，通过自定义操作，执行python代码，通过web上的api接口获取需要采集的中文标题，写入需要采集的目标网站搜索框。遇到以下问题，耗费大量时间未果，特此求助作者。

easyspider 版本 0.6.2  本地系统 windows 11  python 版本3.9.6

python 内容
 # -*- coding: utf-8 -*-
import requests
import json
url = "本地web接口返回需要抓取的内容中文标题"
response = requests.get(url)
if response.status_code == 200:
    data = response.content
    json_string = json.loads(data)
    print(json_string['key_word'])

以上代码本地测试能正常显示返回的内容，但是在easyspider中使用自定义操作 执行系统命令调用该py代码时，返回内容为乱码。
确定返回字符串类型为utf-8, 查看 easyspider 中 easyspider_executestage.py源代码，发现在818行注释了该段代码 “ # output = subprocess.run(code, capture_output=True, text=True, timeout=max_wait_time, encoding="utf-8", shell=True)”  ，尝试在本地复现问题，
本地使用 819行代码 output = subprocess.run(code, capture_output=True, text=True, timeout=max_wait_time, shell=True)， 也中文乱码，但是使用注释的代码后能正常返回中文。不知道这个地方代码中的 encoding="utf-8" 为什么会被注释掉，本人尝试自己编译easyspider代码太多报错未果，尝试过很多办法：例如修改系统cmd返回字符串编码等等，花费了几天时间也没都没能解决这个问题。特此求助作者。（在哔哩哔哩上反复看了这个视频"可视化爬虫易采集EasySpider：如何执行自己写的JS代码和系统代码 （自定义操作）"，每一步核对，但是还是未能解决问题。）

**Comment by NaiboWang** [comment]
建议观看：https://www.bilibili.com/video/BV1VE421P7yj/

如何编译EasySpider的过程一步一步写的很清楚。

**Comment by xyz371292552** [comment]
编译不了是我的问题，可能是环境，也可能是网络，作者大大，我现在这个情况有啥办法帮帮我给点什么建议之类的。跪谢了

**Comment by NaiboWang** [comment]
时间太长了我也不太记得为什么要注释掉utf-8……可能是因为加上这个会导致程序调用出问题，所以我的意思是你直接下载源码从头编译，然后直接执行出你想要的结果即可。

**Comment by xyz371292552** [comment]
好的 好的，我再试试，非常感谢您百忙之中抽出时间来回复我，非常感谢
