### ISSUE TITLE
如果我停止循环的条件是页数>5，该怎么操作啊？

### ISSUE THREAD

**Issue by lelevs** [NaiboWang/EasySpider#516]
![image](https://github.com/user-attachments/assets/57115760-24f7-430f-868d-145529bbdfd8)
![image](https://github.com/user-attachments/assets/2e55b9b8-4a29-47d0-9f8d-ae6a6756a408)
或是
![image](https://github.com/user-attachments/assets/3dc70940-6d34-4e3e-a7a9-b2590be88bac)
都不生效

**Comment by lelevs** [comment]
我的循环是不固定元素列表

**Comment by NaiboWang** [comment]
应该使用`退出当前循环`操作：
![image](https://github.com/user-attachments/assets/53eb12bf-9bab-4bab-b9d5-56ef6c73c5b3)
