### ISSUE TITLE
在插入点击元素时，无法选中导航栏信息。

### ISSUE THREAD

**Issue by websky123** [NaiboWang/EasySpider#521]
![Image_1724143498881.png](https://github.com/user-attachments/assets/c462ee7a-a488-4f83-9a69-fbd4524dd9f4)
如上图，有个网址，在点击导航栏内某按钮后出现的新界面网址和原网址相同，所以要有个手动点击导航栏某按钮操作，但导航栏的按钮好像无法选中进行插入点击操作。

**Comment by miachaellei** [comment]
用鼠标右键点击

**Comment by websky123** [comment]
是用的右键选中，选中的位置也变色了，但操作台无反应。> 用鼠标右键点击

**Comment by miachaellei** [comment]
实在不行可以用点击元素功能试试
![image](https://github.com/user-attachments/assets/ccb15b08-f730-4930-86f1-70a696499080)

**Comment by NaiboWang** [comment]
鼠标右键选不中时，可以鼠标移动到元素后，按键盘的`F7`来选中元素。

**Comment by NaiboWang** [comment]
先点击一下页面上其他元素，然后取消选择，然后再按`F7`，如果弹出下面的框，就先点开`Turn On`:

![image](https://github.com/user-attachments/assets/adf06714-cf76-4344-a0fc-a1ace861d51b)
