### ISSUE TITLE
下载文件

### ISSUE THREAD

**Issue by Sumptuous** [NaiboWang/EasySpider#522]
1、如何设置浏览器的文件下载位置
2、Excel导出文件，会在文件名上加一串字符，如何设置不修改源文件名
3、Excel导出文件，如何设置固定的名称

**Comment by NaiboWang** [comment]
以上问题需要全部下载源码编译运行解决，逻辑在`ExecuteStage/utils.py`的`rename_downloaded_file`函数中。

**Comment by devilpie** [comment]
您好，我在utils.py里做了文件路径的修改，并重新编译打包了文件，但是最后下载保存文件还是在默认路径。
