### ISSUE TITLE
arm64 unbuntu22 运行报错

### ISSUE THREAD

**Issue by MisteryLiuCode** [NaiboWang/EasySpider#523]
我用mac开了个虚拟机，电脑是m芯片的，运行报错
cannot execute binary file: Exec format error
是因为arm版本的原因吗
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/5c938596-cd74-4374-a971-e06f9797ee14">

**Comment by NaiboWang** [comment]
也许是，我没试过，但是M系列芯片上装Windows是可以直接运行的，可以尝试编译运行看有没有问题。

**Comment by MisteryLiuCode** [comment]
好的，我换unbuntu运行也报错了，用的服务器，x86的，可以直接运行的版本
[0822/162509.897964:FATAL:electron_main_delegate.cc(294)] Running as root without --no-sandbox is not supported.
