### ISSUE TITLE
无图形界面unbuntu系统如何运行

### ISSUE THREAD

**Issue by MisteryLiuCode** [NaiboWang/EasySpider#525]
使用./easy-spider.sh运行报错，使用的root账号运行的
[0822/162509.897964:FATAL:electron_main_delegate.cc(294)] Running as root without --no-sandbox is not supported.

**Comment by NaiboWang** [comment]
不能直接用root执行。

**Comment by MisteryLiuCode** [comment]
我用非root用户运行报错
<img width="1293" alt="图片" src="https://github.com/user-attachments/assets/39d27206-d9b4-493f-bf2e-dda7a23c01e5">

**Comment by MisteryLiuCode** [comment]
希望可以帮忙看一下，整了好几天了

**Comment by NaiboWang** [comment]
这个ubuntu有图形界面吗？

**Comment by MisteryLiuCode** [comment]
没有图形界面

**Comment by NaiboWang** [comment]
没有图形界面只能通过Docker运行，参考：https://github.com/NaiboWang/EasySpider/wiki/Docker%E8%BF%90%E8%A1%8C%E7%A4%BA%E4%BE%8B

**Comment by NaiboWang** [comment]
有图形界面可以不用docker，没有图形界面必须用docker，和是否为服务器无关。

**Comment by MisteryLiuCode** [comment]
好的，明白了。我只是用来运行任务，我以为用linux版本也可以

**Comment by NaiboWang** [comment]
运行任务可以用Linux版本，只是无图形界面的Linux需要借助docker来运行任务，有图形界面的Linux可以直接运行任务。

**Comment by MisteryLiuCode** [comment]
我看到迁移任务不能迁移用户信息，那么在无界面的unbuntu怎么设置用户信息呢？

**Comment by NaiboWang** [comment]
docker版本运行可以通过vnc viewer连接到浏览器端的可视化界面，从而看到浏览器执行过程的，去试试。
