### ISSUE TITLE
记录一下docker携带用户信息时启动失败报错，给后面的同学帮助

### ISSUE THREAD

**Issue by xiaokeng2hao** [NaiboWang/EasySpider#532]
把EasySpider集成到后端时发现在Linux系统上携带用户信息时一直报错启动失败，后面去研究源码时发现，在复制user_data时并没有复制到映射docker的挂在目录，以下是没改之前的代码在（/ExecuteStage/easyspider_executestage.py）：
![1724842638637](https://github.com/user-attachments/assets/6100b402-b4aa-44e2-92fa-a16ba555806f)
下面是修改后的代码：
![image](https://github.com/user-attachments/assets/1ab8bca3-4480-4ea2-83cc-19a3c196129e)
同时在创建docker时使用下面的命令：
`sudo docker run -d -p 4444:4444 --name selenium-chrome --shm-size="4g" \
    -v /home/ubuntu/data:/data \
    -u root \
    selenium/standalone-chrome`
    
    /home/ubuntu/data为宿主机目录
    /data为docker目录

**Comment by NaiboWang** [comment]
感谢发现问题，将在下个版本修复此Bug。
