### ISSUE TITLE
可以在自定义操作里添加mysql数据库语句编写吗？并将结果值作为字段操作？

### ISSUE THREAD

**Issue by PW-Studio** [NaiboWang/EasySpider#534]
比如select * from xxx，查询的结果可以作为字段操作；或者进行增删改之类的操作

**Comment by PW-Studio** [comment]
比如select * from xxx，查询的结果可以作为字段操作；或者进行增删改之类的操作

**Comment by NaiboWang** [comment]
理论上可以，参考程序自带的插件myCode.py的写法，但过于复杂的操作建议直接下载源代码修改运行会更合适一点。
