### ISSUE TITLE
设计任务时测试循环内js判断成功，但是在执行任务时提示JavaScript execution failed

### ISSUE THREAD

**Issue by CyfZsj** [NaiboWang/EasySpider#535]
操作步骤：本地直接执行（纯净模式）
报错log：
2024-08-30 15:14:36.497603: 执行节点|Execute node: 判断1层结点是否需要展开
2024-08-30 15:14:36.497655: Execute JavaScript for element:return arguments[0].innerText.includes("营销")
2024-08-30 15:14:36.497662: 对元素执行JavaScript:return arguments[0].innerText.includes("营销")
2024-08-30 15:14:36.500151: JavaScript execution failed
2024-08-30 15:14:36.500184: 判断条件内所有条件分支的条件都不满足|None of the conditions in the 
设计流程时，提示条件满足：
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/8867e784-bc9b-4c8c-ba44-f0a4c02e8f01">
环境： macos 13.1
Google Chrome版本：128.0.6613.114（正式版本） (arm64)

**Comment by NaiboWang** [comment]
看流程看不出太大问题，也许是判断的时候页面元素没有加载完成导致检测不到，或者XPath发生了变化？

实在操作不了，建议直接下载代码调试。

**Comment by CyfZsj** [comment]
好吧   我调了好久没调好，决定不用js判断了，每个节点都循环尝试循环展开子节点，超时就跳过，好像也可以实现。
但是我这个任务放到linux服务器上执行   就不行了，会报错：执行节点<二级目录循环>时出错，将继续执行，错误为： list index out of range然后那一层的节点没有完整爬取到，会跳出循环到上层循环里继续执行

**Comment by blueoblue** [comment]
你的日志里会自动记录js代码而执行状态吗，我这只显示“执行代码，，，”，并不显示执行状态。而且，似乎不会带代码进行检查，随便输入也显示执行。
![image](https://github.com/user-attachments/assets/6e6c25bc-183d-4e7c-aca3-11f0a825fe59)
1处是随便输入的，2处“arguments”拼写错误，日志里没有有任何提示。
 所以，你是添加日志输出吗？

**Comment by NaiboWang** [comment]
> 你的日志里会自动记录js代码而执行状态吗，我这只显示“执行代码，，，”，并不显示执行状态。而且，似乎不会带代码进行检查，随便输入也显示执行。 ![image](https://private-user-images.githubusercontent.com/38844134/377753616-6e6c25bc-183d-4e7c-aca3-11f0a825fe59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDE4ODAsIm5iZiI6MTcyOTI0MTU4MCwicGF0aCI6Ii8zODg0NDEzNC8zNzc3NTM2MTYtNmU2YzI1YmMtMTgzZC00ZTdjLWFjYTMtMTFmMGE4MjVmZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA4NTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOTRmZjg2OWQ2YjIyZWE1MDlhNTU1MjljNDVjNmRlM2I5ZDU5ODQxMGY2ZTkxZWQ0ODI5YWI4NzQ1NjI5MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8xsK_d_ZhvA10nASovWG-7yXQdt3bv3-xf3rAmHXdg4) 1处是随便输入的，2处“arguments”拼写错误，日志里没有有任何提示。 所以，你是添加日志输出吗？

`12314564`从JS本身的角度出发是一个正确的JS语句，可以被执行不会出问题。

而另外一个语句，目前确实没有记录错误是什么，已经在最新代码中修复，可以下载最新源码运行。
