### ISSUE TITLE
命令执行任务，设置了无头模式不生效

### ISSUE THREAD

**Issue by Gotodie** [NaiboWang/EasySpider#542]
只能桌面执行命令/easyspider_executestage --ids '[10]' --user_data 1 --server_address http://localhost:8074 --config_folder "/opt/wfcloud/EasySpider-master/ElectronJS/" --headless 0 --read_type local --config_file_name config.json --saved_file_name
,如果xshell远程报错
![image](https://github.com/user-attachments/assets/8249dac0-166c-4a10-8ee4-31d9c8975a61)

**Comment by NaiboWang** [comment]
没有图形界面的Linux请使用Docker版本连接Docker运行程序。

**Comment by Gotodie** [comment]
> 没有图形界面的Linux请使用Docker版本连接Docker运行程序，包括远程XShell也算是无GUI版本的环境。

启动了docker容器：
![image](https://github.com/user-attachments/assets/12abfb2b-f836-439e-ba81-91ecedba8865)
运行时也产生了报错：
![image](https://github.com/user-attachments/assets/02f7e840-fed0-4b74-a4ef-05c9bd82faf7)

**Comment by NaiboWang** [comment]
从Github下载最新源码进行编译。

**Comment by Gotodie** [comment]
> 从Github下载最新源码进行编译。

docker方式部署还需要按照原本的3个目录下那些步骤进行编译吗？

**Comment by NaiboWang** [comment]
> > 从Github下载最新源码进行编译。
> 
> docker方式部署还需要按照原本的3个目录下那些步骤进行编译吗？

需要，只不过是连接的selenium程序不是本地程序而是docker了。

**Comment by Gotodie** [comment]
> > > 从Github下载最新源码进行编译。
> > 
> > 
> > docker方式部署还需要按照原本的3个目录下那些步骤进行编译吗？
> 
> 需要，只不过是连接的selenium程序不是本地程序而是docker了。

easyspider_executestage.py文件里chrome/chromedriver的目录还需要改？用docker应该就用不到本地的chrome了吧？

**Comment by NaiboWang** [comment]
如果是docker就不需要改本地了

**Comment by Gotodie** [comment]
> 如果是docker就不需要改本地了

我更换了0.6.2的版本
![image](https://github.com/user-attachments/assets/86e361d5-b9ed-4c00-ac93-5169a418ad01)

**Comment by NaiboWang** [comment]
https://github.com/NaiboWang/EasySpider/releases/download/v0.6.2/EasySpider_0.6.2_Linux_x64_with_docker_support.tar.xz

用这个

**Comment by Gotodie** [comment]
这个是二进制吗？不能修改代码然后编译？

**Comment by NaiboWang** [comment]
> 这个是二进制吗？不能修改代码然后编译？

需要修改代码然后编译你就直接从Github Clone最新的代码。

**Comment by Gotodie** [comment]
> > 这个是二进制吗？不能修改代码然后编译？
> 
> 需要修改代码然后编译你就直接从Github Clone最新的代码。

那这个二进制里面是添加了对docker的支持？我需要自己添加进去？

**Comment by NaiboWang** [comment]
二进制里面添加了对docker的支持，最新的源码也支持，不清楚你是不是下载错了，如果是正确的不应该报你说的错误，2186行定义了docker_driver的变量。

config = {
        "ids": [0],
        "saved_file_name": "",
        "user_data": False,
        "config_folder": "",
        "config_file_name": "config.json",
        "read_type": "remote",
        "headless": False,
        "server_address": "http://localhost:8074",
        "keyboard": True,  # 是否监听键盘输入
        "pause_key": "p",  # 暂停键
        "version": "0.6.2",
        "docker_driver": "",
    }

**Comment by NaiboWang** [comment]
不是从Release里找，你直接下载最新的就行了，这个功能是0.6.2版本发布之后加的：

git clone https://github.com/NaiboWang/EasySpider.git

**Comment by Gotodie** [comment]
用了docker是不是就没有办法像纯原码编译出来的调接口生成id，然后执行命令，调的接口里可以传参我想要搜索的内容？
用了docker，我修改用到的execution_instances下的json文件里
{"id":1,"name":"inputText_1","nodeName":"输入文字","nodeId":2,"desc":"要输入的文本，如京东搜索框>输入：电脑","type":"text","exampleValue":"","value":""}]
的value值，也没什么用。

**Comment by Gotodie** [comment]
怎么在linux环境下调用docker爬取小红书这种必须要登录的软件？docker方式好像不会同步打开网页，还是可以通过什么配置可以同步打开网页？

**Comment by Gotodie** [comment]
如果只是改--user_data的参数，当我该参数是1时
![image](https://github.com/user-attachments/assets/b64f5bc6-36cf-4472-8bd2-8500c34bd8f6)
会报错：
![image](https://github.com/user-attachments/assets/222b7f8f-4170-4419-8e76-53577b7e4fbe)


但参数是0时不会有报错，但也不会读取用户配置。

**Comment by Gotodie** [comment]
按照#532修改后，根据输出结果来看，小红书应该还是登录失败，因为根据设计流程里的xpath，均找不到要素
