### ISSUE TITLE
某东商品详情页，拿不到售价等信息，怀疑h5st校验不过

### ISSUE THREAD

**Issue by yifen259** [NaiboWang/EasySpider#545]
某东商品详情页，拿不到售价等信息，怀疑h5st校验不过。
获取售价的异步接口返回403。
可能是浏览器环境检测的参数有问题？

**Comment by yifen259** [comment]
可能是浏览器环境检测的参数有问题？

**Comment by 973440710** [comment]
你好，请问呢解决了吗？，现在接口只要是easyspider进去的都直接403了
