### ISSUE TITLE
爬取特定页面时跳转到about:blank

### ISSUE THREAD

**Issue by bz-2021** [NaiboWang/EasySpider#547]
https://talent.baidu.com/jobs/list 这是我的目标网站，进行流程设计时无法正常加载出页面，会跳转到about:blank

**Comment by NaiboWang** [comment]
网站有反爬，不能用Selenium框架来做，请尝试其他自动化测试框架如puppeteer或playwright，如果成功可以反馈到这里，我会考虑更换底层架构。
