### ISSUE TITLE
关于-自定义操作调用浏览器打印问题

### ISSUE THREAD

**Issue by lishuaijun** [NaiboWang/EasySpider#558]
需求：讲页面批量保存为pdf
我的方法：通过打印页面实现，[自定义操作] 调用js脚本 window.print(); 
问题1：打印弹窗弹出后，脚本无法识别弹窗内，故而无法点击打印的保存按钮
问题2：是否有自动隐藏操作台的功能，目前是手动点击×号进行关闭

![image](https://github.com/user-attachments/assets/74ba9f1f-7144-416f-a124-1af2fc401b71)

**Comment by NaiboWang** [comment]
第一个问题无法直接实现，建议下载源码并添加类似下面的建议内容：

模拟打印操作并在打印对话框中发送 Enter 键是一个比较特殊且挑战性的任务，因为 Selenium 本身不支持直接与浏览器的系统对话框（如打印对话框）交互。不过，你仍然可以尝试使用一些方法来实现，依赖于特定的环境设置和额外的库。

方法一：使用键盘快捷键触发打印

可以通过 Selenium 发送 Ctrl+P 来打开浏览器的打印对话框（以 Chrome 浏览器为例）。然后，你可以利用其他工具（如 PyAutoGUI 或 AutoIt）来发送 Enter 键，以确认打印对话框中的打印操作。

首先，你需要安装 PyAutoGUI：

pip install pyautogui
 
接着，使用 Selenium 配合 PyAutoGUI 来模拟整个流程：
```Python
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pyautogui

# 设置 ChromeDriver 路径
driver = webdriver.Chrome()

# 打开一个页面
driver.get("http://example.com")

# 触发打开打印对话框
driver.find_element_by_tag_name('body').send_keys(Keys.CONTROL + 'p')

# 等待打印对话框完全加载
time.sleep(2)  # 实际的等待时间可能需要调整

# 使用 PyAutoGUI 发送 Enter 键选择默认打印机并打印
pyautogui.press('enter')  # 假设打印对话框已经聚焦在“打印”按钮上

# 在结束之前等待足够长的时间确保命令发出
time.sleep(2)

# 关闭浏览器
driver.quit()
```

注意和考量事项: 
1. 时间延迟: time.sleep() 在这个例子中用于等待打印对话框加载。这不是最佳实践，因为固定的时间延迟可能无法适应所有环境和情况。在实际应用中，需要根据实际情况灵活调整。 

2. 焦点问题: 这个脚本假设在执行 pyautogui.press('enter') 时，打印按钮已经处于聚焦状态。实际情况可能会因操作系统、浏览器版本等因素而异，有时还得考虑屏幕分辨率和对话框内部布局差异。 

3. 操作系统和环境差异: 不同的操作系统或浏览器可能需要不同的键盘快捷键或操作步骤。

在实际部署此类自动化脚本时，建议充分测试并考虑到可能的异常情况，以确保脚本的稳定性和可靠性。


第二个问题比较容易解决，执行下面的JavaScript代码即可：

```JS
document.getElementById("wrapperToolkit").style.display='none'
```

**Comment by lishuaijun** [comment]
感谢老师支持！！！
