### ISSUE TITLE
滑块验证码如何解决？

### ISSUE THREAD

**Issue by xiaowang0519** [NaiboWang/EasySpider#568]
![Uploading 微信图片_20240928104100.png…]()

**Comment by xiaowang0519** [comment]
感谢您的回复，目前还没有解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月30日 18:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [NaiboWang/EasySpider] 滑块验证码如何解决？ (Issue #568) |

请问解决了吗

**Comment by NaiboWang** [comment]
你好，你这张图片没有传成功，对于滑块验证码一般选择手动过验证或者是用相关的验证码插件去处理，比如我们软件官网提到的那个验证码处理插件。

**Comment by wzy-sxj** [comment]
> 你好，你这张图片没有传成功，对于滑块验证码一般选择手动过验证或者是用相关的验证码插件去处理，比如我们软件官网提到的那个验证码处理插件。

<img width="703" alt="微信图片_20241130212948" src="https://github.com/user-attachments/assets/ffbea263-6b2b-4a06-b0dd-6189b7a12639">
手动验证就会这样出错，那个插件好像也处理不了滑块

**Comment by NaiboWang** [comment]
这个问题涉及到网站的反爬机制，可能需要以后才能解决。
