### ISSUE TITLE
能否设置使用的浏览器

### ISSUE THREAD

**Issue by LiCanhui-Huyi** [NaiboWang/EasySpider#57]
easyspider默认使用的是谷歌浏览器，但是我平常使用的是edge，想请问能否设置成默认使用edge

**Comment by NaiboWang** [comment]
Edge用的也是和Chrome一样的Chromium内核，因此用起来应该没区别，有什么需求是只有Edge才能做吗？
为了使得用户打开就能用，所以在压缩包里面自带了Chrome, 防止有些用户电脑上没有安装Chrome, 因此如果实在想要更换浏览器需要自行修改代码编译打包运行。

**Comment by mwc-123** [comment]
可是我这个默认打开的是edge，但是电脑上按得有谷歌。

**Comment by NaiboWang** [comment]
打包好的版本是谷歌浏览器，如果想要换其他浏览器请自行下载代码编译运行。用户电脑上有没有安装谷歌与本程序没有直接关联，都可以用。

**Comment by wd4455** [comment]
谷歌浏览器可以直接复制一个替换自带的版本吗?

**Comment by NaiboWang** [comment]
> 谷歌浏览器可以直接复制一个替换自带的版本吗?

需要同时替换webdriver，具体请看ElectronJS文件夹下的Readme编译说明。

**Comment by Blue-Class** [comment]
up，您好，我想设置成使用edge访问，但是并不会 自行修改代码编译打包运行，能否出的教程，我跟着做，谢谢您
