### ISSUE TITLE
和其他商业爬虫软件有什么区别吗

### ISSUE THREAD

**Issue by Mr-brillianter** [NaiboWang/EasySpider#58]

**Comment by NaiboWang** [comment]
不想多解释，说多了容易引战。这个软件除了完全免费无广告和开源以外，可以去看看其他同类型软件的价格列表中的功能，这个软件基本都有。

同时，v0.3.1里新增的功能目前几乎所有的商业软件都没有，包括你提到的那款：

https://github.com/NaiboWang/EasySpider/releases/tag/v0.3.1

欢迎同时下载下来比较。

其实软件是有专利授权的，只不过合作者大气让大家免费用，感兴趣的话可以查一查专利的最后一个发明人是谁：https://github.com/NaiboWang/EasySpider/blob/master/media/patent.png

欢迎推荐给其他朋友~
