### ISSUE TITLE
怎样实现不记录要输入账号密码的流程？

### ISSUE THREAD

**Issue by gumuqing** [NaiboWang/EasySpider#581]
@NaiboWang 作者你好，请问下对于需要登录的页面，要输入账号密码的，怎样在流程中实现不记录登录操作？
参考了视频“如何爬取需要登录才能爬的网站”，里面通过扫码方式登录进去。如果是通过输入账号密码方式，要怎样操作只记录【打开网页】这个流程就能跳转到页面中，不记录账号密码输入登录流程？

**Comment by touero** [comment]
对于部分网站不会记住的登录状态，在webdriver下，每次启动的都是新的chrome，所以你需要有一个登录操作。
如果不想登录有几种办法可能办到:
- 保存登录信息token、cookie的等，下次启动带着这个信息启动访问网站
- webdriver每次启动都是有一个随机的临时的配置文件（linux在temp， windows我不确定），你可以固定每次都是使用同一个
- 直接使用你本地chrome的配置，这样也能保持登录，同时如果你使用本地的配置还会包含你自己使用的插件

**Comment by NaiboWang** [comment]
输入账号密码和视频中的操作方式一样，进入“带用户信息的模式”，第一次设计过程中，先手动选中输入框，按键盘的F9获得输入框输入焦点，此时可以输入账号和密码且不会记录在任务流程中，登录进去后，以后再次执行“带用户信息模式”即可无需登录进行访问。
