### ISSUE TITLE
OCR中如何指定语言

### ISSUE THREAD

**Issue by zhukefucn** [NaiboWang/EasySpider#582]
在安装Tessract时安装了多种语言，如何在OCR中指定语言。tessract本身有语言选项，但不知道ES在那个地方配置调用的？

**Comment by NaiboWang** [comment]
Tesseract是老版本用的OCR系统，最新版本用的是ddddocr，默认是中英文+数字识别，如果需要修改语言则需要自己去修改源代码编译运行。

**Comment by zhukefucn** [comment]
大神您好！

        给您一个建议，可以在这阶段请大家边学习边收集一些模板，到时候您发布新版本大家就更加喜欢了。这是看八爪鱼得到的启发



致

礼！
=======================================
蒋韧    战略技术中心
江苏润和软件股份有限公司
手机☏：13817558226 
***@***.*** 
地址ி：南京市雨花台区软件大道168号润和创智中心
=====================================

 
发件人： Naibo Wang
发送时间： 2024-10-24 18:57
收件人： NaiboWang/EasySpider
抄送： zhukefucn; Author
主题： Re: [NaiboWang/EasySpider] OCR中如何指定语言 (Issue #582)
Tesseract是老版本用的OCR系统，最新版本用的是ddddocr，默认是中英文+数字识别，如果需要修改语言则需要自己去修改源代码编译运行。
