### ISSUE TITLE
智能验证Easyspider点击后变为从左往右拖的再次验证

### ISSUE THREAD

**Issue by jszzm63** [NaiboWang/EasySpider#59]
登录页面，输入用户名、密码后有个智能验证，正常手工登录点击后显示验证成功，但Easyspider点击后变成从左往右拖的再次验证，请教该如何处理？

正常界面：
![MGXSP(2Y0UUU0QGA(2O4QNU](https://github.com/NaiboWang/EasySpider/assets/134822182/fe8f8db6-3a23-41d3-b44c-7e1432bc7158)

Easyspider自动运行界面：
![T3I3S QUWZS` H`FY` F{CI](https://github.com/NaiboWang/EasySpider/assets/134822182/0a8e1d4f-cda3-4b29-a2d2-8ec5a5e62ca4)

**Comment by NaiboWang** [comment]
先看下这两个视频，然后如果验证码是只需要登录一次的操作的话，手动处理一下就行了，设置好打开网页之后的等待时间，比如打开网页后等个15秒用来留出时间手动处理验证码。
[如何无代码可视化的爬取需要登录才能爬的网站 - 知乎网站案例](https://www.bilibili.com/video/BV1HV4y1r7v8)
[如何爬需要输入验证码的网站](https://www.bilibili.com/video/BV18c411K7FH)

另外不是还有手机一键登录吗，用手机也行的。

**Comment by jszzm63** [comment]
谢谢指点。因为注册用户是公司领导手机，所以手机一键登录不太好弄，那只有采取手动处理了。
