### ISSUE TITLE
mac上的使用问题

### ISSUE THREAD

**Issue by directorxu0899** [NaiboWang/EasySpider#598]
darwin ('64bit', '')
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2266, in <module>
  File "selenium/webdriver/chromium/options.py", line 101, in add_extension
OSError: Path to the extension doesn't exist
[3124] Failed to execute script 'easyspider_executestage' due to unhandled exception!
运行终端时，一直出现此类错误，应该如何解决

**Comment by NaiboWang** [comment]
从哪里下载的软件？easyspider_executestage程序同目录是否有EasySpider.app程序存在？

**Comment by huiqimao** [comment]
出现一样的问题，从https://github.com/NaiboWang/EasySpider/releases下载，mac apple silicon版本；easyspider_executestage程序同EasySpider.app程序同在一个目录

**Comment by huiqimao** [comment]
Hi，Naibo，感谢您的回信，我已经找到问题了。刚开始没有按照指引中的commend
line进行操作，而是直接运行【easyspider_executestage】程序就会导致报错。如果按照指引的命令
“./easyspider_executestage --ids '[1]' --user_data 0 --headless 0
--read_type local --config_file_name config.json --saved_file_name xxx.csv”
运行就会正常了。谢谢哈！

Best，
Joe

Naibo Wang ***@***.***> 于2024年11月26日周二 18:48写道：

**Comment by NaiboWang** [comment]
好的
