### ISSUE TITLE
How to make it more popular?

### ISSUE THREAD

**Issue by bernadetteemiliya82** [NaiboWang/EasySpider#60]
Hi,

Could you tell me where you bought the stars for this repo and the price?  It has pretty high quality! 

Sincerely
Bernadette

**Comment by NaiboWang** [comment]
Come on bro, I didn't "buy" the stars, but I do have some propaganda, such as Zhihu.com, Weibo.com, Bilibili.com and others see this:

https://github.com/NaiboWang/EasySpider/issues/21

Then three days ago it is on Github Trending list: 
![github](https://github.com/NaiboWang/EasySpider/assets/30287768/cb3ca4e1-11bf-44da-96d4-1e243c25f68c)

So all stars are "Free"!!!
