### ISSUE TITLE
表格中的数据如何同类型匹配并且保存为一行数据

### ISSUE THREAD

**Issue by AntiEoom** [NaiboWang/EasySpider#605]
## 版本信息 ｜ Version Information
**EasySpider版本 ｜ EasySpider Version**:  0.6.2
**系统版本（架构） ｜ System Version (Architecture)**:  windows10
**浏览器版本 ｜ Browser Version**:  chrome 124.0.6367.61
**安装方式 ｜ Installation method**: EasySpider_0.6.2_Windows_x64.7z

## 问题描述 ｜ Issue Description
我想采集的数据 [地址 ](https://lpl.qq.com/)，里面赛程列表，我想将每一场的比赛数据保存为一行数据。
具体数据为：日期 + 时间 ，战队1 + 战队2
![image](https://github.com/user-attachments/assets/3a3ef552-9f25-4c12-b7ef-bfca38a09b12)

## 如何复现 ｜ Steps to Reproduce
我在进行选择的时候，点击了上面的日期+时间可以将同类型元素带出来，但是在我选择完 日期 + 时间 + 战队1 + 战队2时就无法将同类型元素全部带出来了。

最终希望的效果是：日期 + 时间 ，战队1， 战队2

我如何设置都没法获取处理，求大佬指点

**Comment by touero** [comment]
不太理解你的意思
![image](https://github.com/user-attachments/assets/d9e6eeb8-0f22-47c9-b177-62dc8e4d7758)
你的意思是你要获取全部`日期 + 时间 ，战队1 + 战队2`吗，例如上图，然后点击下一页继续获取吗？  
但是你说选择 `日期 + 时间 + 战队1 + 战队2`这个页面并没有选择这些选项的地方。

**Comment by AntiEoom** [comment]
`不太明白你的意思 是你要获取全部吗，例如上图，然后点击下一页继续获取吗？`
是的，我是需要获取全部数据，并且尽量将保存下来的excel的数据列为：日期，时间，战队1，战队2

下图中描述了我的操作

![image](https://github.com/user-attachments/assets/3667bf23-69a0-4448-8e3a-5ccf4d5a46b3)

**Comment by touero** [comment]
你应该获取日期，时间，战队1，战队2的xpath，然后遍历获取内容就可以了啊

**Comment by AntiEoom** [comment]
> 你应该获取日期，时间，战队1，战队2的xpath，然后遍历获取内容就可以了啊

这一步操作要自己手动获取嘛，因为我是通过右键一个个选择的。

选择上面的时间还可以将所有的时间全部自动选择， 但是再加上战队就没法全部选择上了😥

**Comment by touero** [comment]
作者也提供了xpathHelper

日期：//span[@class="span2"]
时间：//span[@class="span3"]
战队：//li[@class="gamelist-item"]/div/a

这样能够获取全部的信息了

Plus：连已结束的也会获取到，网页直接加载出来的，可能都不需要翻页操作
![image](https://github.com/user-attachments/assets/425c46c6-7064-40da-a1a7-c77b468281d1)

**Comment by AntiEoom** [comment]
明白了，感谢大佬指导~
