### ISSUE TITLE
windwos定时采集完后，怎么自动关闭浏览器和黑窗口呢

### ISSUE THREAD

**Issue by luoyuyimeng** [NaiboWang/EasySpider#607]
用的这个：
cd E:\Users\EasySpider_windows_x64\
./EasySpider/resources/app/chrome_win64/easyspider_executestage.exe --id [123] --user_data 0 --server_address http://localhost:8074 --config_folder "E:/Users/EasySpider_windows_x64/" --headless 0 --read_type local --config_file_name config.json --saved_file_name

**Comment by cheneygan** [comment]
您好，请问这个怎么解决呢
