### ISSUE TITLE
（脑洞向）看着那个flow图，就想到这个UI有没有可能用blockly库去实现

### ISSUE THREAD

**Issue by yowynn** [NaiboWang/EasySpider#608]
## 版本信息 ｜ Version Information
**EasySpider版本 ｜ EasySpider Version**:  
**系统版本（架构） ｜ System Version (Architecture)**:  
**浏览器版本 ｜ Browser Version**:  
**安装方式 ｜ Installation method**:

## 如何复现 ｜ Steps to Reproduce
![20241119205742_msedge_BPoUxB](https://github.com/user-attachments/assets/27b70cd9-08b0-43fb-9845-4d4742d7d3ae)

非问题反馈，只是单纯有个看示例的时候有个小想法，有没有想过用 blocky库去做那个 flow 的 UI 哈哈

**Comment by NaiboWang** [comment]
感谢建议，目前还没有人力去换UI，将来可能会考虑。
