### ISSUE TITLE
多个流程节点提取不同数据的问题

### ISSUE THREAD

**Issue by ITKing80** [NaiboWang/EasySpider#61]
我在流程中的不同节点提取不同的数据，但是我发现每次都生成新的一行数据。
比如我在4个节点提取4个字段，会生成4条数据，最后一条数据是完整。

这个是我使用方式不正确吗？应该如何设置？

**Comment by NaiboWang** [comment]
查看以下issue理解提取流程：
https://github.com/NaiboWang/EasySpider/issues/34
