### ISSUE TITLE
编译 打包后  运行出错

### ISSUE THREAD

**Issue by WenLiang619** [NaiboWang/EasySpider#610]
我的系统 win64，win11系统，按照视频编译和打包0.6.2版本的三个文件并最后组装。可以设计任务，但是  点击“本地直接执行（纯净模式）”报错，不知道哪里出了问题。请抽空看下？谢谢。
![error](https://github.com/user-attachments/assets/5be196e2-330b-453c-a975-dde0e375594b)

**Comment by NaiboWang** [comment]
直接打开EasySpider.exe是不能运行程序的，需要运行ElectronJS文件夹中Readme里提到的的打包命令，所有打包的程序才能在`.temp_to_pub`文件夹下打包好Release版本并正确运行：

For windows x64, run the following command to release
clean_and_release_win64.cmd

**Comment by WenLiang619** [comment]
ElectronJS目录下执行package_win64.cmd后在
C:\Users\u243216\Desktop\EasySpider-master\ElectronJS\out\EasySpider-win32-x64 下有EasySpider.exe文件，运行它可以设计任务，执行还是出现上面图片的错误。

如果执行
package_win64.cmd
clean_and_release_win64.cmd
out文件夹就空了。

我的是win11 64位系统，编译打包过程中没有出现.temp_to_pub文件夹呢？

**Comment by NaiboWang** [comment]
.temp_to_pub是个项目主目录下的隐藏文件夹，你先设置显示隐藏文件和文件夹，然后在.temp_to_pub文件夹里面找到Windows 64位版本下打包好的程序，双击打开exe就可以。

**Comment by WenLiang619** [comment]
package_win64.cmd
clean_and_release_win64.cmd

执行上面语句后 在C:\Users\u243216\Desktop\EasySpider-master\.temp_to_pub\EasySpider_windows_x64 下执行EasySpider.exe也是可以设计，本地运行 就报上面图示的错误！

**Comment by WenLiang619** [comment]
npm run package后，运行C:\Users\u243216\Desktop\EasySpider-master\.temp_to_pub\EasySpider_windows_x64\EasySpider
下exe文件后，本地执行还是上面图示报错。

命令行执行
“cd C:\Users\u243216\Desktop\EasySpider-master\.temp_to_pub\EasySpider_windows_x64\
./EasySpider/resources/app/chrome_win64/easyspider_executestage.exe --ids [2] --user_data 0 --server_address http://localhost:8074 --config_folder "C:/Users/u243216/Desktop/EasySpider-master/.temp_to_pub/EasySpider_windows_x64/" --headless 0 --read_type local --config_file_name config.json --saved_file_name ”
到是可以执行程序。

**Comment by WenLiang619** [comment]
> package_win64.cmd clean_and_release_win64.cmd
> 
> 执行上面语句后 在C:\Users\u243216\Desktop\EasySpider-master.temp_to_pub\EasySpider_windows_x64 下执行EasySpider.exe也是可以设计，本地运行 就报上面图示的错误！

此种情形下，命令行执行是可以的。

**Comment by NaiboWang** [comment]
C:\Users\u243216\Desktop\EasySpider-master\temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64文件夹下有没有execute_win64.bat文件？

**Comment by NaiboWang** [comment]
同时，C:\Users\u243216\Desktop\EasySpider-master\temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64文件夹下有没有execute.bat文件？

**Comment by WenLiang619** [comment]
> C:\Users\u243216\Desktop\EasySpider-master\temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64文件夹下有没有execute_win64.bat文件？

execute_win64.bat 有的。

**Comment by WenLiang619** [comment]
> 同时，C:\Users\u243216\Desktop\EasySpider-master\temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64文件夹下有没有execute.bat文件？

没有execute.bat

**Comment by NaiboWang** [comment]
execute_win64.bat改名成execute.bat再试试。

**Comment by WenLiang619** [comment]
> execute_win64.bat改名成execute.bat再试试。

把C:\Users\u243216\Desktop\EasySpider-master\.temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64下面的execute_win64.bat改名成execute.bat后运行C:\Users\u243216\Desktop\EasySpider-master\.temp_to_pub\EasySpider_windows_x64\EasySpider下面的EasySpider.exe运行程序，设计任务和执行任务（本地执行和命令行执行）都可以了！    

下载的master文件C:\Users\u243216\Desktop\EasySpider-master\ElectronJS目录里只有execute_win64.bat、execute_win32.bat、execute_macos.sh和execute_linux64.sh并没有execute.bat文件；C:\Users\u243216\Desktop\EasySpider-master\ElectronJS\README.md文件里是这样描述的“把此文件夹内的stealth.min.js和execute.bat文件拷贝入chrome文件夹内”。

**Comment by NaiboWang** [comment]
是的，这个问题是我之前文档写的有点不太清楚，感谢帮忙纠正，现在已经更新了文档。
