### ISSUE TITLE
懂车帝页面详情，页面详情下载图片失败

### ISSUE THREAD

**Issue by WenLiang619** [NaiboWang/EasySpider#611]
按照视频讲解照做，发现图片无法下载。请问是什么原因？ Xpath使用视频中的写法。
![err22](https://github.com/user-attachments/assets/b6b52930-acac-4ea2-bfe0-16f859e6cfed)

**Comment by WenLiang619** [comment]
> 按照视频讲解照做，发现图片无法下载。请问是什么原因？ Xpath使用视频中的写法。 ![err22](https://private-user-images.githubusercontent.com/37403373/390283424-b6b52930-acac-4ea2-bfe0-16f859e6cfed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODkwNjEsIm5iZiI6MTczMjY4ODc2MSwicGF0aCI6Ii8zNzQwMzM3My8zOTAyODM0MjQtYjZiNTI5MzAtYWNhYy00ZWEyLWJmZTAtMTZmODU5ZTZjZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA2MjYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNDY0NzVhMTkzZjEwZTAxNWE3YzI0MGM2N2NiNWQ4MzYwZWUxNjYxOWU3NjQ2M2RhYzQ4YWI3ODZiMjE2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wg0CygW3uz4pn33LIuLwF293f855gw2l8tZP_A5EWIw)

![err22](https://github.com/user-attachments/assets/d6716365-2a4b-4e37-9fba-55d87f7dc8c0)
我VS调试也是这样，下载图片失败，搜索关键词“下载图片失败”为何在py 文件里找不到呢？

**Comment by touero** [comment]
能否提供下载图片报错之前的一些日志，目前这样看是因为路径不正确，代码中有两个地方都有可能会抛出这个错，需要其他日志确认一下。

**Comment by WenLiang619** [comment]
> 能否提供下载图片报错之前的一些日志，目前这样看是因为路径不正确，代码中有两个地方都有可能会抛出这个错，需要其他日志确认一下。

![err2222](https://github.com/user-attachments/assets/ef66b95d-4b02-4bbb-b870-231f91edff75)
断点调试发现这里好像有错？
`save_path = os.path.join(save_directory, new_file_name)`

**Comment by NaiboWang** [comment]
网站应该是改版了，从错误来看应该是文件名不能有冒号，你可以尝试手动改一下你框出来的代码部分，删掉所有的冒号再试试，这个问题将来会被修复。

**Comment by WenLiang619** [comment]
> 网站的文件名格式应该是改版了，从错误来看应该是文件名不能有冒号导致的问题，你可以尝试手动改一下你框出来的代码部分，删掉所有的冒号再试试，这个问题将来会被修复。

备忘，记录下：
1.  utils.py中做如下修改
```
          # 构建保存路径
            save_path_temp = os.path.join(save_directory, new_file_name)
            save_path = save_path_temp.replace(":","")
```。
2. 在ExecuteStage目录下无需虚拟环境运行 **.\generateEXE_win64.cmd**打包执行阶段程序，把执行阶段程序打包成`exe`文件(dist\easyspider_executestage.exe)并自动拷贝到`../ElectronJS/chrome_win64/`目录下。
3. 切换到ElectronJS目录下依次运行**.\package_win64.cmd**和.**\clean_and_release_win64.cmd**将easyspider_executestage.exe拷贝到**.temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64**。
4. **注意：**此时**.temp_to_pub\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64**目录下的'execute_win64.bat'需要改名为‘execute.bat’。 这是一个bug，期待修复。

.temp_to_pub\EasySpider_windows_x64下的应用程序可以下载图片了。

**Comment by WenLiang619** [comment]
.temp_to_pub\EasySpider_windows_x64 和.temp_to_pub\EasySpider_windows_x64\EasySpider 目录下都有一个文件EasySpider.exe。运行任意一个都能正常使用程序，他们有什么区别？

**Comment by NaiboWang** [comment]
前者点击直接执行任务可以直接执行相关任务，后者不行，其实前者的作用更像是一个快捷方式，不然用户打开看到文件夹里面一堆文件不知道要打开哪一个来运行。

**Comment by WenLiang619** [comment]
> 前者点击直接执行任务可以直接执行相关任务，后者不行，其实前者的作用更像是一个快捷方式，不然用户打开看到文件夹里面一堆文件不知道要打开哪一个来运行。

二者 都可以 执行程序 。
