### ISSUE TITLE
api调用获取任务id后 命令行调用提示The key 'id' is not exist in your preset configuration dict, please check if you input the correct name.

### ISSUE THREAD

**Issue by tlotht** [NaiboWang/EasySpider#612]
## 版本信息 ｜ Version Information
**EasySpider版本 ｜最新:  
**系统版本（架构） ｜ windows 10:  
**浏览器版本 ｜google:  
**安装方式 ｜ :github官网下载安装

## 问题描述 ｜ Issue Description
通过api获取到任务id已经成功 
我使用ruby编程 获取任务id代码如下
                                          url = URI.parse('http://localhost:8074/invokeTask')
                                          params = {
                                            id: '387',
                                            params: '{"urlList_0": "https://image.baidu.com/", "loopText_1": "拙政园大门"}'
                                          }
                                          response = RestClient.post(url.to_s, params, {
                                            'User-Agent' => 'Apifox/1.0.0 (https://apifox.com)',
                                            'Accept' => '*/*',
                                            'Host' => 'localhost:8074',
                                            'Accept-Encoding' => 'gzip, deflate, br',
                                            'Connection' => 'keep-alive',
                                            'Content-Type' => 'application/x-www-form-urlencoded'
                                          })
                                          if response.code == 200
                                            begin
                                              # 尝试解析响应体为JSON
                                              result = JSON.parse(response.body)
                                              task_execution_id = result
                                              puts "任务启动成功，任务ID：#{task_execution_id}"
                                            rescue JSON::ParserError
                                              puts "响应内容不是有效的JSON格式: #{response.body}"
                                            rescue => e
                                              puts "发生错误：#{e.message}"
                                            end
                                          else
                                            puts "任务启动失败，状态码：#{response.code}"
                                          end

运行会输出 任务启动成功，任务ID：111

然后参考文档 在命令行中调用 我运行了命令： 
      cd D:\easyspider\EasySpider_windows_x64
      .\EasySpider\resources\app\chrome_win64\easyspider_executestage.exe --id [111] --user_data 0 --server_address http://localhost:8074 --config_folder "D:\easyspider\EasySpider_windows_x64\EasySpider\resources\app\node_modules\object-inspect\test\element.js" --headless 0 --read_type remote --config_file_name config.json --saved_file_name [result.xlsx]

  文件路径是因为easyspider_executestage.exe 在D:\easyspider\EasySpider_windows_x64\EasySpider\resources\app\chrome_win64目录下  element.js文件在D:\easyspider\EasySpider_windows_x64\EasySpider\resources\app\node_modules\object-inspect\test 目录下 并且其他路径也没办法运行 
运行结果为
        [1;31mThe key 'id' is not exist in your preset configuration dict, please check if you input the correct name.
        [0m
        Traceback (most recent call last):
          File "easyspider_executestage.py", line 2257, in <module>
          File "commandline_config\commandline_config.py", line 107, in __init__
          File "commandline_config\commandline_config.py", line 139, in set_command_line
          File "commandline_config\commandline_config.py", line 209, in convert_type
        UnboundLocalError: cannot access local variable 'variable' where it is not associated with a value
        [7888] Failed to execute script 'easyspider_executestage' due to unhandled exception!
        
        Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
        [1;32mpip index versions commandline_config
        pip install commandline --upgrade[0m
        
        D:\easyspider\EasySpider_windows_x64>.\EasySpider\resources\app\chrome_win64\easyspider_executestage.exe --id [111] --user_data 0 --server_address http://localhost:8074 --config_folder "D:\easyspider\EasySpider_windows_x64\EasySpider\resources\app\node_modules\object-inspect\test\element.js" --headless 0 --read_type remote --config_file_name config.json --saved_file_name [result.xlsx]
        [1;31mThe key 'id' is not exist in your preset configuration dict, please check if you input the correct name.
        [0m
        Traceback (most recent call last):
          File "easyspider_executestage.py", line 2257, in <module>
          File "commandline_config\commandline_config.py", line 107, in __init__
          File "commandline_config\commandline_config.py", line 139, in set_command_line
          File "commandline_config\commandline_config.py", line 209, in convert_type
        UnboundLocalError: cannot access local variable 'variable' where it is not associated with a value
        [16796] Failed to execute script 'easyspider_executestage' due to unhandled exception!
        
        Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
        [1;32mpip index versions commandline_config
        pip install commandline --upgrade[0m
似乎不应该使用id作为参数 或者我其他地方做的不对 可以为我指出吗
## 如何复现 ｜ Steps to Reproduce
开发者如果可以使用api方式获取任务id 并且成功调用 可以告诉我如何填写文件目录并且正确的参数名吗

**Comment by NaiboWang** [comment]
把命令行里的`--id`改为`--ids`，其余不变，最新版本已经可以同时指定多个id号以实现并行多开，如指定`--ids [37, 38]`即可同时并行执行id号为`37`和`38`的程序。

API调用文档已同步更新。

**Comment by tlotht** [comment]
感谢 改为--ids调用成功了
