### ISSUE TITLE
如果获取文本列表循环中获取本次循环的文本值

### ISSUE THREAD

**Issue by jackychenccty** [NaiboWang/EasySpider#616]
#601 # 版本信息 ｜ Version Information
**EasySpider版本 ｜ EasySpider Version**:  0.6.2
**系统版本（架构） ｜ System Version (Architecture)**:  
**浏览器版本 ｜ Browser Version**:  
**安装方式 ｜ Installation method**:

## 问题描述 ｜ Issue Description
我想达到的效果是，循环输入查询关键字(配置文本列表循环)，在文章列表进入文章详情，在提取内容中添加一列，记录该详情属于哪个关键字。
我想在下图执行python代码，让当前循环的文本赋值到变量中，或者是否有更好的方式，能在提取的数据中，直接设置字段的值为当前循环的文本值
![image](https://github.com/user-attachments/assets/18934ecc-5c64-4397-ac3c-f50c80634ae6)

**Comment by touero** [comment]
我不知道你为什么要在这个issue中提到`pr 601`，你应该删除他，在我看来它们没有任何关联。

我不确定你的表述是否为：
`遍历关键字列表` -> `出现文章列表` -> `遍历文章` -> `获取第一列` -> `记录符合哪一个关键字`

**Comment by jackychenccty** [comment]
> 我不知道你为什么要在这个issue中提到`pr 601`，你应该删除他，在我看来它们没有任何关联。
> 
> 我不确定你的表述是否为： `遍历关键字列表` -> `出现文章列表` -> `遍历文章` -> `获取第一列` -> `记录符合哪一个关键字`

是的，最终想达到的效果下图
![image](https://github.com/user-attachments/assets/3c2e95a5-ee0a-4c0e-82fe-d16cb22dec0b)

**Comment by jackychenccty** [comment]
已解决，输入关键字后提取查询框的文本，就可以采集到同一行的列中了
