### ISSUE TITLE
linux版的操作流程

### ISSUE THREAD

**Issue by Kozon2015** [NaiboWang/EasySpider#62]
求一版linux下的运行流程，另外就是任务的json文件是怎么生成的

**Comment by NaiboWang** [comment]
Ubuntu 20及以上版本可以直接下载运行的，其他Linux发行版需要自行编译，你可以下载Ubuntu版本的试一试，怎么运行压缩包里的txt文件都说明了。
Json文件生成后会放入tasks文件夹，怎么生成的就需要看源代码了，不是一两句话能说清楚的。

**Comment by Gzj369** [comment]
@NaiboWang 大佬，请问Centos版本，怎么自行编译呢，有操作说明吗？

**Comment by NaiboWang** [comment]
下载代码后按照Readme.md文件的说明一步一步来即可。
