### ISSUE TITLE
关于编写javascript脚本执行时好时坏的案例

### ISSUE THREAD

**Issue by ChenGengZhiGZ** [NaiboWang/EasySpider#63]
任务目的，采集一个电商网站的类目，并将其进行自定义排列。
网站：https://www.fruugo.co.uk/sets-snap-fasteners-kit-tool-metal-snap-buttons-rings-with-fastener-pliers-press/p-144913113-305735011
![image](https://github.com/NaiboWang/EasySpider/assets/49011332/9e4b3a10-caa6-4c7a-9929-20fe57cb3593)
元素所在位置前端解析：
我写的脚本语言是：
return
arguments[0].innerTextreplaceAll(‘\n','').trim().replace(/\s{2,}/g,' > ')
其实就是先把获取元素的innerText整理一下，把换行符号去掉，再去掉前后的空格，最后得到的格式是中间带有多个空格，把它们替换成符号 >来连接。
**单个链接跑了一次，是成功的**
![微信截图_20230530140407](https://github.com/NaiboWang/EasySpider/assets/49011332/3042c540-7bfc-40bc-962b-8b97a6ff1664)

**当我跑20个链接以上，就又不行了**
![image](https://github.com/NaiboWang/EasySpider/assets/49011332/3f9cafa8-26ea-48db-b4ec-6b7f43b03497)

**Comment by NaiboWang** [comment]
把你的任务json文件发到我邮箱naibowang@foxmail.com我去调试下看看，包括你的所有20条链接也发一下。

**Comment by NaiboWang** [comment]
看到消息回一下，不然无法帮忙处理问题。
