### ISSUE TITLE
[bug]cannot load 'Python3'

### ISSUE THREAD

**Issue by niaiwomattt** [NaiboWang/EasySpider#65]
cannot load 'Python3'

系统：Mac 10.14.6

Python3 命令行调用良好，报这个错，请问如何解决？

**Comment by NaiboWang** [comment]
是直接下载的可执行程序，在执行./easyspider_executestage的时候报的错吗？还是下载的源代码然后运行的？

**Comment by niaiwomattt** [comment]
> 是直接下载的可执行程序，在执行./easyspider_executestage的时候报的错吗？还是下载的源代码然后运行的？

对，直接下载 release 里的 mac 程序，按照文档设计了一个采集，然后点击【本地直接执行】，然后 cd 到解压的目录，执行代码就报错了。

**Comment by NaiboWang** [comment]
能不能给个文件夹和命令行的截图，我这边复现不了。

**Comment by niaiwomattt** [comment]
<img width="800" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/2947859/c258ff78-7ba5-4b3f-977d-ce15c9fb5a0f">

```shell
cd 你的EasySpider文件夹，如：cd /Users/你的用户名/Downloads/EasySpider_MacOS_all_arch
./easyspider_executestage --id '[3]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/panbing/Library/Application Support/EasySpider/" --headless 0 --read_type remote --config_file_name config.json --saved_file_name 
```

路径中没有中文

**Comment by NaiboWang** [comment]
命令行执行的截图也发一下

**Comment by niaiwomattt** [comment]
<img width="480" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/2947859/6d9c2670-38cf-4376-8127-b43aa2ec16e3">

**Comment by NaiboWang** [comment]
已经可以复现你的问题，请先下载V0.2.0版本的EasySpider使用，我这边今天尝试修复此Bug，修复后会回复。

**Comment by NaiboWang** [comment]
你这个操作系统版本太低了，所以那个程序有些兼容性问题不能直接用，但是有办法编译运行，方式为：
1. 下载源代码：
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/e5cdc73e-ada8-431d-a61a-aaaec660fb62)
2. 解压后，打开命令行，进入`ExecuteStage`文件夹，然后运行`pip3 install`命令：
```
cd Downloads/EasySpider-master/ExecuteStage
pip3 install -r requirements.txt
```
3. 拷贝`easyspider_executestage.py`文件到之前下载好的EasySpider文件夹（带`easyspider_executestage`可执行文件的那个文件夹）：

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/e2ab65cc-0990-4606-8806-73e33114612d)

4. 命令行进入此文件夹，然后将提示命令中的`./easyspider_executestage`替换成`python3 easyspider_executestage.py` 后面不变：

```shell
cd 你的EasySpider文件夹，如：cd /Users/你的用户名/Downloads/EasySpider_MacOS_all_arch
python3 easyspider_executestage.py --id '[3]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/panbing/Library/Application Support/EasySpider/" --headless 0 --read_type remote --config_file_name config.json --saved_file_name 
```

即可执行任务。
