### ISSUE TITLE
移动到元素问题

### ISSUE THREAD

**Issue by oooing** [NaiboWang/EasySpider#66]
我不清楚是我操作理解问题还是有bug哈。我先描述下情况，网页是瀑布楼的，我先滚动列表页页到底部，然后使用移动到元素（目的是回到列表页第一个元素进行后续操作），但发现移动不了（也尝试直接点击不添加移动，也不行），提示找不到这个元素。
感谢提供这么好的工具！

openPage
Loading page: https://civitai.com/images
Click
Click
Cannot find element://*[@id="913751"]/div[1]/a[1]/img[1], please try to set the wait time before executing this operation
Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=113.0.5672.93)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00C18893+48451]
	(No symbol) [0x00BAB8A1]
	(No symbol) [0x00AB5058]
	(No symbol) [0x00AB83F1]
	(No symbol) [0x00AB9DEB]
	(No symbol) [0x00B0CDD9]
	(No symbol) [0x00AFA2BC]
	(No symbol) [0x00B0C482]
	(No symbol) [0x00AFA0B6]
	(No symbol) [0x00AD7E08]
	(No symbol) [0x00AD8F2D]
	GetHandleVerifier [0x00E78E3A+2540266]
	GetHandleVerifier [0x00EB8959+2801161]
	GetHandleVerifier [0x00EB295C+2776588]
	GetHandleVerifier [0x00CA2280+612144]
	(No symbol) [0x00BB4F6C]
	(No symbol) [0x00BB11D8]
	(No symbol) [0x00BB12BB]
	(No symbol) [0x00BA4857]
	BaseThreadInitThunk [0x76467D59+25]
	RtlInitializeExceptionChain [0x7729B74B+107]
	RtlClearBits [0x7729B6CF+191]

**Comment by NaiboWang** [comment]
首先就是回到第一个元素不需要鼠标移动到元素这个操作，页面上只要第一个元素还存在就可以直接进行其他操作。

那可能真的就是找不到这个元素，我打开你这个页面是找不到的，是不是XPath有问题？你用设计任务时自带的XPath Helper插件定位一下这个元素看能不能找到。

而且有的时候设计任务的时候能找到，执行任务的时候页面就找不到这个元素了也很正常，另一种情况就是这个元素是只有鼠标移动到某位置或者在屏幕可见区域的时候才能显示出来，其他时候会被删掉，所以要审查一下元素。

**Comment by oooing** [comment]
我试过不滚动页面是可以取到的，滚动后就不行了，同样的xpath，你说的几种情况我再试试，感谢回复！

**Comment by oooing** [comment]
是它把元素删了，我现在滚几屏后，在用移动到元素回滚到首屏，就可以继续操作了，感谢

**Comment by NaiboWang** [comment]
好的👌🏻
