### ISSUE TITLE
ocr识别

### ISSUE THREAD

**Issue by Kozon2015** [NaiboWang/EasySpider#67]
大佬，可以修改源码调用的tesserract库吗，有的话是在哪个代码文件

**Comment by NaiboWang** [comment]
https://github.com/NaiboWang/EasySpider/blob/master/ExecuteStage/easyspider_executestage.py

861行

有更好用的OCR库也可以推荐下。

**Comment by Kozon2015** [comment]
paddleocr

**Comment by NaiboWang** [comment]
paddleocr需要先预装paddlepaddle，安装包过大且不易打包到程序中去……
所以想用paddleocr的朋友可以自行修改源码，当然如果找到一种轻量级的方式使用paddleocr，欢迎提交Pull Request~

**Comment by masterzht** [comment]
ddddocr
