### ISSUE TITLE
讲讲架构

### ISSUE THREAD

**Issue by niaiwomattt** [NaiboWang/EasySpider#70]
可不可以讲讲你的架构，我想参考你的架构做个程序。
我知道你的程序是使用 Python 调用 selenium ，但是你这个图形界面是怎么搞的？
期望有时间出个架构图和简单讲解，谢谢大神。

**Comment by NaiboWang** [comment]
看这个：
https://github.com/NaiboWang/EasySpider/blob/master/Docs/面向WEB应用的智能化服务封装系统设计与实现.pdf
