### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by PhoenixMarco02** [NaiboWang/EasySpider#71]
本人mac，版本11.6.7，之前下载了0.3.1版本，能成功打开、成功使用。但是在复现作者mac版ebay案例的视频时，结果csv始终为空。后来终端报错“cannot create temporary directory”、"Failed to extract ...: decompression resulted in return code -1!"。再后来EasySpider已经无法打开，报错如下：
<img width="259" alt="截屏2023-06-05 11 49 17" src="https://github.com/NaiboWang/EasySpider/assets/135573107/57a8b366-5916-4f22-8754-cf4e0b6aa3c0">

<img width="259" alt="截屏2023-06-05 11 49 29" src="https://github.com/NaiboWang/EasySpider/assets/135573107/32e1029e-b857-437d-b175-47184288d239">

望作者回复！

**Comment by NaiboWang** [comment]
先看看有没有同时打开两个程序如果有退了重开，再看看权限有没有给全，都不行就删掉重下试试。

**Comment by PhoenixMarco02** [comment]
重新下载了，仍然不行。权限的话就是按照演示视频里一样，系统偏好设置->仍要打开。报错还是和之前的一样。

**Comment by NaiboWang** [comment]
你确认你只开了一个程序吗？有没有多个账户同时登录打开了软件多次？下面任务栏里右键退出之后重新打开试过吗？
不行重启试试，这个错误很简单，就是系统的8084端口被占用了启动不了服务器。

**Comment by PhoenixMarco02** [comment]
下面任务栏里右键退出之后重新打开还是同样的报错，重启也试过了，也是同样的报错。（确认只开了一个程序，而且通过终端查看8074端口没被占用）

**Comment by PhoenixMarco02** [comment]
好的，感谢，那我等一下0.3.2试试

**Comment by NaiboWang** [comment]
好的，感谢提供解决方案！
