### ISSUE TITLE
修改流程时，如果从中间某个节点修改，浏览器网页怎么同步到此位置，进行可视化修改

### ISSUE THREAD

**Issue by yinyanling-ludong** [NaiboWang/EasySpider#72]
修改流程时，可视化网页总是从头开始，怎么快速定位到要修改的节点，进行网页可视化重新编辑，或者能够自动执行到要修改节点同步也行。

**Comment by NaiboWang** [comment]
调整锚点，建议多看B站视频教程，都有讲。

**Comment by yinyanling-ludong** [comment]
@NaiboWang 你好，我看了B站大部分视频都是从头开始设计的，我意思是调整锚点位置后，浏览器元素界面怎么能对应到锚点上一个节点，我好接着能在浏览器元素界面接着可视化操作，现在好像我没有参考到类似的某个视频，是我没注意到么。。。，现在我测试的是当我修改流程设计时，可视化界面还是从登录开始的，虽然我的锚点可以定位，但是可视化界面元素没有跟到那个节点
<img width="947" alt="1685950266282" src="https://github.com/NaiboWang/EasySpider/assets/134027845/48d8598b-351f-4108-b34e-388d695fec95">

**Comment by NaiboWang** [comment]
B站视频有说如何登录后采集，另外就是你这种情况可以手动登录之后进入你想要的页面即可，手动登录方式为鼠标移动到输入框按键盘F9键输入用户名密码，然后左键点击登录即可。
