### ISSUE TITLE
需要登录的网站获取cookie不正确导致运行爬取未登录

### ISSUE THREAD

**Issue by liuyang77886** [NaiboWang/EasySpider#75]
网站http://www.yiparts.com/models/
版本0.31
操作系统win10

实际cookie：
Searchcompany=%E6%AC%A7%E5%8F%8B; Searchall=; _dx_captcha_cid=57730450; _dx_uzZo5y=c5e28ed9b5c2009f83488e298a5430c1fe0648a1043ace049625f5a3574b1784487e6349; _dx_FMrPY6=64760546KFq0yqjirm1xslULf9EZ06JHFlyf4lD1; _dx_captcha_vid=2012CDDEEF6AED362C17BC60949FB7CEE7C276C0F95E03A683EE45125D95132C0477A47F139302C72E427A4CC5072D7B7BC4ECB734D9A6613F2F902973CC1105A0BCC86183B12A3E69A6E6FF6C3398E5; SearchType=all; acw_tc=2f624a5916861814331167470e4740a7d736da27512f461183ddba038fb5d9; PHPSESSID=m6chnochcdoofi3lac65f7plmd; Hm_lvt_d6d66a78d863e895c324e752879449ea=1685751655,1685971999,1686108133,1686181441; SL_G_WPT_TO=zh; SL_GWPT_Show_Hide_tmp=1; SL_wptGlobTipTmp=1; unitag=l50HNDxAZjBonmoysOt2eCIEd3Xta0NB0L92bMafKDRZLAM1d31qd7JXZWmgeXhsW058NLd5enjYckQ0l93UeVMmdj0%3D; Hm_lpvt_d6d66a78d863e895c324e752879449ea=1686182033

爬取cookie：

SearchType=all; acw_tc=2f624a5416861814469126983e1bb59ee8967c7e73bd50c35c5abade9656a3; PHPSESSID=6pfg8o2q7qg7bvrf7gdfd6r58m; Hm_lvt_d6d66a78d863e895c324e752879449ea=1686181759,1686181804,1686181868,1686182105; Hm_lpvt_d6d66a78d863e895c324e752879449ea=1686182105

**Comment by NaiboWang** [comment]
B站视频有讲需要登录如何爬，建议观看。

**Comment by liuyang77886** [comment]
你都没看问题

**Comment by NaiboWang** [comment]
你的问题太模糊了，请把你从头到尾如何操作的全部过程写下来，一步一步怎么执行的，你期待有什么结果，最终结果是什么样子，到哪一步出了问题。如果我的理解没有错，你是先使用了带用户信息登录浏览器登录之后在浏览器端获取的cookie？因为软件本身的逻辑不是通过获取和写入cookie的方式去搞登录信息，所以请补充问题详细说明。

**Comment by liuyang77886** [comment]
目的是使用带cookie方式进行爬取
第一步运行程序，点击《设计任务》->《使用带用户信息浏览器设计》->登录信息目录默认->《开始设计》，创建任务并运行，并登录，此时查看cookie信息有9条，设置等待时间，然后保存，然后使用在首页->任务信息->任务调用->选择默认的用户数据目录，并点击《本地直接执行（带用户信息模式）》 打开网站后，仍然没有登录，通过查看浏览器的cookie只有4条，

**Comment by NaiboWang** [comment]
你用电脑上自己平常使用的浏览器登录一下，看一下cookie，然后完全关闭浏览器再重新打开，再看一下cookie看结果是不是一样，如果一样就说明这个网站的设计本身就是每次重新打开浏览器，都需要重新登录，cookie会被重置。
这种情况下你可以预留时间手工操作登录，或者设定好用户名密码的操作进行输入登录。
下个版本会添加预定义cookie功能。

**Comment by liuyang77886** [comment]
我需要在启动前校验cookie正确与否，不正确先手动修改cookie，然后在启动运行执行爬虫，现在是否能支持找到cookie文件并修改，如果不能支持下次什么时候能出来呢

**Comment by NaiboWang** [comment]
参考这篇文章：https://www.cnblogs.com/Marydon20170307/p/11613226.html

由于0.3.2版本刚刚发布，因此下一个版本可能要等一段时间才发布，如果等不及也可以自己根据源代码编译一个适合自己需求的版本，参考以下selenium加载cookie的代码：https://www.cnblogs.com/sundahua/p/10202494.html
