### ISSUE TITLE
此种报错信息是如何导致的？麻烦您看一下，谢谢！

### ISSUE THREAD

**Issue by DorisXiaan** [NaiboWang/EasySpider#78]
chrome_win64/easyspider_executestage.exe
Windows找不到文件‘chrome_win64/easyspider_executestage.exe'。请确定文件名是否正确后，再试一次。

**Comment by DorisXiaan** [comment]
重新下载了一下，可以使用了，感谢您解答！

**Comment by 3420643039** [comment]
我刚刚也有遇到过这个问题，但是昨天在调用任务的时候并没有出现这种情况
