### ISSUE TITLE
提取iframe中数据，xpath无法确定位置，请问用什么方法可以处理？

### ISSUE THREAD

**Issue by therocflyinginbluesky** [NaiboWang/EasySpider#79]
版本：0.3.2
提取数据页面：https://music.163.com/#/discover/toplist?id=71384707
https://music.163.com/discover/toplist?id=71384707
![截图](https://github.com/NaiboWang/EasySpider/assets/133950042/47634910-8be8-4703-99d4-aee0b39faa31)
提取数据时，发现用鼠标无法选择元素，有提示要求重新建任务，将网页的#删除，重新设置依然无法选择元素。调试网页，发现数据在iframe中，xpath无法确定数据的位置，请问用什么方法可以处理？

**Comment by NaiboWang** [comment]
目前版本暂时无法处理iframe所有情况，下个版本将支持所有iframe的处理。

**Comment by therocflyinginbluesky** [comment]
好的，谢谢。期待下个版本。

**Comment by NaiboWang** [comment]
0.3.5版本已经支持iframe，请关注。
