### ISSUE TITLE
这种报错信息是什么原因，麻烦作者大大，谢谢

### ISSUE THREAD

**Issue by hepingfly** [NaiboWang/EasySpider#80]
不需要登录信息的网站可以正常爬取数据，在爬取需要登录信息网站时候软件报这个错误
chromeDriver 特地去下了一个和chrome的版本匹配的

<img width="1845" alt="iShot_2023-06-15_18 27 19" src="https://github.com/NaiboWang/EasySpider/assets/18638517/460e50e5-a2f0-4d58-b8d9-ff88b3a74ed3">

**Comment by NaiboWang** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/9d9c2049-32c2-4ed3-8baf-285724e760ce)
用户目录文件存在这个绝对路径地址，因此macos必须用相对路径写文件夹，如`./user_data`
