### ISSUE TITLE
关于软件使用的几个问题和几点建议（mac端）

### ISSUE THREAD

**Issue by whalerwho** [NaiboWang/EasySpider#81]
您好，软件很好用，感谢您的付出，使用中有几个问题请教下您：

1. 能否把同一任务多次执行结果合并到同一个输出文档中（使用场景：比如我关注某小区的房价，我想实现每天系统执行一次任务，并把数据合并到同一个文档中，便于比较）
2. 文档命名能否自定义，比如基于时间和任务名称的组合命名，便于识别，如，20230605天津房价
3. 如果同一任务中涉及到了多个不同表头内容的抓取，能否分sheet存储。（使用场景：比如我要抓取某小区房价的概览及列表信息，概览不需要循环，列表信息需要循环读取，这两个需求会产生两个表头，实际使用中会出现概览信息的表头下内容出现循环列表信息中某一列信息内容的情况，而循环列表中该字段下内容为空）
4. 纯净模式的输出目录能否自定义或者基于任务名称自动建立文件夹（解决不同任务之间信息错乱的问题）

以上，感谢您的时间

**Comment by NaiboWang** [comment]
1和2只需要修改`--saved_file_name`字段为指定名称，指定名称相同则会写入同一文件，参考：
https://github.com/NaiboWang/EasySpider/wiki/Argument-Instruction
3 建议分成两个任务执行
4 目前不做考虑，因为此类需求太多而且不同人的要求不同，有要求不同文件夹的，有要求不同目录的，有要求保持不变的，也有要求写入数据库的。对于此类要求，大家可以自行修改代码更改逻辑，因为无法制定统一标准。

**Comment by NaiboWang** [comment]
以上功能均已实现，包括导入MySQL数据库功能的版本已发布，欢迎使用。
