### ISSUE TITLE
作者，我有一个好想法，能不能自动生成spider项目代码，然后一些扩展功能我们自己写。

### ISSUE THREAD

**Issue by Hollywood3** [NaiboWang/EasySpider#82]

**Comment by NaiboWang** [comment]
确实是个好想法，已经有很多项目实现了，如微软的PlayWright就是做这个事情的，如果想要更细力度的修改代码，可以考虑用PlayWright：

https://github.com/microsoft/playwright

因为EasySpider还是想要面向不太会写代码的人群的，加上已经带了自定义操作可以自行Python和JS代码，已经可以满足绝大多数目标用户的需求了，如果要生成代码，那需要很长时间的重构和开发，目前暂时没有这个时间。

谢谢建议~
