### ISSUE TITLE
请问该如何获取302跳转后的网址?

### ISSUE THREAD

**Issue by hjl4am** [NaiboWang/EasySpider#83]
有一个文章列表，列表的网址形式为：a.com/123.html
但该地址使用了302跳转，实际打开的网址为：b.com/456.html
我看软件里有循环打开列表网址，然后也有获取页面网址的功能。但两者如何组合，我不知道这个流程。
请指教。

**Comment by NaiboWang** [comment]
跳转后直接获取当前页面网址即可，地址栏显示的网址就是提取到的网址。
