### ISSUE TITLE
mac m1 pro 无法使用带用户信息浏览器设计

### ISSUE THREAD

**Issue by keeepman** [NaiboWang/EasySpider#85]
macos monterey 12.5,芯片是m1 pro，点击开启设计无法自动生成文件夹，并且手动新增文件夹后登陆信息也没有保存在该文件夹下
![21151687226637_ pic](https://github.com/NaiboWang/EasySpider/assets/84370820/7a5859da-5f2e-4621-9cd6-f671c7f5f72f)

**Comment by NaiboWang** [comment]
MacOS生成的文件夹不在这个目录，在软件使用说明里那个任务文件夹里同级目录，可以正常使用的你试试就知道了。
