### ISSUE TITLE
localhost:8074无法访问需要怎么办？

### ISSUE THREAD

**Issue by ferrarizrw** [NaiboWang/EasySpider#86]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8074): Max retries exceeded with url: /queryExecutionInstance?id=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b45c940>: Failed to establish a new connection: [Errno 61] Connection refused'))
<img width="1460" alt="image" src="https://github.com/NaiboWang/EasySpider/assets/137139548/5b521ca6-0bb3-4527-8f71-9543c753c817">

**Comment by NaiboWang** [comment]
你是不是没打开EasySpider主程序？
