### ISSUE TITLE
cloudflare真人认证，点击后还是一直重复要求验证。

### ISSUE THREAD

**Issue by lobsterforsale** [NaiboWang/EasySpider#89]
网址：https://www.wcxsw.org/
问题：Cloudflare认证一直重复，无法通过。
详细：该网站是个小说网站。使用搜索功能会触发cloudflare真人验证，但是鼠标点击后无法通过，一直重复要求认证。
图片过程如下：
![image](https://github.com/NaiboWang/EasySpider/assets/68791260/52cdc8dc-371c-4857-90f2-9ccb2ced22ff)
![image](https://github.com/NaiboWang/EasySpider/assets/68791260/9319f5a2-b5a7-4f76-ac24-5b2d71c1ea83)

**Comment by NaiboWang** [comment]
Cloudflare有解决方案但现版本不支持，将来会贴出如何处理的方案。

**Comment by lobsterforsale** [comment]
感谢Naibo！

**Comment by 425765923** [comment]
> Cloudflare最新版本已经支持，但需要配置，很快将发布视频教程，请关注。

看了视频，似乎涉及cloudflare的网址没有办法保存cookie登陆信息。每次爬都需要重新登陆

**Comment by NaiboWang** [comment]
> > Cloudflare最新版本已经支持，但需要配置，很快将发布视频教程，请关注。
> 
> 看了视频，似乎涉及cloudflare的网址没有办法保存cookie登陆信息。每次爬都需要重新登陆

注意到问题并修复了此bug，可以下载最新版本使用。
