### ISSUE TITLE
如何手动输入用户名和密码

### ISSUE THREAD

**Issue by LG2016** [NaiboWang/EasySpider#91]
不用扫码登陆，手动输入用户名和密码如何输入呢？选中输入框，不能手动输入，麻烦了，谢谢。
![image](https://github.com/NaiboWang/EasySpider/assets/16609877/0195c0a9-6986-427a-88b7-3765b76f1ba9)

**Comment by NaiboWang** [comment]
两种方式：
1. 选中输入框后输入文字。
2. 直接鼠标移动到输入框然后按键盘F9聚焦后输入。

区别就是前者会记录输入文字的操作在流程图里，后者不会。
