### ISSUE TITLE
用户信息目录创建不成功

### ISSUE THREAD

**Issue by wxyaxxy** [NaiboWang/EasySpider#93]
您好，我无法使用cookie来免登录，以下是具体信息
------------
Apple M2
Macos Ventura
我把EasySpider_MacOS_all_arch下载到download目录然后解压
直接点击运行EasySpider应用程序
“设计任务”->"使用带用户信息浏览器设计“->默认”./user_data“->”开始设计“，
在~/Downloads/EasySpider_MacOS_all_arch/目录下未创建"user_data"文件夹
后续设计的时候，通过扫码登录到JD，然后抓取了一些数据，保存任务
再次执行任务的时候，还是需要重新登陆
-------------
备注：
在”设置“->"隐私与安全性”->"文件和文件夹“->EasySpider已经提供了”下载“目录的访问权限
----------
望指点，谢谢

**Comment by NaiboWang** [comment]
MacOS你的这种方式，用户目录已经被创建了，但没有创建在当前目录下，而是在软件使用说明里面的那个目录里。
另外就是京东的设定本来就是每次重新打开浏览器都需要重新登录，所以无论哪种模式都一样。
