### ISSUE TITLE
翻页之后网址不变的网站无法抓取

### ISSUE THREAD

**Issue by DorisXiaan** [NaiboWang/EasySpider#94]
网站：https://www.xylink.com/news。
此网站在网页上提供了翻页按钮，但是：
1. 翻页之后网站链接不变；
2. 详情页不支持“在新标签页打开”；
3. 从第二页列表打开的详情页链接会直接返回到第一页列表的网页；

我通过翻页循环进行抓取的时候，Xpath确实定位到了下一页按钮，但是：
1. 抓取的结果只到第二页的第一条链接的详情页；
2. 在此链接处一直反复抓取；

请问您这种情况应该怎么处理呢？谢谢！

**Comment by NaiboWang** [comment]
这个页面设计的逻辑有点反人类，后退后会返回第一页，因此无法直接按照正常逻辑翻页，只能设计24个循环每次点击一个不同的页码按钮，或者手工干预一下。

**Comment by NaiboWang** [comment]
另一种方式是根据js定义翻页流程，设置变量来设置翻页次数。

**Comment by NaiboWang** [comment]
实验成功，用自定义操作在打开网页后定义一个变量let_a:

```JavaScript
let_a = 1;
```
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/dc263af5-2fdf-4014-bfca-368acef5e8db)

然后把循环点击下一页的点击操作删掉，并在开头增加翻页的自定义操作，JS代码：

```JavaScript
for(let i=0;i<let_a;i++){
$x('//*[contains(@class, "ant-pagination-next")]/button[1]')[0].click();
}
let_a = let_a + 1;
```
![image](https://github.com/NaiboWang/EasySpider/assets/30287768/10187e34-a4c7-4dfe-bff5-02bb94149b8b)

**Comment by DorisXiaan** [comment]
超级感谢您的详细解答！
