### ISSUE TITLE
循环体内的点击元素能使用相对循环体的xpath吗？

### ISSUE THREAD

**Issue by wzt0501** [NaiboWang/EasySpider#95]
<img width="960" alt="16878490522550" src="https://github.com/NaiboWang/EasySpider/assets/75840452/495d96df-694c-4d95-8e20-e44f630d97cf">
<img width="960" alt="16878491148691" src="https://github.com/NaiboWang/EasySpider/assets/75840452/cfa157a2-4f22-4457-a666-a19d43514185">

循环体内的点击元素不能使用相对循环体的xpath吗？

**Comment by NaiboWang** [comment]
能不能描述下你的需求，为什么需要相对循环体的点击元素，有没有尝试过浏览器中选中全部链接后点击“循环点击每个链接”？

**Comment by wzt0501** [comment]
试过这个，如果光只提取详情页的是可以的，但列表页有的数据有的需要，因为详情页的html格式不一定是一样的，主要是数据补全。我看你的视频列表页和详情页分开两套流程，且链接需要人工导入，量多有点麻烦，想试试在一套流程里实现可不可行

**Comment by wzt0501** [comment]
<img width="606" alt="企业微信截图_1687860852630" src="https://github.com/NaiboWang/EasySpider/assets/75840452/1e2a1730-38a8-4805-826e-f3765116e8df">
按你的思路我提取不到和点击元素同父级元素下的其他元素，是不是我操作问题

**Comment by wzt0501** [comment]
<img width="606" alt="企业微信截图_1687860852630" src="https://github.com/NaiboWang/EasySpider/assets/75840452/9fe12891-b515-44fa-ac67-70d029ff15d3">
我试了，循环点击每个链接，在点击元素前提取数据，但同父级元素下的其他元素定位不到，是不是我操作问题。

**Comment by NaiboWang** [comment]
用`*../../td[3]`表示相对XPath。
