### ISSUE TITLE
循环列表后需要在两次点击详情链接后提取数据只能返回第一条而后报错

### ISSUE THREAD

**Issue by durongzhen** [NaiboWang/EasySpider#96]
1. 这是列表数据：
![2](https://github.com/NaiboWang/EasySpider/assets/25242234/cedb03e5-656d-4f8b-9fa9-1cc92103997c)
需要再点击详情后跳转到详情页面：
![3](https://github.com/NaiboWang/EasySpider/assets/25242234/088763df-82e4-4611-9c03-f3c86ae01f76)
然后点击“大气污染物排放信息”进入详情页面提取数据。
2.流程如下：
![1](https://github.com/NaiboWang/EasySpider/assets/25242234/e1731645-ee3b-436f-a026-3163ed288b1a)
目前遇到的问题：
只能提取到列表第一条数据。
log如下：
“openPage
Loading page: http://permit.mee.gov.cn/perxxgkinfo/syssb/xkgg/xkgg!licenseInformation.action
Click
loop
loop
Click
Click
getData
Click
Click
Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=114.0.5735.91)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x009FA813+48355]
	(No symbol) [0x0098C4B1]
	(No symbol) [0x00895358]
	(No symbol) [0x008987A1]
	(No symbol) [0x0089A19B]
	(No symbol) [0x008ED279]
	(No symbol) [0x008DA73C]
	(No symbol) [0x008EC922]
	(No symbol) [0x008DA536]
	(No symbol) [0x008B82DC]
	(No symbol) [0x008B93DD]
	GetHandleVerifier [0x00C5AABD+2539405]
	GetHandleVerifier [0x00C9A78F+2800735]
	GetHandleVerifier [0x00C9456C+2775612]
	GetHandleVerifier [0x00A851E0+616112]
	(No symbol) [0x00995F8C]
	(No symbol) [0x00992328]
	(No symbol) [0x0099240B]
	(No symbol) [0x00984FF7]
	BaseThreadInitThunk [0x756E00C9+25]
	RtlGetAppContainerNamedObjectPath [0x76F07B4E+286]
	RtlGetAppContainerNamedObjectPath [0x76F07B1E+238]
”

**Comment by NaiboWang** [comment]
政府网站不予答疑，问题关闭。
