### ISSUE TITLE
测试中出现白屏且长时间等待后依然无法获取元素

### ISSUE THREAD

**Issue by feazhou** [NaiboWang/EasySpider#97]
版本0.3.2，程序调用的Chrome版本为114.0.5735.91

新建任务打开网页地址为https://www.nmpa.gov.cn/

Chrome窗口加载不出任何元素但有操作提示框，屏幕为全白色
![无法加载元素](https://s3.bmp.ovh/imgs/2023/06/28/108ff44f914c1479.jpg
)

无论等待多久都没有正常加载，其他gov.cn网站测试正常，请问这该如何解决？

**Comment by NaiboWang** [comment]
请看声明，政府网站不予答疑，问题关闭。
