### ISSUE TITLE
循环列表后需要在两次点击详情链接后提取数据只能返回第一条

### ISSUE THREAD

**Issue by durongzhen** [NaiboWang/EasySpider#98]
网站：https://read.douban.com/original/featured/fast-selling-finalized
流程：循环列表数据点击链接进入详情页面点击“免费试读”，提取内容章节数据。
问题：只能返回列表页面第一条数据。看浏览器执行，只对第一条数据执行了“免费试读”点击操作，其他均报错。
日志文件如下：
Click
Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=114.0.5735.91)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x011CA813+48355]
	(No symbol) [0x0115C4B1]
	(No symbol) [0x01065358]
	(No symbol) [0x010687A1]
	(No symbol) [0x0106A19B]
	(No symbol) [0x010BD279]
	(No symbol) [0x010AA73C]
	(No symbol) [0x010BC922]
	(No symbol) [0x010AA536]
	(No symbol) [0x010882DC]
	(No symbol) [0x010893DD]
	GetHandleVerifier [0x0142AABD+2539405]
	GetHandleVerifier [0x0146A78F+2800735]
	GetHandleVerifier [0x0146456C+2775612]
	GetHandleVerifier [0x012551E0+616112]
	(No symbol) [0x01165F8C]
	(No symbol) [0x01162328]
	(No symbol) [0x0116240B]
	(No symbol) [0x01154FF7]
	BaseThreadInitThunk [0x756E00C9+25]
	RtlGetAppContainerNamedObjectPath [0x76F07B4E+286]
	RtlGetAppContainerNamedObjectPath [0x76F07B1E+238]

getData
动图：
![动画3](https://github.com/NaiboWang/EasySpider/assets/25242234/12862caa-d2b5-4b6c-a31f-7345863f27d6)

**Comment by NaiboWang** [comment]
每个页面的结构会发生变化所以XPath不是所有页面都一样，需要修改，具体修改方式请学习B站视频或者问QQ群友。

**Comment by durongzhen** [comment]
> 每个页面的结构会发生变化所以XPath不是所有页面都一样，需要修改，具体修改方式请学习B站视频或者问QQ群友。

换了多种写法，都无法匹配，如：“//span[text()='免费试读']”，标签文本实际上是不变的

**Comment by NaiboWang** [comment]
看看推荐的写法，还不行请加群问，issues一般是来提软件的bug和功能需求之类问题的，对于不属于软件本身功能型的问题，比如如何设置xpath什么的，我这边没时间一一解答，请理解。

**Comment by durongzhen** [comment]
> 

好的
